interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: ARDUINO-F103-I2C.bin
    permissions: rwx
    size: 0x15b00
symbols:
  0x0: reent.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x800010d: __do_global_dtors_aux
  0x8000131: frame_dummy
  0x8000179: strlen
  0x8000189: setup
  0x8000199: loop
  0x8000209: _ZN7TwoWire9availableEv
  0x800021d: _ZN7TwoWire4readEv
  0x8000249: _ZN7TwoWire4peekEv
  0x8000271: _ZN7TwoWire16onRequestServiceEv
  0x8000295: _ZN7TwoWire5flushEv
  0x80002ed: _ZN7TwoWire5writeEPKhj
  0x8000389: _ZN7TwoWire5writeEh
  0x8000419: _ZN7TwoWireC2Ev
  0x8000445: _Z41__static_initialization_and_destruction_0ii
  0x8000465: _ZN7TwoWire5beginEh
  0x8000519: _ZN7TwoWire5beginEi
  0x8000523: _ZN7TwoWire5beginEv
  0x800052d: _ZN7TwoWire17beginTransmissionEh
  0x8000555: _ZN7TwoWire17beginTransmissionEi
  0x8000561: _ZN7TwoWire15endTransmissionEh
  0x80005c9: _ZN7TwoWire15endTransmissionEv
  0x80005d5: _ZN7TwoWire16allocateRxBufferEj
  0x8000609: _ZN7TwoWire16onReceiveServiceEPhi
  0x8000671: _ZN7TwoWire11requestFromEhhmhh
  0x8000709: _ZN7TwoWire11requestFromEhhh
  0x800071d: _ZN7TwoWire11requestFromEii
  0x800072b: _GLOBAL__sub_I__ZN7TwoWire8rxBufferE
  0x8000739: SystemClock_Config
  0x80007d9: Reset_Handler
  0x80007dc: CopyDataInit
  0x80007e4: LoopCopyDataInit
  0x80007f2: FillZerobss
  0x80007f8: LoopFillZerobss
  0x8000820: Default_Handler
  0x8000821: USB_HP_CAN1_TX_IRQHandler
  0x8000823: init
  0x800082b: HAL_MspInit
  0x800082d: HAL_InitTick
  0x8000879: HAL_Init
  0x800089d: HAL_IncTick
  0x80008b5: HAL_GetTick
  0x80008c1: HAL_NVIC_SetPriorityGrouping
  0x80008e5: HAL_NVIC_SetPriority
  0x8000949: HAL_NVIC_EnableIRQ
  0x8000965: HAL_SYSTICK_Config
  0x8000991: HAL_NVIC_ClearPendingIRQ
  0x80009b1: HAL_SYSTICK_CLKSourceConfig
  0x80009d1: HAL_SYSTICK_Callback
  0x80009d3: HAL_SYSTICK_IRQHandler
  0x80009dd: HAL_DMA_Abort_IT
  0x8000a75: HAL_GPIO_Init
  0x8000c61: HAL_GPIO_EXTI_IRQHandler
  0x8000c7d: I2C_Master_SB
  0x8000d07: I2C_Master_ADD10
  0x8000d13: I2C_Master_ADDR
  0x8000eed: I2C_SlaveTransmit_BTF
  0x8000f0d: I2C_SlaveReceive_BTF
  0x8000f2d: HAL_I2C_MspInit
  0x8000f31: HAL_I2C_Init
  0x8001099: HAL_I2C_Master_Transmit_IT
  0x8001165: HAL_I2C_Master_Receive_IT
  0x8001239: HAL_I2C_Slave_Sequential_Transmit_IT
  0x80012c5: HAL_I2C_Slave_Sequential_Receive_IT
  0x8001351: HAL_I2C_EnableListen_IT
  0x800138f: HAL_I2C_MasterTxCpltCallback
  0x8001391: HAL_I2C_MasterRxCpltCallback
  0x8001393: HAL_I2C_SlaveTxCpltCallback
  0x8001395: I2C_SlaveTransmit_TXE
  0x80013e5: HAL_I2C_SlaveRxCpltCallback
  0x80013e7: I2C_SlaveReceive_RXNE
  0x8001433: I2C_Slave_ADDR
  0x800145d: I2C_Slave_AF
  0x80014f1: HAL_I2C_MemTxCpltCallback
  0x80014f3: I2C_MasterTransmit_TXE
  0x800163d: I2C_MasterTransmit_BTF
  0x80016db: HAL_I2C_MemRxCpltCallback
  0x80016dd: I2C_MasterReceive_RXNE
  0x80017ad: I2C_MasterReceive_BTF
  0x80018ab: HAL_I2C_AbortCpltCallback
  0x80018ad: I2C_ITError
  0x80019f5: I2C_Slave_STOPF
  0x8001af9: HAL_I2C_EV_IRQHandler
  0x8001c61: HAL_I2C_ER_IRQHandler
  0x8001d3d: I2C_DMAAbort
  0x8001d9b: HAL_I2C_GetState
  0x8001da1: HAL_I2C_GetError
  0x8001da5: RCC_Delay
  0x8001dd1: HAL_RCC_OscConfig
  0x80021b1: HAL_RCC_GetSysClockFreq
  0x800221d: HAL_RCC_ClockConfig
  0x800238d: HAL_RCC_GetHCLKFreq
  0x8002399: HAL_RCC_GetPCLK1Freq
  0x80023b9: HAL_RCC_GetPCLK2Freq
  0x80023d9: HAL_RCCEx_PeriphCLKConfig
  0x80024ed: HAL_RTC_AlarmIRQHandler
  0x8002525: HAL_TIM_IC_CaptureCallback
  0x8002527: HAL_TIM_PWM_PulseFinishedCallback
  0x8002529: HAL_TIM_TriggerCallback
  0x800252b: HAL_TIM_IRQHandler
  0x80026a5: HAL_TIMEx_CommutationCallback
  0x80026a7: HAL_TIMEx_BreakCallback
  0x80026a9: UART_EndRxTransfer
  0x80026c5: UART_Transmit_IT
  0x8002731: UART_SetConfig
  0x80028e1: UART_WaitOnFlagUntilTimeout
  0x8002945: HAL_UART_MspInit
  0x8002947: HAL_UART_Init
  0x80029a5: HAL_UART_Transmit
  0x8002a87: HAL_UART_Transmit_IT
  0x8002acf: UART_EndTransmit_IT
  0x8002ae9: UART_Receive_IT
  0x8002b89: HAL_UART_IRQHandler
  0x8002ca9: UART_DMAAbortOnError
  0x8002cb9: HAL_UART_GetState
  0x8002cc5: set_GPIO_Port_Clock
  0x8002d6d: noOsSystickHandler
  0x8002d6f: SysTick_Handler
  0x8002d7f: hw_config_init
  0x8002d8b: pinmap_find_peripheral
  0x8002da5: pinmap_peripheral
  0x8002db7: pinmap_find_pin
  0x8002dcf: pinmap_pin
  0x8002ddf: pinmap_find_function
  0x8002dfb: pinmap_function
  0x8002e0f: pinmap_merge_peripheral
  0x8002e21: HAL_RTC_AlarmAEventCallback
  0x8002e39: RTC_Alarm_IRQHandler
  0x8002e49: _Error_Handler
  0x8002e4d: SystemInit
  0x8002e99: get_timer_obj
  0x8002e9d: HAL_TIM_OC_DelayElapsedCallback
  0x8002eb7: HAL_TIM_PeriodElapsedCallback
  0x8002ec5: TIM1_UP_IRQHandler
  0x8002ed9: TIM2_IRQHandler
  0x8002eed: TIM3_IRQHandler
  0x8002f01: TIM4_IRQHandler
  0x8002f15: i2c_custom_init
  0x80035d9: i2c_master_write
  0x8003643: i2c_slave_write_IT
  0x8003673: i2c_master_read
  0x80036dd: get_i2c_obj
  0x80036e1: i2c_attachSlaveRxEvent
  0x80036f3: i2c_attachSlaveTxEvent
  0x8003705: HAL_I2C_AddrCallback
  0x8003755: HAL_I2C_ListenCpltCallback
  0x8003785: HAL_I2C_ErrorCallback
  0x800379d: I2C1_EV_IRQHandler
  0x80037ad: I2C1_ER_IRQHandler
  0x80037bd: I2C2_EV_IRQHandler
  0x80037cd: I2C2_ER_IRQHandler
  0x80037dd: uart_init
  0x8003c15: uart_debug_init
  0x8003c65: uart_debug_write
  0x8003d1d: serial_tx_active
  0x8003d41: uart_attach_tx_callback
  0x8003d95: uart_index
  0x8003db9: HAL_UART_RxCpltCallback
  0x8003ddd: HAL_UART_TxCpltCallback
  0x8003e29: HAL_UART_ErrorCallback
  0x8003e69: USART1_IRQHandler
  0x8003e81: USART2_IRQHandler
  0x8003e99: USART3_IRQHandler
  0x8003eb1: _sbrk
  0x8003eed: _close
  0x8003ef3: _fstat
  0x8003efd: _isatty
  0x8003f01: _lseek
  0x8003f05: _read
  0x8003f09: _write
  0x8003f15: _exit
  0x8003f19: _kill
  0x8003f29: _getpid
  0x8003f2d: _ZN14HardwareSerial16_tx_complete_irqEP8serial_s
  0x8003f61: _ZN14HardwareSerial9availableEv
  0x8003f75: _ZN14HardwareSerial4peekEv
  0x8003f91: _ZN14HardwareSerial4readEv
  0x8003fb9: _ZN14HardwareSerial5flushEv
  0x8003fcd: _ZN14HardwareSerial5writeEh
  0x800401d: _Z14serialEventRunv
  0x8004049: _ZN14HardwareSerial4initEv
  0x800406d: _ZN14HardwareSerial5setRxEm
  0x8004085: _ZN14HardwareSerial5setTxEm
  0x800409d: _ZN14HardwareSerialC1EPv
  0x80040f9: _Z41__static_initialization_and_destruction_0ii
  0x800411d: _GLOBAL__sub_I_Serial2
  0x800412b: _ZNK9IPAddress7printToER5Print
  0x8004165: _ZN9IPAddressC1Ehhhh
  0x8004181: _Z41__static_initialization_and_destruction_0ii
  0x80041ad: _GLOBAL__sub_I__ZN9IPAddressC2Ev
  0x80041bb: _ZN5Print5writeEPKhj
  0x80041df: _ZN5Print5printEc
  0x80041e9: _ZN5Print11printNumberEmh
  0x8004243: _ZN5Print5printEmi
  0x8004259: _ZN5Print5printEhi
  0x8004261: _Z11initVariantv
  0x8004263: _Z7premainv
  0x8004271: main
  0x8004291: _ZL10get_pin_idt
  0x80042a5: __tcf_0
  0x80042cd: _Z41__static_initialization_and_destruction_0ii
  0x8004379: EXTI0_IRQHandler
  0x8004383: EXTI1_IRQHandler
  0x800438d: EXTI2_IRQHandler
  0x8004397: EXTI3_IRQHandler
  0x80043a1: EXTI4_IRQHandler
  0x80043ab: EXTI9_5_IRQHandler
  0x80043c1: EXTI15_10_IRQHandler
  0x80043d9: _ZNKSt8functionIFvvEEclEv
  0x80043e9: HAL_GPIO_EXTI_Callback
  0x8004409: _GLOBAL__sub_I__Z22stm32_interrupt_enableP12GPIO_TypeDeftSt8functionIFvvEEm
  0x8004417: __aeabi_atexit
  0x8004421: __cxa_atexit
  0x800443d: __libc_init_array
  0x8004485: memcpy
  0x800449b: memset
  0x80044ad: _free_r
  0x8004545: _malloc_r
  0x8004601: __sfputc_r
  0x800462d: __sfputs_r
  0x8004651: _vfiprintf_r
  0x800487d: _printf_common
  0x800496d: _printf_i
  0x8004bad: iprintf
  0x8004bdd: realloc
  0x8004bed: _sbrk_r
  0x8004c0d: __swbuf_r
  0x8004cb1: __swsetup_r
  0x8004d8d: abort
  0x8004d9d: __sflush_r
  0x8004ead: _fflush_r
  0x8004f01: _cleanup_r
  0x8004f0d: std.isra.0
  0x8004f55: __sfmoreglue
  0x8004f81: __sinit
  0x8004fe1: __sfp
  0x8005059: _fwalk_reent
  0x8005095: __swhatbuf_r
  0x80050dd: __smakebuf_r
  0x800515d: memchr
  0x8005179: __malloc_lock
  0x800517b: __malloc_unlock
  0x800517d: _realloc_r
  0x80051c9: _raise_r
  0x8005219: raise
  0x8005229: _kill_r
  0x800524d: _getpid_r
  0x8005251: __sread
  0x8005273: __swrite
  0x80052ab: __sseek
  0x80052cf: __sclose
  0x80052d9: _write_r
  0x80052fd: _close_r
  0x800531d: _fstat_r
  0x8005341: _isatty_r
  0x8005361: _lseek_r
  0x8005385: _malloc_usable_size_r
  0x8005399: _read_r
  0x80053bd: _ZSt25__throw_bad_function_callv
  0x80053c5: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKSsj
  0x8005489: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKSsj
  0x800554d: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x80055d1: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x8005654: __EH_FRAME_BEGIN__
  0x8005655: _init
  0x8005661: _fini
  0x800566c: _etext
  0x80056d4: _ZTV7TwoWire
  0x80056f4: PinMap_I2C_SCL
  0x8005724: PinMap_I2C_SDA
  0x8005754: PinMap_UART_RX
  0x800579c: PinMap_UART_TX
  0x8005840: digitalPin
  0x800587c: AHBPrescTable
  0x800588c: APBPrescTable
  0x8005930: _ZTV14HardwareSerial
  0x8005950: _ZTV9IPAddress
  0x800595c: _global_impure_ptr
  0x8005994: __sf_fake_stderr
  0x80059b4: __sf_fake_stdin
  0x80059d4: __sf_fake_stdout
  0x80059f4: __exidx_end
  0x80059f8: __frame_dummy_init_array_entry
  0x8005a1c: __init_array_end
  0x8005a20: _sidata
  0x20000000: __dso_handle
  0x20000004: uwTickFreq
  0x20000008: uwTickPrio
  0x2000000c: SystemCoreClock
  0x20000010: serial_debug
  0x2000007c: _impure_ptr
  0x20000080: impure_data
  0x200000e0: _edata
  0x200000e4: object.8672
  0x200000fc: reading
  0x20000100: Wire
  0x200001a0: _ZN7TwoWire12transmittingE
  0x200001a1: _ZN7TwoWire13rxBufferIndexE
  0x200001a2: _ZN7TwoWire13txBufferIndexE
  0x200001a3: _ZN7TwoWire14rxBufferLengthE
  0x200001a4: _ZN7TwoWire14txBufferLengthE
  0x200001a8: _ZN7TwoWire14user_onReceiveE
  0x200001ac: _ZN7TwoWire14user_onRequestE
  0x200001b0: _ZN7TwoWire17rxBufferAllocatedE
  0x200001b1: _ZN7TwoWire17txBufferAllocatedE
  0x200001b4: _ZN7TwoWire8rxBufferE
  0x200001b8: _ZN7TwoWire8txBufferE
  0x200001bc: _ZN7TwoWire9txAddressE
  0x200001c0: RTCUserCallback
  0x200001c4: RtcHandle
  0x200001d8: callbackUserData
  0x200001dc: timer_handles
  0x20000234: i2c_handles
  0x2000023c: rx_callback
  0x20000250: rx_callback_obj
  0x20000264: tx_callback
  0x20000278: tx_callback_obj
  0x2000028c: uart_handlers
  0x200002a0: heap_end.4572
  0x200002a4: Serial2
  0x200003e8: _ZL11INADDR_NONE
  0x200003f0: _ZL13gpio_irq_conf
  0x20000530: __malloc_free_list
  0x20000534: __malloc_sbrk_start
  0x20000538: _ZGVNSt7collateIcE2idE
  0x2000053c: _ZGVNSt8messagesIcE2idE
  0x20000540: _ZGVNSt8time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000544: _ZGVNSt8time_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000548: _ZGVNSt11__timepunctIcE2idE
  0x2000054c: _ZGVNSt7num_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000550: _ZGVNSt7num_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000554: _ZGVNSt8numpunctIcE2idE
  0x20000558: _ZGVNSt9money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x2000055c: _ZGVNSt9money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000560: _ZGVNSt10moneypunctIcLb1EE2idE
  0x20000564: _ZGVNSt10moneypunctIcLb0EE2idE
  0x20000568: _ZGVNSt7collateIwE2idE
  0x2000056c: _ZGVNSt8messagesIwE2idE
  0x20000570: _ZGVNSt8time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000574: _ZGVNSt8time_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000578: _ZGVNSt11__timepunctIwE2idE
  0x2000057c: _ZGVNSt7num_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000580: _ZGVNSt7num_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000584: _ZGVNSt8numpunctIwE2idE
  0x20000588: _ZGVNSt9money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x2000058c: _ZGVNSt9money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000590: _ZGVNSt10moneypunctIwLb1EE2idE
  0x20000594: _ZGVNSt10moneypunctIwLb0EE2idE
  0x20000598: _ZGVNSt7__cxx117collateIwE2idE
  0x2000059c: _ZGVNSt7__cxx118messagesIwE2idE
  0x200005a0: _ZGVNSt7__cxx118time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200005a4: _ZGVNSt7__cxx118numpunctIwE2idE
  0x200005a8: _ZGVNSt7__cxx119money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200005ac: _ZGVNSt7__cxx119money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200005b0: _ZGVNSt7__cxx1110moneypunctIwLb1EE2idE
  0x200005b4: _ZGVNSt7__cxx1110moneypunctIwLb0EE2idE
  0x200005b8: _ZGVNSt7__cxx117collateIcE2idE
  0x200005bc: _ZGVNSt7__cxx118messagesIcE2idE
  0x200005c0: _ZGVNSt7__cxx118time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200005c4: _ZGVNSt7__cxx118numpunctIcE2idE
  0x200005c8: _ZGVNSt7__cxx119money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200005cc: _ZGVNSt7__cxx119money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200005d0: _ZGVNSt7__cxx1110moneypunctIcLb1EE2idE
  0x200005d4: _ZGVNSt7__cxx1110moneypunctIcLb0EE2idE
  0x200005d8: uwTick
  0x200005dc: errno
  0x200005e0: _end
  0x20005000: _estack
  0xf108f85f: BootRAM
