interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: SAM3-RIOT-PWM.bin
    permissions: rwx
    size: 0x1205c
symbols:
  0x0: _sbackup_data
  0x80000: cortex_vector_base
  0x80040: vector_cpu
  0x800f5: isr_trng
  0x800f9: _init
  0x800fb: _fini
  0x800fd: _sbrk_r
  0x80139: _read_r
  0x80141: _write_r
  0x80149: _close_r
  0x80153: _lseek_r
  0x8015d: _fstat_r
  0x80167: _isatty_r
  0x80175: sched_run
  0x801d9: sched_set_status
  0x80259: sched_switch
  0x80289: sched_task_exit
  0x802c5: thread_stack_init
  0x8032d: cpu_switch_context_exit
  0x80332: unreachable329
  0x80335: thread_yield_higher
  0x80345: isr_pendsv
  0x80361: isr_svc
  0x80365: context_restore
  0x8037d: hard_fault_default
  0x80390: fix_msp
  0x80396: test_sp
  0x803a4: use_psp
  0x803a8: out
  0x803c1: nmi_default
  0x803d1: mem_manage_default
  0x803e1: bus_fault_default
  0x803f1: usage_fault_default
  0x80401: debug_mon_default
  0x80411: dummy_handler_default
  0x80421: pre_startup
  0x80423: post_startup
  0x80425: reset_handler_default
  0x80491: hard_fault_handler
  0x80619: irq_disable
  0x80621: irq_enable
  0x80629: irq_restore
  0x8062f: irq_is_in
  0x80637: stdio_init
  0x80645: stdio_read
  0x8064b: stdio_write
  0x8065d: pm_off
  0x80665: board_init
  0x8067d: panic_arch
  0x80681: core_panic
  0x806c5: main_trampoline
  0x806dd: idle_thread
  0x806e5: kernel_init
  0x8073d: thread_create
  0x80835: pm_set_lowest
  0x80839: cpu_init
  0x808b9: isr_handler
  0x808f5: uart_write
  0x80915: uart_poweron
  0x80935: uart_init
  0x809e1: isr_uart
  0x809e7: isr_usart0
  0x809ed: isr_usart1
  0x809f3: isr_usart3
  0x809f9: gpio_init
  0x80a69: gpio_init_mux
  0x80a9d: periph_init
  0x80aa3: main
  0x80acb: auto_init
  0x80acd: cortexm_init
  0x80b0d: pwm_init
  0x80be1: pwm_set
  0x80c21: pwm_poweron
  0x80c51: pwm_poweroff
  0x80c79: spi_init_pins
  0x80cc5: spi_init
  0x80ce5: __libc_init_array
  0x80d2d: _malloc_r
  0x80de1: iprintf
  0x80e11: _puts_r
  0x80eed: puts
  0x80efd: __swbuf_r
  0x80fa1: __swsetup_r
  0x8107d: __sflush_r
  0x81189: _fflush_r
  0x81201: std
  0x81249: _cleanup_r
  0x81255: __sfmoreglue
  0x81281: __sfp_lock_acquire
  0x8128d: __sfp_lock_release
  0x81299: __sinit_lock_acquire
  0x812a5: __sinit_lock_release
  0x812b1: __sinit
  0x81321: __sfp
  0x813ad: _fwalk_reent
  0x813eb: __retarget_lock_init_recursive
  0x813ed: __retarget_lock_acquire_recursive
  0x813ef: __retarget_lock_release_recursive
  0x813f1: __swhatbuf_r
  0x81439: __smakebuf_r
  0x814b9: memset
  0x814c9: __malloc_lock
  0x814d5: __malloc_unlock
  0x814e1: _free_r
  0x81579: __sfputc_r
  0x815a3: __sfputs_r
  0x815c9: _vfprintf_r
  0x81829: _printf_common
  0x81909: _printf_i
  0x81b55: __sread
  0x81b77: __swrite
  0x81baf: __sseek
  0x81bd3: __sclose
  0x81bdb: memchr
  0x81e7d: assert_crash_message
  0x81ed8: uart_config
  0x81f18: pwm_chan
  0x81f38: spi_config
  0x81f50: _global_impure_ptr
  0x81f54: __sf_fake_stderr
  0x81f74: __sf_fake_stdin
  0x81f94: __sf_fake_stdout
  0x81fe8: __preinit_array_start
  0x8205c: _sbackup_data_load
  0x20070000: isr_stack
  0x20070200: _estack
  0x20070204: idle_name
  0x20070208: main_name
  0x2007020c: _impure_ptr
  0x20070210: impure_data
  0x20070270: _tcb_name_offset
  0x20070271: max_threads
  0x20070274: _erelocate
  0x20070278: sched_active_pid
  0x2007027c: sched_active_thread
  0x20070280: sched_context_switch_request
  0x20070284: sched_num_threads
  0x20070288: sched_runqueues
  0x200702c8: sched_threads
  0x2007034c: crashed
  0x20070350: idle_stack
  0x20070450: main_stack
  0x20070a50: ctx
  0x20070a70: pwm_chan_mask
  0x20070a72: pwm_period
  0x20070a74: locks
  0x20070a78: __malloc_free_list
  0x20070a7c: __malloc_sbrk_start
  0x20070a80: __lock___atexit_recursive_mutex
  0x20070a81: __lock___arc4random_mutex
  0x20070a82: __lock___env_recursive_mutex
  0x20070a83: __lock___sinit_recursive_mutex
  0x20070a84: __lock___malloc_recursive_mutex
  0x20070a85: __lock___at_quick_exit_mutex
  0x20070a86: __lock___dd_hash_mutex
  0x20070a87: __lock___tz_mutex
  0x20070a88: __lock___sfp_recursive_mutex
  0x20070a8c: __noinit_end
  0x20088000: _eheap
