interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: ARDUINO-SAM3-SPI.bin
    permissions: rwx
    size: 0x152d8
symbols:
  0x0: __register_frame_info
  0x80000: exception_table
  0x800f5: __do_global_dtors_aux
  0x80119: frame_dummy
  0x80149: _ZN8SPIClass8transferEh15SPITransferMode
  0x8015d: _Z12readRegisterhi
  0x801a9: _Z13writeRegisterhh
  0x801e5: setup
  0x8021d: loop
  0x80251: _ZL10SPI_0_Initv
  0x80299: _ZN8SPIClass4initEv
  0x802cf: _ZN8SPIClass11setDataModeEhh
  0x80303: _ZN8SPIClass15setClockDividerEhh
  0x80331: _ZN8SPIClass5beginEv
  0x80353: _ZN8SPIClass8transferEhh15SPITransferMode
  0x803b1: _GLOBAL__sub_I__ZN8SPIClassC2EP3SpimPFvvE
  0x803d5: _Z11serialEventv
  0x803d9: UART_Handler
  0x803e5: _Z12serialEvent1v
  0x803e7: _Z12serialEvent2v
  0x803e9: _Z12serialEvent3v
  0x803ed: USART0_Handler
  0x803f9: USART1_Handler
  0x80405: USART3_Handler
  0x80411: init
  0x80539: _GLOBAL__sub_I_g_APinDescription
  0x8060d: _Z14serialEventRunv
  0x80651: PIO_PullUp
  0x8065b: PIO_Get
  0x8066f: PIO_SetPeripheral
  0x80695: PIO_SetInput
  0x806bb: PIO_SetOutput
  0x806e1: PIO_Configure
  0x80745: PIO_GetOutputDataStatus
  0x80759: pmc_enable_periph_clk
  0x8079d: pmc_disable_periph_clk
  0x807dd: SPI_Enable
  0x807e5: SPI_Configure
  0x80805: SPI_ConfigureNPCS
  0x8080d: SystemInit
  0x80895: Reset_Handler
  0x8090d: adc_init
  0x809a5: adc_configure_trigger
  0x809b3: adc_configure_timing
  0x809cd: adc_disable_channel
  0x809d7: adc_disable_all_channel
  0x809df: adc_disable_interrupt
  0x809e5: UOTGHS_Handler
  0x809f5: PIOA_Handler
  0x80a2d: PIOB_Handler
  0x80a65: PIOC_Handler
  0x80a9d: PIOD_Handler
  0x80ad5: SPI0_Handler
  0x80ad7: SVC_Handler
  0x80adb: PendSV_Handler
  0x80adf: SysTick_Handler
  0x80af5: sysTickHook
  0x80af9: svcHook
  0x80afd: _sbrk
  0x80b19: link
  0x80b1f: _close
  0x80b25: _fstat
  0x80b2f: _isatty
  0x80b33: _lseek
  0x80b37: _read
  0x80b3d: _write
  0x80b61: _exit
  0x80b71: _kill
  0x80b73: _getpid
  0x80b79: analogOutputInit
  0x80b7d: pinMode
  0x80c85: digitalWrite
  0x80cf5: digitalRead
  0x80d39: tickReset
  0x80d59: _ZN10RingBufferC2Ev
  0x80d73: _ZN10RingBuffer10store_charEh
  0x80d91: _ZN9UARTClasscvbEv
  0x80d95: _ZN9UARTClass9availableEv
  0x80da7: _ZN9UARTClass4peekEv
  0x80dc3: _ZN9UARTClass4readEv
  0x80ded: _ZN9UARTClass5flushEv
  0x80e05: _ZN9UARTClass5writeEh
  0x80e59: _ZN9UARTClass3endEv
  0x80e95: _ZN9UARTClassC2EP4Uart4IRQnmP10RingBufferS4_
  0x80eb9: _ZN9UARTClass4initEmm
  0x80f29: _ZN9UARTClass5beginEm
  0x80f31: _ZN9UARTClass10IrqHandlerEv
  0x80f7b: _ZN10USARTClass5beginEm
  0x80f85: _ZN10USARTClassC2EP5Usart4IRQnmP10RingBufferS4_
  0x80fa9: initVariant
  0x80fad: main
  0x80fd9: _watchdogDefaultSetup
  0x80fe5: delay
  0x80fe7: _ZN5Print5writeEPKhj
  0x81009: TimeTick_Increment
  0x81019: WDT_Disable
  0x81021: __libc_init_array
  0x81071: iprintf
  0x81099: memset
  0x8112d: strlen
  0x8118d: kill
  0x8119d: __sprint_r.part.0
  0x81215: _vfiprintf_r
  0x81e69: __sbprintf
  0x81ee5: __swsetup_r
  0x81fa9: register_fini
  0x81fbd: atexit
  0x81fc9: __sflush_r
  0x82111: _fflush_r
  0x8213d: _cleanup_r
  0x82149: __sinit
  0x8223d: __sfp_lock_acquire
  0x82241: __sfp_lock_release
  0x82245: __libc_fini_array
  0x82275: _fputwc_r
  0x82335: _malloc_trim_r
  0x823d1: _free_r
  0x82569: __sfvwrite_r
  0x8287d: _fwalk
  0x828c5: __locale_charset
  0x828cd: __locale_mb_cur_max
  0x828d9: __smakebuf_r
  0x829b9: _malloc_r
  0x82ef1: memchr
  0x82f85: memcpy
  0x83071: memmove
  0x8313d: __malloc_lock
  0x83141: __malloc_unlock
  0x83145: _realloc_r
  0x83505: _sbrk_r
  0x83529: _kill_r
  0x83551: __sread
  0x83575: __swrite
  0x835ad: __sseek
  0x835cd: __sclose
  0x835d5: __swbuf_r
  0x8367d: _wcrtomb_r
  0x836cd: __ascii_wctomb
  0x836e9: _write_r
  0x83711: __register_exitproc
  0x837b9: _close_r
  0x837dd: _fclose_r
  0x8385d: fclose
  0x8386d: _fstat_r
  0x83895: _isatty_r
  0x838b9: _lseek_r
  0x838e1: _read_r
  0x83909: __aeabi_uldivmod
  0x83935: __gnu_ldivmod_helper
  0x83965: __gnu_uldivmod_helper
  0x83995: __aeabi_idiv0
  0x83999: __divdi3
  0x83c39: __udivdi3
  0x83ec8: g_APinDescription
  0x84950: _ZTV9UARTClass
  0x84980: _ZTV10USARTClass
  0x849b4: _global_impure_ptr
  0x849b8: blanks.6717
  0x849f8: zeroes.6718
  0x84a09: _init
  0x84a14: __preinit_array_start
  0x84a18: __frame_dummy_init_array_entry
  0x84a24: __init_array_end
  0x84a25: _fini
  0x84a30: __fini_array_start
  0x84a34: _efixed
  0x84a3c: _etext
  0x20070000: _srelocate
  0x20070001: banzai
  0x2007002c: SystemCoreClock
  0x20070030: _ZL5ticks
  0x20070038: impure_data
  0x20070460: _impure_ptr
  0x20070464: lc_ctype_charset
  0x20070484: __mb_cur_max
  0x20070488: __malloc_av_
  0x20070890: __malloc_trim_threshold
  0x20070894: __malloc_sbrk_base
  0x20070898: __wctomb
  0x2007089c: _erelocate
  0x200708a0: object.7862
  0x200708b8: SPI
  0x200708fc: tx_buffer2
  0x20070984: tx_buffer1
  0x20070a0c: Serial
  0x20070a30: rx_buffer1
  0x20070ab8: Serial1
  0x20070ae0: Serial2
  0x20070b08: Serial3
  0x20070b30: tx_buffer3
  0x20070bb8: tx_buffer4
  0x20070c40: g_pinStatus
  0x20070c90: rx_buffer2
  0x20070d18: rx_buffer3
  0x20070da0: rx_buffer4
  0x20070e28: gpf_isr
  0x20070e2c: callbacksPioA
  0x20070eac: callbacksPioB
  0x20070f2c: callbacksPioC
  0x20070fac: callbacksPioD
  0x2007102c: heap.6420
  0x20071030: _dwTickCount
  0x20071034: __malloc_max_total_mem
  0x20071038: __malloc_max_sbrked_mem
  0x2007103c: __malloc_top_pad
  0x20071040: __malloc_current_mallinfo
  0x20071068: errno
  0x2007106c: _end
  0x20088000: _estack
