interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: ARDUINO-SAM3-DAC.bin
    permissions: rwx
    size: 0x15b5c
symbols:
  0x0: __register_frame_info
  0x80000: exception_table
  0x800f5: __do_global_dtors_aux
  0x80119: frame_dummy
  0x80149: setup
  0x80159: loop
  0x80189: _Z11serialEventv
  0x8018d: UART_Handler
  0x80199: _Z12serialEvent1v
  0x8019b: _Z12serialEvent2v
  0x8019d: _Z12serialEvent3v
  0x801a1: USART0_Handler
  0x801ad: USART1_Handler
  0x801b9: USART3_Handler
  0x801c5: init
  0x802ed: _GLOBAL__sub_I_g_APinDescription
  0x803c1: _Z14serialEventRunv
  0x80405: PIO_PullUp
  0x8040f: PIO_SetPeripheral
  0x80435: PIO_SetInput
  0x8045b: PIO_SetOutput
  0x80481: PIO_Configure
  0x804e5: PIO_GetOutputDataStatus
  0x804f9: pmc_enable_periph_clk
  0x8053d: pmc_disable_periph_clk
  0x8057d: SystemInit
  0x80605: Reset_Handler
  0x8067d: adc_init
  0x80715: adc_configure_trigger
  0x80723: adc_configure_timing
  0x8073d: adc_start
  0x80743: adc_enable_channel
  0x8074d: adc_disable_channel
  0x80757: adc_disable_all_channel
  0x8075f: adc_get_channel_status
  0x80769: adc_get_latest_value
  0x8076d: adc_disable_interrupt
  0x80771: adc_get_status
  0x80775: UOTGHS_Handler
  0x80785: PIOA_Handler
  0x807bd: PIOB_Handler
  0x807f5: PIOC_Handler
  0x8082d: PIOD_Handler
  0x80865: SPI0_Handler
  0x80867: SVC_Handler
  0x8086b: PendSV_Handler
  0x8086f: SysTick_Handler
  0x80885: sysTickHook
  0x80889: svcHook
  0x8088d: _sbrk
  0x808a9: link
  0x808af: _close
  0x808b5: _fstat
  0x808bf: _isatty
  0x808c3: _lseek
  0x808c7: _read
  0x808cd: _write
  0x808f1: _exit
  0x80901: _kill
  0x80903: _getpid
  0x80909: mapResolution
  0x8091d: analogRead
  0x809b9: analogOutputInit
  0x809bd: analogWrite
  0x80c7d: pinMode
  0x80d85: digitalWrite
  0x80df5: tickReset
  0x80e15: _ZN10RingBufferC2Ev
  0x80e2f: _ZN10RingBuffer10store_charEh
  0x80e4d: _ZN9UARTClasscvbEv
  0x80e51: _ZN9UARTClass9availableEv
  0x80e63: _ZN9UARTClass4peekEv
  0x80e7f: _ZN9UARTClass4readEv
  0x80ea9: _ZN9UARTClass5flushEv
  0x80ec1: _ZN9UARTClass5writeEh
  0x80f15: _ZN9UARTClass3endEv
  0x80f51: _ZN9UARTClassC2EP4Uart4IRQnmP10RingBufferS4_
  0x80f75: _ZN9UARTClass4initEmm
  0x80fe5: _ZN9UARTClass5beginEm
  0x80fed: _ZN9UARTClass10IrqHandlerEv
  0x81037: _ZN10USARTClass5beginEm
  0x81041: _ZN10USARTClassC2EP5Usart4IRQnmP10RingBufferS4_
  0x81065: initVariant
  0x81069: main
  0x81095: _watchdogDefaultSetup
  0x810a1: delay
  0x810a3: _ZN5Print5writeEPKhj
  0x810c5: FindClockConfiguration
  0x81141: PWMC_ConfigureChannel
  0x811a1: PWMC_ConfigureClocks
  0x811f5: PWMC_SetPeriod
  0x81211: PWMC_SetDutyCycle
  0x81255: PWMC_EnableChannel
  0x81261: TC_Configure
  0x81299: TC_Start
  0x812c5: TC_SetRA
  0x812cd: TC_SetRB
  0x812d5: TC_SetRC
  0x812dd: TimeTick_Increment
  0x812ed: WDT_Disable
  0x812f5: dacc_reset
  0x812fb: dacc_set_transfer_mode
  0x8130f: dacc_get_interrupt_status
  0x81313: dacc_write_conversion_data
  0x81317: dacc_set_channel_selection
  0x8132f: dacc_set_power_save
  0x81353: dacc_set_timing
  0x8137f: dacc_enable_channel
  0x81391: dacc_get_channel_status
  0x81395: dacc_set_analog_control
  0x8139d: __assert_func
  0x813d9: fiprintf
  0x81401: __libc_init_array
  0x81451: iprintf
  0x81479: memset
  0x8150d: strlen
  0x8156d: kill
  0x8157d: __sprint_r.part.0
  0x815f5: _vfiprintf_r
  0x82249: __sbprintf
  0x822c5: __swsetup_r
  0x82389: register_fini
  0x8239d: abort
  0x823ad: atexit
  0x823b9: __sflush_r
  0x82501: _fflush_r
  0x8252d: _cleanup_r
  0x82539: __sinit
  0x8262d: __sfp_lock_acquire
  0x82631: __sfp_lock_release
  0x82635: __libc_fini_array
  0x82665: _fputwc_r
  0x82725: _malloc_trim_r
  0x827c1: _free_r
  0x82959: __sfvwrite_r
  0x82c6d: _fwalk
  0x82cb5: __locale_charset
  0x82cbd: __locale_mb_cur_max
  0x82cc9: __smakebuf_r
  0x82da9: _malloc_r
  0x832e1: memchr
  0x83375: memcpy
  0x83461: memmove
  0x8352d: __malloc_lock
  0x83531: __malloc_unlock
  0x83535: _realloc_r
  0x838f5: _sbrk_r
  0x83919: _raise_r
  0x83971: raise
  0x83981: _kill_r
  0x839a9: _getpid_r
  0x839ad: __sread
  0x839d1: __swrite
  0x83a09: __sseek
  0x83a29: __sclose
  0x83a31: __swbuf_r
  0x83ad9: _wcrtomb_r
  0x83b29: __ascii_wctomb
  0x83b45: _write_r
  0x83b6d: __register_exitproc
  0x83c15: _close_r
  0x83c39: _fclose_r
  0x83cb9: fclose
  0x83cc9: _fstat_r
  0x83cf1: _isatty_r
  0x83d15: _lseek_r
  0x83d3d: _read_r
  0x83d65: __aeabi_uldivmod
  0x83d91: __gnu_ldivmod_helper
  0x83dc1: __gnu_uldivmod_helper
  0x83df1: __aeabi_idiv0
  0x83df5: __divdi3
  0x84095: __udivdi3
  0x84324: g_APinDescription
  0x84dac: channelToId.9433
  0x84df4: channelToTC.9432
  0x84e3c: channelToChNo.9430
  0x84e84: channelToAB.9431
  0x84ed0: _ZTV9UARTClass
  0x84f00: _ZTV10USARTClass
  0x84f5c: __func__.6830
  0x84f71: __func__.6841
  0x8514f: __func__.6804
  0x85165: __func__.6793
  0x8517c: __func__.6792
  0x851dd: __func__.6798
  0x8522c: _global_impure_ptr
  0x85230: blanks.6717
  0x85270: zeroes.6718
  0x85281: _init
  0x8528c: __preinit_array_start
  0x85290: __frame_dummy_init_array_entry
  0x85298: __init_array_end
  0x85299: _fini
  0x852a4: __fini_array_start
  0x852a8: _efixed
  0x852b0: _etext
  0x20070000: _srelocate
  0x20070001: banzai
  0x2007002c: ledPin
  0x20070030: analogPin
  0x20070034: SystemCoreClock
  0x20070038: _writeResolution
  0x2007003c: latestSelectedChannel.9384
  0x20070040: _readResolution
  0x20070044: _ZL5ticks
  0x20070048: impure_data
  0x20070470: _impure_ptr
  0x20070474: lc_ctype_charset
  0x20070494: __mb_cur_max
  0x20070498: __malloc_av_
  0x200708a0: __malloc_trim_threshold
  0x200708a4: __malloc_sbrk_base
  0x200708a8: __wctomb
  0x200708ac: _erelocate
  0x200708b0: object.7862
  0x200708c8: val
  0x200708cc: tx_buffer2
  0x20070954: tx_buffer1
  0x200709dc: Serial
  0x20070a00: rx_buffer1
  0x20070a88: Serial1
  0x20070ab0: Serial2
  0x20070ad8: Serial3
  0x20070b00: tx_buffer3
  0x20070b88: tx_buffer4
  0x20070c10: g_pinStatus
  0x20070c60: rx_buffer2
  0x20070ce8: rx_buffer3
  0x20070d70: rx_buffer4
  0x20070df8: gpf_isr
  0x20070dfc: callbacksPioA
  0x20070e7c: callbacksPioB
  0x20070efc: callbacksPioC
  0x20070f7c: callbacksPioD
  0x20070ffc: heap.6420
  0x20071000: PWMEnabled
  0x20071001: TCChanEnabled
  0x2007100c: _dwTickCount
  0x20071010: __malloc_max_total_mem
  0x20071014: __malloc_max_sbrked_mem
  0x20071018: __malloc_top_pad
  0x2007101c: __malloc_current_mallinfo
  0x20071044: errno
  0x20071048: _end
  0x20088000: _estack
