interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: ARDUINO-F103-GPIO.bin
    permissions: rwx
    size: 0x13680
symbols:
  0x0: reent.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x800010d: __do_global_dtors_aux
  0x8000131: frame_dummy
  0x8000179: strlen
  0x8000189: setup
  0x800019d: loop
  0x80001c5: SystemClock_Config
  0x8000265: Reset_Handler
  0x8000268: CopyDataInit
  0x8000270: LoopCopyDataInit
  0x800027e: FillZerobss
  0x8000284: LoopFillZerobss
  0x80002ac: Default_Handler
  0x80002ad: USB_HP_CAN1_TX_IRQHandler
  0x80002af: init
  0x80002b7: HAL_MspInit
  0x80002b9: HAL_InitTick
  0x8000305: HAL_Init
  0x8000329: HAL_IncTick
  0x8000341: HAL_GetTick
  0x800034d: HAL_NVIC_SetPriorityGrouping
  0x8000371: HAL_NVIC_SetPriority
  0x80003d5: HAL_NVIC_EnableIRQ
  0x80003f1: HAL_SYSTICK_Config
  0x800041d: HAL_NVIC_ClearPendingIRQ
  0x800043d: HAL_SYSTICK_CLKSourceConfig
  0x800045d: HAL_SYSTICK_Callback
  0x800045f: HAL_SYSTICK_IRQHandler
  0x8000469: HAL_DMA_Abort_IT
  0x8000501: HAL_GPIO_Init
  0x80006ed: HAL_GPIO_ReadPin
  0x80006fb: HAL_GPIO_WritePin
  0x8000709: HAL_GPIO_EXTI_IRQHandler
  0x8000725: I2C_Master_SB
  0x80007af: I2C_Master_ADD10
  0x80007bb: I2C_Master_ADDR
  0x8000995: I2C_SlaveTransmit_BTF
  0x80009b5: I2C_SlaveReceive_BTF
  0x80009d5: HAL_I2C_Slave_Sequential_Transmit_IT
  0x8000a61: HAL_I2C_Slave_Sequential_Receive_IT
  0x8000aed: HAL_I2C_EnableListen_IT
  0x8000b2b: HAL_I2C_MasterTxCpltCallback
  0x8000b2d: HAL_I2C_MasterRxCpltCallback
  0x8000b2f: HAL_I2C_SlaveTxCpltCallback
  0x8000b31: I2C_SlaveTransmit_TXE
  0x8000b81: HAL_I2C_SlaveRxCpltCallback
  0x8000b83: I2C_SlaveReceive_RXNE
  0x8000bcf: I2C_Slave_ADDR
  0x8000bf9: I2C_Slave_AF
  0x8000c8d: HAL_I2C_MemTxCpltCallback
  0x8000c8f: I2C_MasterTransmit_TXE
  0x8000dd9: I2C_MasterTransmit_BTF
  0x8000e77: HAL_I2C_MemRxCpltCallback
  0x8000e79: I2C_MasterReceive_RXNE
  0x8000f49: I2C_MasterReceive_BTF
  0x8001047: HAL_I2C_AbortCpltCallback
  0x8001049: I2C_ITError
  0x8001191: I2C_Slave_STOPF
  0x8001295: HAL_I2C_EV_IRQHandler
  0x80013fd: HAL_I2C_ER_IRQHandler
  0x80014d9: I2C_DMAAbort
  0x8001539: RCC_Delay
  0x8001565: HAL_RCC_OscConfig
  0x8001945: HAL_RCC_GetSysClockFreq
  0x80019b1: HAL_RCC_ClockConfig
  0x8001b21: HAL_RCC_GetHCLKFreq
  0x8001b2d: HAL_RCCEx_PeriphCLKConfig
  0x8001c41: HAL_RTC_AlarmIRQHandler
  0x8001c79: HAL_TIM_PWM_DeInit
  0x8001cb3: HAL_TIM_IC_CaptureCallback
  0x8001cb5: HAL_TIM_PWM_PulseFinishedCallback
  0x8001cb7: HAL_TIM_TriggerCallback
  0x8001cb9: HAL_TIM_IRQHandler
  0x8001e33: TIM_CCxChannelCmd
  0x8001e51: HAL_TIM_PWM_Stop
  0x8001eb1: TIM_CCxNChannelCmd
  0x8001ecd: HAL_TIMEx_PWMN_Stop
  0x8001f19: HAL_TIMEx_CommutationCallback
  0x8001f1b: HAL_TIMEx_BreakCallback
  0x8001f1d: UART_EndRxTransfer
  0x8001f39: UART_Transmit_IT
  0x8001fa3: HAL_UART_Transmit_IT
  0x8001feb: UART_EndTransmit_IT
  0x8002005: UART_Receive_IT
  0x80020a5: HAL_UART_IRQHandler
  0x80021c5: UART_DMAAbortOnError
  0x80021d5: HAL_UART_GetState
  0x80021e1: is_pin_configured
  0x80021f7: set_pin_configured
  0x8002215: reset_pin_configured
  0x8002235: get_GPIO_Port
  0x8002271: set_GPIO_Port_Clock
  0x8002319: get_pwm_channel
  0x8002345: HAL_TIM_PWM_MspDeInit
  0x800234d: pwm_stop
  0x80023a5: noOsSystickHandler
  0x80023a7: SysTick_Handler
  0x80023b9: digital_io_init
  0x8002439: digital_io_write
  0x8002451: digital_io_read
  0x800245b: hw_config_init
  0x8002467: pinmap_find_peripheral
  0x8002481: pinmap_peripheral
  0x8002493: pinmap_find_pin
  0x80024ab: pinmap_pin
  0x80024bb: pinmap_find_function
  0x80024d7: pinmap_function
  0x80024eb: pin_in_pinmap
  0x8002511: HAL_RTC_AlarmAEventCallback
  0x8002529: RTC_Alarm_IRQHandler
  0x8002539: _Error_Handler
  0x800253d: SystemInit
  0x8002589: timer_disable_clock
  0x80025ed: get_timer_obj
  0x80025f1: HAL_TIM_OC_DelayElapsedCallback
  0x800260b: HAL_TIM_PeriodElapsedCallback
  0x8002619: TIM1_UP_IRQHandler
  0x800262d: TIM2_IRQHandler
  0x8002641: TIM3_IRQHandler
  0x8002655: TIM4_IRQHandler
  0x8002669: get_i2c_obj
  0x800266d: HAL_I2C_AddrCallback
  0x80026bd: HAL_I2C_ListenCpltCallback
  0x80026ed: HAL_I2C_ErrorCallback
  0x8002705: I2C1_EV_IRQHandler
  0x8002715: I2C1_ER_IRQHandler
  0x8002725: I2C2_EV_IRQHandler
  0x8002735: I2C2_ER_IRQHandler
  0x8002745: serial_tx_active
  0x8002769: uart_attach_tx_callback
  0x80027bd: uart_index
  0x80027e1: HAL_UART_RxCpltCallback
  0x8002805: HAL_UART_TxCpltCallback
  0x8002851: HAL_UART_ErrorCallback
  0x8002891: USART1_IRQHandler
  0x80028a9: USART2_IRQHandler
  0x80028c1: USART3_IRQHandler
  0x80028d9: _exit
  0x80028dd: _kill
  0x80028ed: _getpid
  0x80028f1: pinMode
  0x8002985: digitalWrite
  0x80029cd: digitalRead
  0x8002a1d: _ZN14HardwareSerial16_tx_complete_irqEP8serial_s
  0x8002a51: _ZN14HardwareSerial9availableEv
  0x8002a65: _ZN14HardwareSerial4peekEv
  0x8002a81: _ZN14HardwareSerial4readEv
  0x8002aa9: _ZN14HardwareSerial5flushEv
  0x8002abd: _ZN14HardwareSerial5writeEh
  0x8002b0d: _Z14serialEventRunv
  0x8002b39: _ZN14HardwareSerial4initEv
  0x8002b5d: _ZN14HardwareSerial5setRxEm
  0x8002b75: _ZN14HardwareSerial5setTxEm
  0x8002b8d: _ZN14HardwareSerialC1EPv
  0x8002be9: _Z41__static_initialization_and_destruction_0ii
  0x8002c0d: _GLOBAL__sub_I_Serial2
  0x8002c1b: _ZNK9IPAddress7printToER5Print
  0x8002c55: _ZN9IPAddressC1Ehhhh
  0x8002c71: _Z41__static_initialization_and_destruction_0ii
  0x8002c9d: _GLOBAL__sub_I__ZN9IPAddressC2Ev
  0x8002cab: _ZN5Print5writeEPKhj
  0x8002ccf: _ZN5Print5printEc
  0x8002cd9: _ZN5Print11printNumberEmh
  0x8002d33: _ZN5Print5printEmi
  0x8002d49: _ZN5Print5printEhi
  0x8002d51: _Z11initVariantv
  0x8002d53: _Z7premainv
  0x8002d61: main
  0x8002d81: _ZL10get_pin_idt
  0x8002d95: __tcf_0
  0x8002dbd: _Z41__static_initialization_and_destruction_0ii
  0x8002e69: EXTI0_IRQHandler
  0x8002e73: EXTI1_IRQHandler
  0x8002e7d: EXTI2_IRQHandler
  0x8002e87: EXTI3_IRQHandler
  0x8002e91: EXTI4_IRQHandler
  0x8002e9b: EXTI9_5_IRQHandler
  0x8002eb1: EXTI15_10_IRQHandler
  0x8002ec9: _ZNKSt8functionIFvvEEclEv
  0x8002ed9: HAL_GPIO_EXTI_Callback
  0x8002ef9: _GLOBAL__sub_I__Z22stm32_interrupt_enableP12GPIO_TypeDeftSt8functionIFvvEEm
  0x8002f07: __aeabi_atexit
  0x8002f11: __cxa_atexit
  0x8002f2d: __libc_init_array
  0x8002f75: abort
  0x8002f83: _raise_r
  0x8002fd5: raise
  0x8002fe5: _kill_r
  0x8003009: _getpid_r
  0x800300d: _ZSt25__throw_bad_function_callv
  0x8003015: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKSsj
  0x80030d9: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKSsj
  0x800319d: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x8003221: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x80032a4: __EH_FRAME_BEGIN__
  0x80032a5: _init
  0x80032b1: _fini
  0x80032bc: _etext
  0x80032d0: PinMap_PWM
  0x8003420: PinMap_UART_RX
  0x8003468: PinMap_UART_TX
  0x800350c: digitalPin
  0x8003548: AHBPrescTable
  0x8003558: _ZTV14HardwareSerial
  0x8003578: _ZTV9IPAddress
  0x8003584: __sf_fake_stderr
  0x80035a4: __sf_fake_stdin
  0x80035c4: __sf_fake_stdout
  0x80035e4: __exidx_end
  0x80035e8: __frame_dummy_init_array_entry
  0x8003608: __init_array_end
  0x800360c: _sidata
  0x20000000: __dso_handle
  0x20000004: uwTickFreq
  0x20000008: uwTickPrio
  0x2000000c: SystemCoreClock
  0x20000010: _impure_ptr
  0x20000014: impure_data
  0x20000074: _edata
  0x20000078: object.8672
  0x20000090: buttonState
  0x20000094: RTCUserCallback
  0x20000098: RtcHandle
  0x200000ac: callbackUserData
  0x200000b0: timer_handles
  0x20000108: i2c_handles
  0x20000110: rx_callback
  0x20000124: rx_callback_obj
  0x20000138: tx_callback
  0x2000014c: tx_callback_obj
  0x20000160: uart_handlers
  0x20000174: g_anOutputPinConfigured
  0x20000188: g_digPinConfigured
  0x2000019c: Serial2
  0x200002e0: _ZL11INADDR_NONE
  0x200002e8: _ZL13gpio_irq_conf
  0x20000428: _ZGVNSt7collateIcE2idE
  0x2000042c: _ZGVNSt8messagesIcE2idE
  0x20000430: _ZGVNSt8time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000434: _ZGVNSt8time_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000438: _ZGVNSt11__timepunctIcE2idE
  0x2000043c: _ZGVNSt7num_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000440: _ZGVNSt7num_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000444: _ZGVNSt8numpunctIcE2idE
  0x20000448: _ZGVNSt9money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x2000044c: _ZGVNSt9money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000450: _ZGVNSt10moneypunctIcLb1EE2idE
  0x20000454: _ZGVNSt10moneypunctIcLb0EE2idE
  0x20000458: _ZGVNSt7collateIwE2idE
  0x2000045c: _ZGVNSt8messagesIwE2idE
  0x20000460: _ZGVNSt8time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000464: _ZGVNSt8time_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000468: _ZGVNSt11__timepunctIwE2idE
  0x2000046c: _ZGVNSt7num_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000470: _ZGVNSt7num_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000474: _ZGVNSt8numpunctIwE2idE
  0x20000478: _ZGVNSt9money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x2000047c: _ZGVNSt9money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000480: _ZGVNSt10moneypunctIwLb1EE2idE
  0x20000484: _ZGVNSt10moneypunctIwLb0EE2idE
  0x20000488: _ZGVNSt7__cxx117collateIwE2idE
  0x2000048c: _ZGVNSt7__cxx118messagesIwE2idE
  0x20000490: _ZGVNSt7__cxx118time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000494: _ZGVNSt7__cxx118numpunctIwE2idE
  0x20000498: _ZGVNSt7__cxx119money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x2000049c: _ZGVNSt7__cxx119money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004a0: _ZGVNSt7__cxx1110moneypunctIwLb1EE2idE
  0x200004a4: _ZGVNSt7__cxx1110moneypunctIwLb0EE2idE
  0x200004a8: _ZGVNSt7__cxx117collateIcE2idE
  0x200004ac: _ZGVNSt7__cxx118messagesIcE2idE
  0x200004b0: _ZGVNSt7__cxx118time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200004b4: _ZGVNSt7__cxx118numpunctIcE2idE
  0x200004b8: _ZGVNSt7__cxx119money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200004bc: _ZGVNSt7__cxx119money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200004c0: _ZGVNSt7__cxx1110moneypunctIcLb1EE2idE
  0x200004c4: _ZGVNSt7__cxx1110moneypunctIcLb0EE2idE
  0x200004c8: uwTick
  0x200004cc: errno
  0x200004d0: _end
  0x20005000: _estack
  0xf108f85f: BootRAM
