interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  .stack:
    base_addr: 0x1fff0000
    permissions: rw-
    size: 0xaf8
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: K64F-RIOT-USART-Read.bin
    permissions: rwx
    size: 0x12f6c
symbols:
  0x0: _sbackup_data
  0x10: _flashsec_length
  0x40: vector_cpu
  0x1d8: vector_padding
  0x400: _vectors_length
  0x410: _sfixed
  0x411: _init
  0x413: _fini
  0x415: _sbrk_r
  0x451: _read_r
  0x459: _write_r
  0x461: _close_r
  0x46b: _lseek_r
  0x475: _fstat_r
  0x47f: _isatty_r
  0x491: sched_run
  0x4f5: sched_set_status
  0x575: sched_switch
  0x5a5: sched_task_exit
  0x5e1: thread_stack_init
  0x649: cpu_switch_context_exit
  0x64e: unreachable325
  0x651: thread_yield_higher
  0x661: isr_pendsv
  0x67d: isr_svc
  0x681: context_restore
  0x699: hard_fault_default
  0x6ac: fix_msp
  0x6b2: test_sp
  0x6c0: use_psp
  0x6c4: out
  0x6dd: nmi_default
  0x6ed: mem_manage_default
  0x6fd: bus_fault_default
  0x70d: usage_fault_default
  0x71d: debug_mon_default
  0x72d: isr_systick
  0x73d: post_startup
  0x741: reset_handler_default
  0x7ad: hard_fault_handler
  0x935: irq_disable
  0x93d: irq_enable
  0x945: irq_restore
  0x94b: irq_is_in
  0x955: pre_startup
  0x969: isr_wdog_ewm
  0x96d: wdog_disable
  0x985: stdio_init
  0x99d: stdio_read
  0x9ad: stdio_write
  0x9bf: pm_off
  0x9c9: board_init
  0xa2d: panic_arch
  0xa31: core_panic
  0xa75: main_trampoline
  0xa8d: idle_thread
  0xa95: kernel_init
  0xaed: thread_add_to_list
  0xb1d: thread_create
  0xc11: pm_set_lowest
  0xc15: cpu_init
  0xc39: isrpipe_write_one
  0xc4f: isrpipe_read
  0xc75: uart_init
  0xd31: uart_write
  0xd51: isr_uart0_rx_tx
  0xd85: bit_clear8
  0xda5: kinetis_mcg_set_fll_factor
  0xdb9: kinetis_mcg_enable_osc
  0xdd9: kinetis_mcg_set_mode
  0xf59: kinetis_mcg_init
  0x105d: gpio_init_port
  0x1089: gpio_init
  0x10d5: gpio_set
  0x10ef: _pop
  0x1101: tsrb_get
  0x1127: tsrb_add_one
  0x114d: periph_init
  0x1151: main
  0x1165: auto_init
  0x1169: _mutex_lock
  0x11c9: mutex_unlock
  0x1215: cortexm_init
  0x1255: __libc_init_array
  0x129d: _malloc_r
  0x1365: _iprintf_r
  0x1395: iprintf
  0x13cd: _puts_r
  0x14a5: puts
  0x14b5: __swbuf_r
  0x1565: __swbuf
  0x1575: __swsetup_r
  0x1675: __sflush_r
  0x17a1: _fflush_r
  0x1801: fflush
  0x1825: __fp_lock
  0x1829: _cleanup_r
  0x1835: __fp_unlock
  0x1839: __sfmoreglue
  0x1869: __sfp
  0x18ed: __sinit.part.0
  0x19e1: _cleanup
  0x19f5: __sinit
  0x19fd: __sfp_lock_acquire
  0x1a01: __sfp_lock_release
  0x1a05: __sinit_lock_acquire
  0x1a09: __sinit_lock_release
  0x1a0d: __fp_lock_all
  0x1a21: __fp_unlock_all
  0x1a35: _fwalk
  0x1a81: _fwalk_reent
  0x1ad5: __swhatbuf_r
  0x1b31: __smakebuf_r
  0x1bc5: memset
  0x1c65: __malloc_lock
  0x1c69: __malloc_unlock
  0x1c6d: _free_r
  0x1d19: __sfputc_r
  0x1d51: __sfputs_r
  0x1d81: __sprint_r
  0x1d9d: _vfprintf_r
  0x2061: vfprintf
  0x2079: _printf_common
  0x21a5: _printf_i
  0x243d: __sread
  0x2461: __seofread
  0x2465: __swrite
  0x24a5: __sseek
  0x24c5: __sclose
  0x24cd: __sfvwrite_r
  0x27e1: memchr
  0x2881: memcpy
  0x29b5: memmove
  0x2a85: _realloc_r
  0x2ad1: _malloc_usable_size_r
  0x2d67: assert_crash_message
  0x2de4: uart_config
  0x2e04: mcg_mode_routing
  0x2e44: _global_impure_ptr
  0x2e48: __sf_fake_stderr
  0x2e68: __sf_fake_stdout
  0x2e88: __sf_fake_stdin
  0x2ee4: __preinit_array_start
  0x2f6c: _sbackup_data_load
  0x40000: _ram_length
  0x100000: _fw_rom_length
  0x1fff0000: isr_stack
  0x1fff0200: _estack
  0x1fff0204: stdio_uart_isrpipe
  0x1fff0218: idle_name
  0x1fff021c: main_name
  0x1fff0220: _impure_ptr
  0x1fff0224: impure_data
  0x1fff0284: _tcb_name_offset
  0x1fff0285: max_threads
  0x1fff0288: _erelocate
  0x1fff028c: sched_active_pid
  0x1fff0290: sched_active_thread
  0x1fff0294: sched_context_switch_request
  0x1fff0298: sched_num_threads
  0x1fff029c: sched_runqueues
  0x1fff02dc: sched_threads
  0x1fff0360: _rx_buf_mem
  0x1fff03a0: crashed
  0x1fff03a4: idle_stack
  0x1fff04a4: main_stack
  0x1fff0aa4: config
  0x1fff0aac: current_mode
  0x1fff0aad: buffer
  0x1fff0af0: __malloc_free_list
  0x1fff0af4: __malloc_sbrk_start
  0x1fff0af8: __noinit_end
  0x20030000: _eheap
