interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: SAM3-RIOT-USART-Read.bin
    permissions: rwx
    size: 0x128e4
symbols:
  0x0: _sbackup_data
  0x80000: cortex_vector_base
  0x80040: vector_cpu
  0x800f5: isr_trng
  0x800f9: _init
  0x800fb: _fini
  0x800fd: _sbrk_r
  0x80139: _read_r
  0x80141: _write_r
  0x80149: _close_r
  0x80153: _lseek_r
  0x8015d: _fstat_r
  0x80167: _isatty_r
  0x80175: sched_run
  0x801d9: sched_set_status
  0x80259: sched_switch
  0x80289: sched_task_exit
  0x802c5: thread_stack_init
  0x8032d: cpu_switch_context_exit
  0x80332: unreachable329
  0x80335: thread_yield_higher
  0x80345: isr_pendsv
  0x80361: isr_svc
  0x80365: context_restore
  0x8037d: hard_fault_default
  0x80390: fix_msp
  0x80396: test_sp
  0x803a4: use_psp
  0x803a8: out
  0x803c1: nmi_default
  0x803d1: mem_manage_default
  0x803e1: bus_fault_default
  0x803f1: usage_fault_default
  0x80401: debug_mon_default
  0x80411: dummy_handler_default
  0x80421: pre_startup
  0x80423: post_startup
  0x80425: reset_handler_default
  0x80491: hard_fault_handler
  0x80619: irq_disable
  0x80621: irq_enable
  0x80629: irq_restore
  0x8062f: irq_is_in
  0x80639: stdio_init
  0x80651: stdio_read
  0x80661: stdio_write
  0x80673: pm_off
  0x8067d: board_init
  0x80695: panic_arch
  0x80699: core_panic
  0x806dd: main_trampoline
  0x806f5: idle_thread
  0x806fd: kernel_init
  0x80755: thread_add_to_list
  0x80785: thread_create
  0x8087d: pm_set_lowest
  0x80881: cpu_init
  0x80901: isrpipe_write_one
  0x80917: isrpipe_read
  0x8093d: isr_handler
  0x80979: uart_write
  0x80999: uart_poweron
  0x809b9: uart_init
  0x80a65: isr_uart
  0x80a6b: isr_usart0
  0x80a71: isr_usart1
  0x80a77: isr_usart3
  0x80a7d: gpio_init
  0x80aed: gpio_init_mux
  0x80b21: _pop
  0x80b33: tsrb_get
  0x80b59: tsrb_add_one
  0x80b7f: periph_init
  0x80b81: main
  0x80b95: auto_init
  0x80b99: _mutex_lock
  0x80bf9: mutex_unlock
  0x80c45: cortexm_init
  0x80c85: __libc_init_array
  0x80ccd: _malloc_r
  0x80d95: _iprintf_r
  0x80dc5: iprintf
  0x80dfd: _puts_r
  0x80ec1: puts
  0x80ed1: __swbuf_r
  0x80f81: __swbuf
  0x80f91: __swsetup_r
  0x81091: __sflush_r
  0x811bd: _fflush_r
  0x8121d: fflush
  0x81241: __fp_lock
  0x81245: _cleanup_r
  0x81251: __fp_unlock
  0x81255: __sfmoreglue
  0x81285: __sfp
  0x81309: __sinit.part.0
  0x813fd: _cleanup
  0x81411: __sinit
  0x81419: __sfp_lock_acquire
  0x8141d: __sfp_lock_release
  0x81421: __sinit_lock_acquire
  0x81425: __sinit_lock_release
  0x81429: __fp_lock_all
  0x8143d: __fp_unlock_all
  0x81451: _fwalk
  0x81499: _fwalk_reent
  0x814e9: __swhatbuf_r
  0x81545: __smakebuf_r
  0x815d9: memset
  0x81679: __malloc_lock
  0x8167d: __malloc_unlock
  0x81681: _free_r
  0x81729: __sfputc_r
  0x81761: __sfputs_r
  0x81791: __sprint_r
  0x817ad: _vfprintf_r
  0x81a75: vfprintf
  0x81a8d: _printf_common
  0x81bb5: _printf_i
  0x81e49: __sread
  0x81e6d: __seofread
  0x81e71: __swrite
  0x81eb1: __sseek
  0x81ed1: __sclose
  0x81ed9: __sfvwrite_r
  0x821d9: memchr
  0x82265: memcpy
  0x82351: memmove
  0x8241d: _realloc_r
  0x82469: _malloc_usable_size_r
  0x826ff: assert_crash_message
  0x8277c: uart_config
  0x827bc: _global_impure_ptr
  0x827c0: __sf_fake_stderr
  0x827e0: __sf_fake_stdout
  0x82800: __sf_fake_stdin
  0x8285c: __preinit_array_start
  0x828e4: _sbackup_data_load
  0x20070000: isr_stack
  0x20070200: _estack
  0x20070204: stdio_uart_isrpipe
  0x20070218: idle_name
  0x2007021c: main_name
  0x20070220: _impure_ptr
  0x20070224: impure_data
  0x20070284: _tcb_name_offset
  0x20070285: max_threads
  0x20070288: _erelocate
  0x2007028c: sched_active_pid
  0x20070290: sched_active_thread
  0x20070294: sched_context_switch_request
  0x20070298: sched_num_threads
  0x2007029c: sched_runqueues
  0x200702dc: sched_threads
  0x20070360: _rx_buf_mem
  0x200703a0: crashed
  0x200703a4: idle_stack
  0x200704a4: main_stack
  0x20070aa4: ctx
  0x20070ac4: buffer
  0x20070b04: __malloc_free_list
  0x20070b08: __malloc_sbrk_start
  0x20070b0c: __noinit_end
  0x20088000: _eheap
