[package]
name = "agent-interface"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.75"
shlex = "1.2.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
libc = "0.2.148"
tracing = { version = "0.1.37", default-features = false }
