interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: ARDUINO-F103-SPI.bin
    permissions: rwx
    size: 0x1644c
symbols:
  0x0: reent.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x800010d: __do_global_dtors_aux
  0x8000131: frame_dummy
  0x8000179: strlen
  0x8000189: _Z12readRegisterhi
  0x80001dd: _Z13writeRegisterhh
  0x8000219: setup
  0x8000251: loop
  0x8000281: _ZN8SPIClassC1Ev
  0x80002d1: _Z41__static_initialization_and_destruction_0ii
  0x80002f1: _ZN8SPIClass5beginEh
  0x800037b: _ZN8SPIClass8transferEhh15SPITransferMode
  0x8000431: _GLOBAL__sub_I_SPI
  0x8000441: SystemClock_Config
  0x80004e1: Reset_Handler
  0x80004e4: CopyDataInit
  0x80004ec: LoopCopyDataInit
  0x80004fa: FillZerobss
  0x8000500: LoopFillZerobss
  0x8000528: Default_Handler
  0x8000529: USB_HP_CAN1_TX_IRQHandler
  0x800052b: init
  0x8000533: HAL_MspInit
  0x8000535: HAL_InitTick
  0x8000581: HAL_Init
  0x80005a5: HAL_IncTick
  0x80005bd: HAL_GetTick
  0x80005c9: HAL_NVIC_SetPriorityGrouping
  0x80005ed: HAL_NVIC_SetPriority
  0x8000651: HAL_NVIC_EnableIRQ
  0x800066d: HAL_SYSTICK_Config
  0x8000699: HAL_NVIC_ClearPendingIRQ
  0x80006b9: HAL_SYSTICK_CLKSourceConfig
  0x80006d9: HAL_SYSTICK_Callback
  0x80006db: HAL_SYSTICK_IRQHandler
  0x80006e5: HAL_DMA_Abort_IT
  0x800077d: HAL_GPIO_Init
  0x8000969: HAL_GPIO_ReadPin
  0x8000977: HAL_GPIO_WritePin
  0x8000985: HAL_GPIO_EXTI_IRQHandler
  0x80009a1: I2C_Master_SB
  0x8000a2b: I2C_Master_ADD10
  0x8000a37: I2C_Master_ADDR
  0x8000c11: I2C_SlaveTransmit_BTF
  0x8000c31: I2C_SlaveReceive_BTF
  0x8000c51: HAL_I2C_Slave_Sequential_Transmit_IT
  0x8000cdd: HAL_I2C_Slave_Sequential_Receive_IT
  0x8000d69: HAL_I2C_EnableListen_IT
  0x8000da7: HAL_I2C_MasterTxCpltCallback
  0x8000da9: HAL_I2C_MasterRxCpltCallback
  0x8000dab: HAL_I2C_SlaveTxCpltCallback
  0x8000dad: I2C_SlaveTransmit_TXE
  0x8000dfd: HAL_I2C_SlaveRxCpltCallback
  0x8000dff: I2C_SlaveReceive_RXNE
  0x8000e4b: I2C_Slave_ADDR
  0x8000e75: I2C_Slave_AF
  0x8000f09: HAL_I2C_MemTxCpltCallback
  0x8000f0b: I2C_MasterTransmit_TXE
  0x8001055: I2C_MasterTransmit_BTF
  0x80010f3: HAL_I2C_MemRxCpltCallback
  0x80010f5: I2C_MasterReceive_RXNE
  0x80011c5: I2C_MasterReceive_BTF
  0x80012c3: HAL_I2C_AbortCpltCallback
  0x80012c5: I2C_ITError
  0x800140d: I2C_Slave_STOPF
  0x8001511: HAL_I2C_EV_IRQHandler
  0x8001679: HAL_I2C_ER_IRQHandler
  0x8001755: I2C_DMAAbort
  0x80017b5: RCC_Delay
  0x80017e1: HAL_RCC_OscConfig
  0x8001bc1: HAL_RCC_GetSysClockFreq
  0x8001c2d: HAL_RCC_ClockConfig
  0x8001d9d: HAL_RCC_GetHCLKFreq
  0x8001da9: HAL_RCC_GetPCLK1Freq
  0x8001dc9: HAL_RCC_GetPCLK2Freq
  0x8001de9: HAL_RCCEx_PeriphCLKConfig
  0x8001efd: HAL_RTC_AlarmIRQHandler
  0x8001f35: SPI_WaitFlagStateUntilTimeout
  0x8001fcb: SPI_CheckFlag_BSY
  0x8001ff1: HAL_SPI_MspInit
  0x8001ff3: HAL_SPI_TransmitReceive
  0x800232d: HAL_SPI_Init
  0x80023b5: SPI_ISCRCErrorValid
  0x80023b9: HAL_TIM_PWM_DeInit
  0x80023f3: HAL_TIM_IC_CaptureCallback
  0x80023f5: HAL_TIM_PWM_PulseFinishedCallback
  0x80023f7: HAL_TIM_TriggerCallback
  0x80023f9: HAL_TIM_IRQHandler
  0x8002573: TIM_CCxChannelCmd
  0x8002591: HAL_TIM_PWM_Stop
  0x80025f1: TIM_CCxNChannelCmd
  0x800260d: HAL_TIMEx_PWMN_Stop
  0x8002659: HAL_TIMEx_CommutationCallback
  0x800265b: HAL_TIMEx_BreakCallback
  0x800265d: UART_EndRxTransfer
  0x8002679: UART_Transmit_IT
  0x80026e5: UART_SetConfig
  0x8002895: UART_WaitOnFlagUntilTimeout
  0x80028f9: HAL_UART_MspInit
  0x80028fb: HAL_UART_Init
  0x8002959: HAL_UART_Transmit
  0x8002a3b: HAL_UART_Transmit_IT
  0x8002a83: UART_EndTransmit_IT
  0x8002a9d: UART_Receive_IT
  0x8002b3d: HAL_UART_IRQHandler
  0x8002c5d: UART_DMAAbortOnError
  0x8002c6d: HAL_UART_GetState
  0x8002c79: is_pin_configured
  0x8002c8f: set_pin_configured
  0x8002cad: reset_pin_configured
  0x8002ccd: get_GPIO_Port
  0x8002d09: set_GPIO_Port_Clock
  0x8002db1: get_pwm_channel
  0x8002ddd: HAL_TIM_PWM_MspDeInit
  0x8002de5: pwm_stop
  0x8002e3d: noOsSystickHandler
  0x8002e3f: SysTick_Handler
  0x8002e51: digital_io_init
  0x8002ed1: digital_io_write
  0x8002ee9: digital_io_read
  0x8002ef3: hw_config_init
  0x8002eff: pinmap_find_peripheral
  0x8002f19: pinmap_peripheral
  0x8002f2b: pinmap_find_pin
  0x8002f43: pinmap_pin
  0x8002f53: pinmap_find_function
  0x8002f6f: pinmap_function
  0x8002f83: pin_in_pinmap
  0x8002fa7: pinmap_merge_peripheral
  0x8002fb9: HAL_RTC_AlarmAEventCallback
  0x8002fd1: RTC_Alarm_IRQHandler
  0x8002fe1: spi_getClkFreqInst
  0x800301d: spi_init
  0x8003cf9: spi_transfer
  0x8003d23: _Error_Handler
  0x8003d25: SystemInit
  0x8003d71: timer_disable_clock
  0x8003dd5: get_timer_obj
  0x8003dd9: HAL_TIM_OC_DelayElapsedCallback
  0x8003df3: HAL_TIM_PeriodElapsedCallback
  0x8003e01: TIM1_UP_IRQHandler
  0x8003e15: TIM2_IRQHandler
  0x8003e29: TIM3_IRQHandler
  0x8003e3d: TIM4_IRQHandler
  0x8003e51: get_i2c_obj
  0x8003e55: HAL_I2C_AddrCallback
  0x8003ea5: HAL_I2C_ListenCpltCallback
  0x8003ed5: HAL_I2C_ErrorCallback
  0x8003eed: I2C1_EV_IRQHandler
  0x8003efd: I2C1_ER_IRQHandler
  0x8003f0d: I2C2_EV_IRQHandler
  0x8003f1d: I2C2_ER_IRQHandler
  0x8003f2d: uart_init
  0x8004365: uart_debug_init
  0x80043b5: uart_debug_write
  0x800446d: serial_tx_active
  0x8004491: uart_attach_tx_callback
  0x80044e5: uart_index
  0x8004509: HAL_UART_RxCpltCallback
  0x800452d: HAL_UART_TxCpltCallback
  0x8004579: HAL_UART_ErrorCallback
  0x80045b9: USART1_IRQHandler
  0x80045d1: USART2_IRQHandler
  0x80045e9: USART3_IRQHandler
  0x8004601: _sbrk
  0x800463d: _close
  0x8004643: _fstat
  0x800464d: _isatty
  0x8004651: _lseek
  0x8004655: _read
  0x8004659: _write
  0x8004665: _exit
  0x8004669: _kill
  0x8004679: _getpid
  0x800467d: pinMode
  0x8004711: digitalWrite
  0x8004759: digitalRead
  0x80047a9: _ZN14HardwareSerial16_tx_complete_irqEP8serial_s
  0x80047dd: _ZN14HardwareSerial9availableEv
  0x80047f1: _ZN14HardwareSerial4peekEv
  0x800480d: _ZN14HardwareSerial4readEv
  0x8004835: _ZN14HardwareSerial5flushEv
  0x8004849: _ZN14HardwareSerial5writeEh
  0x8004899: _Z14serialEventRunv
  0x80048c5: _ZN14HardwareSerial4initEv
  0x80048e9: _ZN14HardwareSerial5setRxEm
  0x8004901: _ZN14HardwareSerial5setTxEm
  0x8004919: _ZN14HardwareSerialC1EPv
  0x8004975: _Z41__static_initialization_and_destruction_0ii
  0x8004999: _GLOBAL__sub_I_Serial2
  0x80049a7: _ZNK9IPAddress7printToER5Print
  0x80049e1: _ZN9IPAddressC1Ehhhh
  0x80049fd: _Z41__static_initialization_and_destruction_0ii
  0x8004a29: _GLOBAL__sub_I__ZN9IPAddressC2Ev
  0x8004a37: _ZN5Print5writeEPKhj
  0x8004a5b: _ZN5Print5printEc
  0x8004a65: _ZN5Print11printNumberEmh
  0x8004abf: _ZN5Print5printEmi
  0x8004ad5: _ZN5Print5printEhi
  0x8004add: _Z11initVariantv
  0x8004adf: _Z7premainv
  0x8004aed: main
  0x8004b0d: _ZL10get_pin_idt
  0x8004b21: __tcf_0
  0x8004b49: _Z41__static_initialization_and_destruction_0ii
  0x8004bf5: EXTI0_IRQHandler
  0x8004bff: EXTI1_IRQHandler
  0x8004c09: EXTI2_IRQHandler
  0x8004c13: EXTI3_IRQHandler
  0x8004c1d: EXTI4_IRQHandler
  0x8004c27: EXTI9_5_IRQHandler
  0x8004c3d: EXTI15_10_IRQHandler
  0x8004c55: _ZNKSt8functionIFvvEEclEv
  0x8004c65: HAL_GPIO_EXTI_Callback
  0x8004c85: _GLOBAL__sub_I__Z22stm32_interrupt_enableP12GPIO_TypeDeftSt8functionIFvvEEm
  0x8004c93: __aeabi_atexit
  0x8004c9d: __cxa_atexit
  0x8004cb9: __libc_init_array
  0x8004d01: memset
  0x8004d11: _free_r
  0x8004da9: _malloc_r
  0x8004e65: __sfputc_r
  0x8004e91: __sfputs_r
  0x8004eb5: _vfiprintf_r
  0x80050e1: _printf_common
  0x80051d1: _printf_i
  0x8005411: iprintf
  0x8005441: _sbrk_r
  0x8005461: __swbuf_r
  0x8005505: __swsetup_r
  0x80055e1: abort
  0x80055f1: __sflush_r
  0x8005701: _fflush_r
  0x8005755: _cleanup_r
  0x8005761: std.isra.0
  0x80057a9: __sfmoreglue
  0x80057d5: __sinit
  0x8005835: __sfp
  0x80058ad: _fwalk_reent
  0x80058e9: __swhatbuf_r
  0x8005931: __smakebuf_r
  0x80059b1: memchr
  0x80059cd: __malloc_lock
  0x80059cf: __malloc_unlock
  0x80059d1: _raise_r
  0x8005a21: raise
  0x8005a31: _kill_r
  0x8005a55: _getpid_r
  0x8005a59: __sread
  0x8005a7b: __swrite
  0x8005ab3: __sseek
  0x8005ad7: __sclose
  0x8005ae1: _write_r
  0x8005b05: _close_r
  0x8005b25: _fstat_r
  0x8005b49: _isatty_r
  0x8005b69: _lseek_r
  0x8005b8d: _read_r
  0x8005bb1: _ZSt25__throw_bad_function_callv
  0x8005bb9: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKSsj
  0x8005c7d: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKSsj
  0x8005d41: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x8005dc5: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x8005e48: __EH_FRAME_BEGIN__
  0x8005e49: _init
  0x8005e55: _fini
  0x8005e60: _etext
  0x8005e74: PinMap_PWM
  0x8005fc4: PinMap_SPI_MISO
  0x8005ff4: PinMap_SPI_MOSI
  0x8006024: PinMap_SPI_SCLK
  0x8006054: PinMap_SPI_SSEL
  0x8006084: PinMap_UART_RX
  0x80060cc: PinMap_UART_TX
  0x8006170: digitalPin
  0x8006214: AHBPrescTable
  0x8006224: APBPrescTable
  0x800627c: _ZTV14HardwareSerial
  0x800629c: _ZTV9IPAddress
  0x80062a8: _global_impure_ptr
  0x80062e0: __sf_fake_stderr
  0x8006300: __sf_fake_stdin
  0x8006320: __sf_fake_stdout
  0x8006340: __exidx_end
  0x8006344: __frame_dummy_init_array_entry
  0x8006368: __init_array_end
  0x800636c: _sidata
  0x20000000: __dso_handle
  0x20000004: uwTickFreq
  0x20000008: uwTickPrio
  0x2000000c: SystemCoreClock
  0x20000010: serial_debug
  0x2000007c: _impure_ptr
  0x20000080: impure_data
  0x200000e0: _edata
  0x200000e4: object.8672
  0x200000fc: SPI
  0x20000190: uCRCErrorWorkaroundCheck
  0x20000194: RTCUserCallback
  0x20000198: RtcHandle
  0x200001ac: callbackUserData
  0x200001b0: timer_handles
  0x20000208: i2c_handles
  0x20000210: rx_callback
  0x20000224: rx_callback_obj
  0x20000238: tx_callback
  0x2000024c: tx_callback_obj
  0x20000260: uart_handlers
  0x20000274: heap_end.4572
  0x20000278: g_anOutputPinConfigured
  0x2000028c: g_digPinConfigured
  0x200002a0: Serial2
  0x200003e4: _ZL11INADDR_NONE
  0x200003ec: _ZL13gpio_irq_conf
  0x2000052c: __malloc_free_list
  0x20000530: __malloc_sbrk_start
  0x20000534: _ZGVNSt7collateIcE2idE
  0x20000538: _ZGVNSt8messagesIcE2idE
  0x2000053c: _ZGVNSt8time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000540: _ZGVNSt8time_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000544: _ZGVNSt11__timepunctIcE2idE
  0x20000548: _ZGVNSt7num_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x2000054c: _ZGVNSt7num_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000550: _ZGVNSt8numpunctIcE2idE
  0x20000554: _ZGVNSt9money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000558: _ZGVNSt9money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x2000055c: _ZGVNSt10moneypunctIcLb1EE2idE
  0x20000560: _ZGVNSt10moneypunctIcLb0EE2idE
  0x20000564: _ZGVNSt7collateIwE2idE
  0x20000568: _ZGVNSt8messagesIwE2idE
  0x2000056c: _ZGVNSt8time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000570: _ZGVNSt8time_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000574: _ZGVNSt11__timepunctIwE2idE
  0x20000578: _ZGVNSt7num_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x2000057c: _ZGVNSt7num_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000580: _ZGVNSt8numpunctIwE2idE
  0x20000584: _ZGVNSt9money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000588: _ZGVNSt9money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x2000058c: _ZGVNSt10moneypunctIwLb1EE2idE
  0x20000590: _ZGVNSt10moneypunctIwLb0EE2idE
  0x20000594: _ZGVNSt7__cxx117collateIwE2idE
  0x20000598: _ZGVNSt7__cxx118messagesIwE2idE
  0x2000059c: _ZGVNSt7__cxx118time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200005a0: _ZGVNSt7__cxx118numpunctIwE2idE
  0x200005a4: _ZGVNSt7__cxx119money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200005a8: _ZGVNSt7__cxx119money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200005ac: _ZGVNSt7__cxx1110moneypunctIwLb1EE2idE
  0x200005b0: _ZGVNSt7__cxx1110moneypunctIwLb0EE2idE
  0x200005b4: _ZGVNSt7__cxx117collateIcE2idE
  0x200005b8: _ZGVNSt7__cxx118messagesIcE2idE
  0x200005bc: _ZGVNSt7__cxx118time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200005c0: _ZGVNSt7__cxx118numpunctIcE2idE
  0x200005c4: _ZGVNSt7__cxx119money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200005c8: _ZGVNSt7__cxx119money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200005cc: _ZGVNSt7__cxx1110moneypunctIcLb1EE2idE
  0x200005d0: _ZGVNSt7__cxx1110moneypunctIcLb0EE2idE
  0x200005d4: uwTick
  0x200005d8: errno
  0x200005dc: _end
  0x20005000: _estack
  0xf108f85f: BootRAM
