interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: ARDUINO-F103-PWM.bin
    permissions: rwx
    size: 0x16374
symbols:
  0x0: reent.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x800010d: __do_global_dtors_aux
  0x8000131: frame_dummy
  0x8000179: strlen
  0x8000189: setup
  0x800019d: loop
  0x80001d1: SystemClock_Config
  0x8000271: Reset_Handler
  0x8000274: CopyDataInit
  0x800027c: LoopCopyDataInit
  0x800028a: FillZerobss
  0x8000290: LoopFillZerobss
  0x80002b8: Default_Handler
  0x80002b9: USB_HP_CAN1_TX_IRQHandler
  0x80002bb: init
  0x80002c3: HAL_MspInit
  0x80002c5: HAL_InitTick
  0x8000311: HAL_Init
  0x8000335: HAL_IncTick
  0x800034d: HAL_GetTick
  0x8000359: HAL_ADC_PollForConversion
  0x80004c9: HAL_ADC_GetValue
  0x80004d1: HAL_ADC_ConfigChannel
  0x8000609: HAL_ADC_GetState
  0x800060d: ADC_Enable
  0x800068d: HAL_ADC_Start
  0x8000779: ADC_ConversionStop_Disable
  0x80007c5: HAL_ADC_Init
  0x80008d5: HAL_ADC_DeInit
  0x80009d1: HAL_ADC_Stop
  0x8000a0d: HAL_ADCEx_Calibration_Start
  0x8000af9: HAL_NVIC_SetPriorityGrouping
  0x8000b1d: HAL_NVIC_SetPriority
  0x8000b81: HAL_NVIC_EnableIRQ
  0x8000b9d: HAL_SYSTICK_Config
  0x8000bc9: HAL_NVIC_ClearPendingIRQ
  0x8000be9: HAL_SYSTICK_CLKSourceConfig
  0x8000c09: HAL_SYSTICK_Callback
  0x8000c0b: HAL_SYSTICK_IRQHandler
  0x8000c15: HAL_DMA_Abort_IT
  0x8000cad: HAL_GPIO_Init
  0x8000e99: HAL_GPIO_WritePin
  0x8000ea5: HAL_GPIO_EXTI_IRQHandler
  0x8000ec1: I2C_Master_SB
  0x8000f4b: I2C_Master_ADD10
  0x8000f57: I2C_Master_ADDR
  0x8001131: I2C_SlaveTransmit_BTF
  0x8001151: I2C_SlaveReceive_BTF
  0x8001171: HAL_I2C_Slave_Sequential_Transmit_IT
  0x80011fd: HAL_I2C_Slave_Sequential_Receive_IT
  0x8001289: HAL_I2C_EnableListen_IT
  0x80012c7: HAL_I2C_MasterTxCpltCallback
  0x80012c9: HAL_I2C_MasterRxCpltCallback
  0x80012cb: HAL_I2C_SlaveTxCpltCallback
  0x80012cd: I2C_SlaveTransmit_TXE
  0x800131d: HAL_I2C_SlaveRxCpltCallback
  0x800131f: I2C_SlaveReceive_RXNE
  0x800136b: I2C_Slave_ADDR
  0x8001395: I2C_Slave_AF
  0x8001429: HAL_I2C_MemTxCpltCallback
  0x800142b: I2C_MasterTransmit_TXE
  0x8001575: I2C_MasterTransmit_BTF
  0x8001613: HAL_I2C_MemRxCpltCallback
  0x8001615: I2C_MasterReceive_RXNE
  0x80016e5: I2C_MasterReceive_BTF
  0x80017e3: HAL_I2C_AbortCpltCallback
  0x80017e5: I2C_ITError
  0x800192d: I2C_Slave_STOPF
  0x8001a31: HAL_I2C_EV_IRQHandler
  0x8001b99: HAL_I2C_ER_IRQHandler
  0x8001c75: I2C_DMAAbort
  0x8001cd5: RCC_Delay
  0x8001d01: HAL_RCC_OscConfig
  0x80020e1: HAL_RCC_GetSysClockFreq
  0x800214d: HAL_RCC_ClockConfig
  0x80022bd: HAL_RCC_GetHCLKFreq
  0x80022c9: HAL_RCC_GetPCLK1Freq
  0x80022e9: HAL_RCC_GetPCLK2Freq
  0x8002309: HAL_RCC_GetClockConfig
  0x8002345: HAL_RCCEx_PeriphCLKConfig
  0x8002459: HAL_RCCEx_GetPeriphCLKFreq
  0x8002555: HAL_RTC_AlarmIRQHandler
  0x800258d: TIM_OC1_SetConfig
  0x80025e9: TIM_OC3_SetConfig
  0x800264d: TIM_OC4_SetConfig
  0x8002695: HAL_TIM_PWM_DeInit
  0x80026cf: HAL_TIM_IC_CaptureCallback
  0x80026d1: HAL_TIM_PWM_PulseFinishedCallback
  0x80026d3: HAL_TIM_TriggerCallback
  0x80026d5: HAL_TIM_IRQHandler
  0x8002851: TIM_Base_SetConfig
  0x80028c9: HAL_TIM_PWM_Init
  0x80028fd: TIM_OC2_SetConfig
  0x8002961: HAL_TIM_PWM_ConfigChannel
  0x8002a3d: TIM_CCxChannelCmd
  0x8002a59: HAL_TIM_PWM_Start
  0x8002a89: HAL_TIM_PWM_Stop
  0x8002ae9: TIM_CCxNChannelCmd
  0x8002b05: HAL_TIMEx_PWMN_Start
  0x8002b29: HAL_TIMEx_PWMN_Stop
  0x8002b75: HAL_TIMEx_CommutationCallback
  0x8002b77: HAL_TIMEx_BreakCallback
  0x8002b79: UART_EndRxTransfer
  0x8002b95: UART_Transmit_IT
  0x8002c01: UART_SetConfig
  0x8002db1: UART_WaitOnFlagUntilTimeout
  0x8002e15: HAL_UART_MspInit
  0x8002e17: HAL_UART_Init
  0x8002e75: HAL_UART_Transmit
  0x8002f57: HAL_UART_Transmit_IT
  0x8002f9f: UART_EndTransmit_IT
  0x8002fb9: UART_Receive_IT
  0x8003059: HAL_UART_IRQHandler
  0x8003179: UART_DMAAbortOnError
  0x8003189: HAL_UART_GetState
  0x8003195: is_pin_configured
  0x80031ab: set_pin_configured
  0x80031c9: reset_pin_configured
  0x80031e9: get_GPIO_Port
  0x8003225: set_GPIO_Port_Clock
  0x80032cd: get_adc_channel
  0x80032e9: get_pwm_channel
  0x8003315: HAL_ADC_MspInit
  0x8003391: HAL_ADC_MspDeInit
  0x80033ed: adc_read_value
  0x80034d5: HAL_TIM_PWM_MspInit
  0x800377d: HAL_TIM_PWM_MspDeInit
  0x8003785: pwm_start
  0x8003851: pwm_stop
  0x80038a9: noOsSystickHandler
  0x80038ab: SysTick_Handler
  0x80038bd: digital_io_init
  0x800393d: digital_io_write
  0x8003955: hw_config_init
  0x8003961: pinmap_find_peripheral
  0x800397b: pinmap_peripheral
  0x800398d: pinmap_find_pin
  0x80039a5: pinmap_pin
  0x80039b5: pinmap_find_function
  0x80039d1: pinmap_function
  0x80039e5: pin_in_pinmap
  0x8003a09: pinmap_merge_peripheral
  0x8003a1d: HAL_RTC_AlarmAEventCallback
  0x8003a35: RTC_Alarm_IRQHandler
  0x8003a45: _Error_Handler
  0x8003a49: SystemInit
  0x8003a95: timer_enable_clock
  0x8003b3d: timer_disable_clock
  0x8003ba1: getTimerClkSrc
  0x8003be9: getTimerClkFreq
  0x8003c55: get_timer_obj
  0x8003c59: HAL_TIM_OC_DelayElapsedCallback
  0x8003c73: HAL_TIM_PeriodElapsedCallback
  0x8003c81: TIM1_UP_IRQHandler
  0x8003c95: TIM2_IRQHandler
  0x8003ca9: TIM3_IRQHandler
  0x8003cbd: TIM4_IRQHandler
  0x8003cd1: get_i2c_obj
  0x8003cd5: HAL_I2C_AddrCallback
  0x8003d25: HAL_I2C_ListenCpltCallback
  0x8003d55: HAL_I2C_ErrorCallback
  0x8003d6d: I2C1_EV_IRQHandler
  0x8003d7d: I2C1_ER_IRQHandler
  0x8003d8d: I2C2_EV_IRQHandler
  0x8003d9d: I2C2_ER_IRQHandler
  0x8003dad: uart_init
  0x80041e5: uart_debug_init
  0x8004235: uart_debug_write
  0x80042ed: serial_tx_active
  0x8004311: uart_attach_tx_callback
  0x8004365: uart_index
  0x8004389: HAL_UART_RxCpltCallback
  0x80043ad: HAL_UART_TxCpltCallback
  0x80043f9: HAL_UART_ErrorCallback
  0x8004439: USART1_IRQHandler
  0x8004451: USART2_IRQHandler
  0x8004469: USART3_IRQHandler
  0x8004481: _sbrk
  0x80044bd: _close
  0x80044c3: _fstat
  0x80044cd: _isatty
  0x80044d1: _lseek
  0x80044d5: _read
  0x80044d9: _write
  0x80044e5: _exit
  0x80044e9: _kill
  0x80044f9: _getpid
  0x80044fd: analogRead
  0x800455d: analogWrite
  0x800460d: pinMode
  0x80046a1: digitalWrite
  0x80046e9: _ZN14HardwareSerial16_tx_complete_irqEP8serial_s
  0x800471d: _ZN14HardwareSerial9availableEv
  0x8004731: _ZN14HardwareSerial4peekEv
  0x800474d: _ZN14HardwareSerial4readEv
  0x8004775: _ZN14HardwareSerial5flushEv
  0x8004789: _ZN14HardwareSerial5writeEh
  0x80047d9: _Z14serialEventRunv
  0x8004805: _ZN14HardwareSerial4initEv
  0x8004829: _ZN14HardwareSerial5setRxEm
  0x8004841: _ZN14HardwareSerial5setTxEm
  0x8004859: _ZN14HardwareSerialC1EPv
  0x80048b5: _Z41__static_initialization_and_destruction_0ii
  0x80048d9: _GLOBAL__sub_I_Serial2
  0x80048e7: _ZNK9IPAddress7printToER5Print
  0x8004921: _ZN9IPAddressC1Ehhhh
  0x800493d: _Z41__static_initialization_and_destruction_0ii
  0x8004969: _GLOBAL__sub_I__ZN9IPAddressC2Ev
  0x8004977: _ZN5Print5writeEPKhj
  0x800499b: _ZN5Print5printEc
  0x80049a5: _ZN5Print11printNumberEmh
  0x80049ff: _ZN5Print5printEmi
  0x8004a15: _ZN5Print5printEhi
  0x8004a1d: _Z11initVariantv
  0x8004a1f: _Z7premainv
  0x8004a2d: main
  0x8004a4d: _ZL10get_pin_idt
  0x8004a61: __tcf_0
  0x8004a89: _Z41__static_initialization_and_destruction_0ii
  0x8004b35: EXTI0_IRQHandler
  0x8004b3f: EXTI1_IRQHandler
  0x8004b49: EXTI2_IRQHandler
  0x8004b53: EXTI3_IRQHandler
  0x8004b5d: EXTI4_IRQHandler
  0x8004b67: EXTI9_5_IRQHandler
  0x8004b7d: EXTI15_10_IRQHandler
  0x8004b95: _ZNKSt8functionIFvvEEclEv
  0x8004ba5: HAL_GPIO_EXTI_Callback
  0x8004bc5: _GLOBAL__sub_I__Z22stm32_interrupt_enableP12GPIO_TypeDeftSt8functionIFvvEEm
  0x8004bd3: __aeabi_atexit
  0x8004bdd: __cxa_atexit
  0x8004bf9: __libc_init_array
  0x8004c41: memset
  0x8004c51: _free_r
  0x8004ce9: _malloc_r
  0x8004da5: __sfputc_r
  0x8004dd1: __sfputs_r
  0x8004df5: _vfiprintf_r
  0x8005021: _printf_common
  0x8005111: _printf_i
  0x8005351: iprintf
  0x8005381: _sbrk_r
  0x80053a1: __swbuf_r
  0x8005445: __swsetup_r
  0x8005521: abort
  0x8005531: __sflush_r
  0x8005641: _fflush_r
  0x8005695: _cleanup_r
  0x80056a1: std.isra.0
  0x80056e9: __sfmoreglue
  0x8005715: __sinit
  0x8005775: __sfp
  0x80057ed: _fwalk_reent
  0x8005829: __swhatbuf_r
  0x8005871: __smakebuf_r
  0x80058f1: memchr
  0x800590d: __malloc_lock
  0x800590f: __malloc_unlock
  0x8005911: _raise_r
  0x8005961: raise
  0x8005971: _kill_r
  0x8005995: _getpid_r
  0x8005999: __sread
  0x80059bb: __swrite
  0x80059f3: __sseek
  0x8005a17: __sclose
  0x8005a21: _write_r
  0x8005a45: _close_r
  0x8005a65: _fstat_r
  0x8005a89: _isatty_r
  0x8005aa9: _lseek_r
  0x8005acd: _read_r
  0x8005af1: _ZSt25__throw_bad_function_callv
  0x8005af9: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKSsj
  0x8005bbd: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKSsj
  0x8005c81: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x8005d05: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x8005d88: __EH_FRAME_BEGIN__
  0x8005d89: _init
  0x8005d95: _fini
  0x8005da0: _etext
  0x8005dc8: PinMap_ADC
  0x8005e7c: PinMap_PWM
  0x8005fcc: PinMap_UART_RX
  0x8006014: PinMap_UART_TX
  0x80060b8: digitalPin
  0x80060f4: AHBPrescTable
  0x8006104: APBPrescTable
  0x8006194: _ZTV14HardwareSerial
  0x80061b4: _ZTV9IPAddress
  0x80061c0: _global_impure_ptr
  0x80061f8: __sf_fake_stderr
  0x8006218: __sf_fake_stdin
  0x8006238: __sf_fake_stdout
  0x8006258: __exidx_end
  0x800625c: __frame_dummy_init_array_entry
  0x800627c: __init_array_end
  0x8006280: _sidata
  0x20000000: __dso_handle
  0x20000004: analogPin
  0x20000008: ledPin
  0x2000000c: uwTickFreq
  0x20000010: uwTickPrio
  0x20000014: g_current_pin
  0x20000018: SystemCoreClock
  0x2000001c: serial_debug
  0x20000088: _readResolution
  0x2000008c: _writeResolution
  0x20000090: _impure_ptr
  0x20000094: impure_data
  0x200000f4: _edata
  0x200000f8: object.8672
  0x20000110: val
  0x20000114: RTCUserCallback
  0x20000118: RtcHandle
  0x2000012c: callbackUserData
  0x20000130: timer_handles
  0x20000188: i2c_handles
  0x20000190: rx_callback
  0x200001a4: rx_callback_obj
  0x200001b8: tx_callback
  0x200001cc: tx_callback_obj
  0x200001e0: uart_handlers
  0x200001f4: heap_end.4572
  0x200001f8: g_anOutputPinConfigured
  0x2000020c: g_digPinConfigured
  0x20000220: Serial2
  0x20000364: _ZL11INADDR_NONE
  0x2000036c: _ZL13gpio_irq_conf
  0x200004ac: __malloc_free_list
  0x200004b0: __malloc_sbrk_start
  0x200004b4: _ZGVNSt7collateIcE2idE
  0x200004b8: _ZGVNSt8messagesIcE2idE
  0x200004bc: _ZGVNSt8time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200004c0: _ZGVNSt8time_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200004c4: _ZGVNSt11__timepunctIcE2idE
  0x200004c8: _ZGVNSt7num_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200004cc: _ZGVNSt7num_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200004d0: _ZGVNSt8numpunctIcE2idE
  0x200004d4: _ZGVNSt9money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200004d8: _ZGVNSt9money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200004dc: _ZGVNSt10moneypunctIcLb1EE2idE
  0x200004e0: _ZGVNSt10moneypunctIcLb0EE2idE
  0x200004e4: _ZGVNSt7collateIwE2idE
  0x200004e8: _ZGVNSt8messagesIwE2idE
  0x200004ec: _ZGVNSt8time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004f0: _ZGVNSt8time_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004f4: _ZGVNSt11__timepunctIwE2idE
  0x200004f8: _ZGVNSt7num_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004fc: _ZGVNSt7num_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000500: _ZGVNSt8numpunctIwE2idE
  0x20000504: _ZGVNSt9money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000508: _ZGVNSt9money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x2000050c: _ZGVNSt10moneypunctIwLb1EE2idE
  0x20000510: _ZGVNSt10moneypunctIwLb0EE2idE
  0x20000514: _ZGVNSt7__cxx117collateIwE2idE
  0x20000518: _ZGVNSt7__cxx118messagesIwE2idE
  0x2000051c: _ZGVNSt7__cxx118time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000520: _ZGVNSt7__cxx118numpunctIwE2idE
  0x20000524: _ZGVNSt7__cxx119money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000528: _ZGVNSt7__cxx119money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x2000052c: _ZGVNSt7__cxx1110moneypunctIwLb1EE2idE
  0x20000530: _ZGVNSt7__cxx1110moneypunctIwLb0EE2idE
  0x20000534: _ZGVNSt7__cxx117collateIcE2idE
  0x20000538: _ZGVNSt7__cxx118messagesIcE2idE
  0x2000053c: _ZGVNSt7__cxx118time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000540: _ZGVNSt7__cxx118numpunctIcE2idE
  0x20000544: _ZGVNSt7__cxx119money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000548: _ZGVNSt7__cxx119money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x2000054c: _ZGVNSt7__cxx1110moneypunctIcLb1EE2idE
  0x20000550: _ZGVNSt7__cxx1110moneypunctIcLb0EE2idE
  0x20000554: uwTick
  0x20000558: errno
  0x2000055c: _end
  0x20005000: _estack
  0xf108f85f: BootRAM
