interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  .stack:
    base_addr: 0x1fff0000
    permissions: rw-
    size: 0xa7c
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: K64F-RIOT-ADC.bin
    permissions: rwx
    size: 0x128f8
symbols:
  0x0: _sbackup_data
  0x10: _flashsec_length
  0x40: vector_cpu
  0x1d8: vector_padding
  0x400: _vectors_length
  0x410: _sfixed
  0x411: _init
  0x413: _fini
  0x415: _sbrk_r
  0x451: _read_r
  0x459: _write_r
  0x461: _close_r
  0x46b: _lseek_r
  0x475: _fstat_r
  0x47f: _isatty_r
  0x491: sched_run
  0x4f5: sched_set_status
  0x575: sched_switch
  0x5a5: sched_task_exit
  0x5e1: thread_stack_init
  0x649: cpu_switch_context_exit
  0x64e: unreachable325
  0x651: thread_yield_higher
  0x661: isr_pendsv
  0x67d: isr_svc
  0x681: context_restore
  0x699: hard_fault_default
  0x6ac: fix_msp
  0x6b2: test_sp
  0x6c0: use_psp
  0x6c4: out
  0x6dd: nmi_default
  0x6ed: mem_manage_default
  0x6fd: bus_fault_default
  0x70d: usage_fault_default
  0x71d: debug_mon_default
  0x72d: isr_systick
  0x73d: post_startup
  0x741: reset_handler_default
  0x7ad: hard_fault_handler
  0x935: irq_disable
  0x93d: irq_enable
  0x945: irq_restore
  0x94b: irq_is_in
  0x955: pre_startup
  0x969: isr_wdog_ewm
  0x96d: wdog_disable
  0x985: stdio_init
  0x993: stdio_read
  0x999: stdio_write
  0x9ab: pm_off
  0x9b5: board_init
  0xa19: panic_arch
  0xa1d: core_panic
  0xa61: main_trampoline
  0xa79: idle_thread
  0xa81: kernel_init
  0xad9: thread_add_to_list
  0xb09: thread_create
  0xbfd: pm_set_lowest
  0xc01: cpu_init
  0xc25: uart_init
  0xce1: uart_write
  0xd01: isr_uart0_rx_tx
  0xd35: bit_clear8
  0xd55: kinetis_mcg_set_fll_factor
  0xd69: kinetis_mcg_enable_osc
  0xd89: kinetis_mcg_set_mode
  0xf09: kinetis_mcg_init
  0x100d: gpio_init_port
  0x1039: gpio_init
  0x1085: gpio_set
  0x109f: periph_init
  0x10a5: main
  0x10bd: auto_init
  0x10c1: cortexm_init
  0x1101: poweron
  0x114d: poweroff
  0x1199: spi_init_pins
  0x11c5: spi_init
  0x1209: done
  0x1255: prep
  0x12a1: kinetis_adc_calibrate
  0x1309: adc_init
  0x135d: adc_sample
  0x13a9: _mutex_lock
  0x1409: mutex_unlock
  0x1455: __libc_init_array
  0x149d: _malloc_r
  0x1551: iprintf
  0x1581: _puts_r
  0x165d: puts
  0x166d: __swbuf_r
  0x1711: __swsetup_r
  0x17ed: __sflush_r
  0x18f9: _fflush_r
  0x1971: std
  0x19b9: _cleanup_r
  0x19c5: __sfmoreglue
  0x19f1: __sfp_lock_acquire
  0x19fd: __sfp_lock_release
  0x1a09: __sinit_lock_acquire
  0x1a15: __sinit_lock_release
  0x1a21: __sinit
  0x1a91: __sfp
  0x1b1d: _fwalk_reent
  0x1b5b: __retarget_lock_init_recursive
  0x1b5d: __retarget_lock_acquire_recursive
  0x1b5f: __retarget_lock_release_recursive
  0x1b61: __swhatbuf_r
  0x1ba9: __smakebuf_r
  0x1c29: memset
  0x1c39: __malloc_lock
  0x1c45: __malloc_unlock
  0x1c51: _free_r
  0x1ced: __sfputc_r
  0x1d17: __sfputs_r
  0x1d3d: _vfprintf_r
  0x1f9d: _printf_common
  0x2079: _printf_i
  0x22c5: __sread
  0x22e7: __swrite
  0x231f: __sseek
  0x2343: __sclose
  0x2351: memchr
  0x2677: assert_crash_message
  0x26d0: uart_config
  0x26f0: mcg_mode_routing
  0x2730: spi_config
  0x274c: adc_config
  0x27ec: _global_impure_ptr
  0x27f0: __sf_fake_stderr
  0x2810: __sf_fake_stdin
  0x2830: __sf_fake_stdout
  0x2884: __preinit_array_start
  0x28f8: _sbackup_data_load
  0x40000: _ram_length
  0x100000: _fw_rom_length
  0x1fff0000: isr_stack
  0x1fff0200: _estack
  0x1fff0204: idle_name
  0x1fff0208: main_name
  0x1fff020c: _impure_ptr
  0x1fff0210: impure_data
  0x1fff0270: _tcb_name_offset
  0x1fff0271: max_threads
  0x1fff0274: _erelocate
  0x1fff0278: sched_active_pid
  0x1fff027c: sched_active_thread
  0x1fff0280: sched_context_switch_request
  0x1fff0284: sched_num_threads
  0x1fff0288: sched_runqueues
  0x1fff02c8: sched_threads
  0x1fff034c: crashed
  0x1fff0350: idle_stack
  0x1fff0450: main_stack
  0x1fff0a50: config
  0x1fff0a58: current_mode
  0x1fff0a5c: locks
  0x1fff0a60: locks
  0x1fff0a68: __malloc_free_list
  0x1fff0a6c: __malloc_sbrk_start
  0x1fff0a70: __lock___atexit_recursive_mutex
  0x1fff0a71: __lock___arc4random_mutex
  0x1fff0a72: __lock___env_recursive_mutex
  0x1fff0a73: __lock___sinit_recursive_mutex
  0x1fff0a74: __lock___malloc_recursive_mutex
  0x1fff0a75: __lock___at_quick_exit_mutex
  0x1fff0a76: __lock___dd_hash_mutex
  0x1fff0a77: __lock___tz_mutex
  0x1fff0a78: __lock___sfp_recursive_mutex
  0x1fff0a7c: __noinit_end
  0x20030000: _eheap
