interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  .stack:
    base_addr: 0x1fff0000
    permissions: rw-
    size: 0xab0
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: K64F-RIOT-TIMER.bin
    permissions: rwx
    size: 0x1293c
symbols:
  0x0: _sbackup_data
  0x10: _flashsec_length
  0x40: vector_cpu
  0x1d8: vector_padding
  0x400: _vectors_length
  0x410: _sfixed
  0x411: _init
  0x413: _fini
  0x415: _sbrk_r
  0x451: _read_r
  0x459: _write_r
  0x461: _close_r
  0x46b: _lseek_r
  0x475: _fstat_r
  0x47f: _isatty_r
  0x491: sched_run
  0x4f5: sched_set_status
  0x575: sched_switch
  0x5a5: sched_task_exit
  0x5e1: thread_stack_init
  0x649: cpu_switch_context_exit
  0x64e: unreachable325
  0x651: thread_yield_higher
  0x661: isr_pendsv
  0x67d: isr_svc
  0x681: context_restore
  0x699: hard_fault_default
  0x6ac: fix_msp
  0x6b2: test_sp
  0x6c0: use_psp
  0x6c4: out
  0x6dd: nmi_default
  0x6ed: mem_manage_default
  0x6fd: bus_fault_default
  0x70d: usage_fault_default
  0x71d: debug_mon_default
  0x72d: isr_systick
  0x73d: post_startup
  0x741: reset_handler_default
  0x7ad: hard_fault_handler
  0x935: irq_disable
  0x93d: irq_enable
  0x945: irq_restore
  0x94b: irq_is_in
  0x955: pre_startup
  0x969: isr_wdog_ewm
  0x96d: wdog_disable
  0x985: stdio_init
  0x993: stdio_read
  0x999: stdio_write
  0x9ab: pm_off
  0x9b5: board_init
  0xa19: panic_arch
  0xa1d: core_panic
  0xa61: main_trampoline
  0xa79: idle_thread
  0xa81: kernel_init
  0xad9: thread_create
  0xbcd: pm_set_lowest
  0xbd1: cpu_init
  0xbf5: uart_init
  0xcb1: uart_write
  0xcd1: isr_uart0_rx_tx
  0xd05: bit_clear8
  0xd25: kinetis_mcg_set_fll_factor
  0xd39: kinetis_mcg_enable_osc
  0xd59: kinetis_mcg_set_mode
  0xed9: kinetis_mcg_init
  0xfdd: gpio_init_port
  0x1009: gpio_init
  0x1055: gpio_set
  0x106f: periph_init
  0x1071: timerCB
  0x1075: main
  0x10b5: auto_init
  0x10b9: cortexm_init
  0x10f9: lptmr_reload
  0x1135: pit_irq_handler
  0x11a5: __NVIC_ClearPendingIRQ
  0x11c5: timer_init
  0x1321: timer_set
  0x13e9: timer_read
  0x1435: timer_start
  0x1495: timer_stop
  0x1505: isr_pit1
  0x150b: isr_pit3
  0x1511: isr_lptmr0
  0x1545: __libc_init_array
  0x158d: _malloc_r
  0x1641: iprintf
  0x1671: _puts_r
  0x174d: puts
  0x175d: __swbuf_r
  0x1801: __swsetup_r
  0x18dd: __sflush_r
  0x19e9: _fflush_r
  0x1a61: std
  0x1aa9: _cleanup_r
  0x1ab5: __sfmoreglue
  0x1ae1: __sfp_lock_acquire
  0x1aed: __sfp_lock_release
  0x1af9: __sinit_lock_acquire
  0x1b05: __sinit_lock_release
  0x1b11: __sinit
  0x1b81: __sfp
  0x1c0d: _fwalk_reent
  0x1c4b: __retarget_lock_init_recursive
  0x1c4d: __retarget_lock_acquire_recursive
  0x1c4f: __retarget_lock_release_recursive
  0x1c51: __swhatbuf_r
  0x1c99: __smakebuf_r
  0x1d19: memset
  0x1d29: __malloc_lock
  0x1d35: __malloc_unlock
  0x1d41: _free_r
  0x1ddd: __sfputc_r
  0x1e07: __sfputs_r
  0x1e2d: _vfprintf_r
  0x208d: _printf_common
  0x2169: _printf_i
  0x23b5: __sread
  0x23d7: __swrite
  0x240f: __sseek
  0x2433: __sclose
  0x2441: memchr
  0x2767: assert_crash_message
  0x27c0: uart_config
  0x27e0: mcg_mode_routing
  0x2820: lptmr_config
  0x282c: pit_config
  0x2830: _global_impure_ptr
  0x2834: __sf_fake_stderr
  0x2854: __sf_fake_stdin
  0x2874: __sf_fake_stdout
  0x28c8: __preinit_array_start
  0x293c: _sbackup_data_load
  0x40000: _ram_length
  0x100000: _fw_rom_length
  0x1fff0000: isr_stack
  0x1fff0200: _estack
  0x1fff0204: idle_name
  0x1fff0208: main_name
  0x1fff020c: _impure_ptr
  0x1fff0210: impure_data
  0x1fff0270: _tcb_name_offset
  0x1fff0271: max_threads
  0x1fff0274: _erelocate
  0x1fff0278: sched_active_pid
  0x1fff027c: sched_active_thread
  0x1fff0280: sched_context_switch_request
  0x1fff0284: sched_num_threads
  0x1fff0288: sched_runqueues
  0x1fff02c8: sched_threads
  0x1fff034c: crashed
  0x1fff0350: idle_stack
  0x1fff0450: main_stack
  0x1fff0a50: config
  0x1fff0a58: current_mode
  0x1fff0a5c: time
  0x1fff0a60: lptmr
  0x1fff0a74: pit
  0x1fff0a9c: __malloc_free_list
  0x1fff0aa0: __malloc_sbrk_start
  0x1fff0aa4: __lock___atexit_recursive_mutex
  0x1fff0aa5: __lock___arc4random_mutex
  0x1fff0aa6: __lock___env_recursive_mutex
  0x1fff0aa7: __lock___sinit_recursive_mutex
  0x1fff0aa8: __lock___malloc_recursive_mutex
  0x1fff0aa9: __lock___at_quick_exit_mutex
  0x1fff0aaa: __lock___dd_hash_mutex
  0x1fff0aab: __lock___tz_mutex
  0x1fff0aac: __lock___sfp_recursive_mutex
  0x1fff0ab0: __noinit_end
  0x20030000: _eheap
