interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: ARDUINO-F103-GPIO_INT.bin
    permissions: rwx
    size: 0x138a4
symbols:
  0x0: reent.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x800010d: __do_global_dtors_aux
  0x8000131: frame_dummy
  0x8000179: strlen
  0x8000189: _Z5blinkv
  0x800019d: setup
  0x80001d5: loop
  0x80001e9: SystemClock_Config
  0x8000289: Reset_Handler
  0x800028c: CopyDataInit
  0x8000294: LoopCopyDataInit
  0x80002a2: FillZerobss
  0x80002a8: LoopFillZerobss
  0x80002d0: Default_Handler
  0x80002d1: USB_HP_CAN1_TX_IRQHandler
  0x80002d3: init
  0x80002db: HAL_MspInit
  0x80002dd: HAL_InitTick
  0x8000329: HAL_Init
  0x800034d: HAL_IncTick
  0x8000365: HAL_GetTick
  0x8000371: HAL_NVIC_SetPriorityGrouping
  0x8000395: HAL_NVIC_SetPriority
  0x80003f9: HAL_NVIC_EnableIRQ
  0x8000415: HAL_SYSTICK_Config
  0x8000441: HAL_NVIC_ClearPendingIRQ
  0x8000461: HAL_SYSTICK_CLKSourceConfig
  0x8000481: HAL_SYSTICK_Callback
  0x8000483: HAL_SYSTICK_IRQHandler
  0x800048d: HAL_DMA_Abort_IT
  0x8000525: HAL_GPIO_Init
  0x8000711: HAL_GPIO_WritePin
  0x800071d: HAL_GPIO_EXTI_IRQHandler
  0x8000739: I2C_Master_SB
  0x80007c3: I2C_Master_ADD10
  0x80007cf: I2C_Master_ADDR
  0x80009a9: I2C_SlaveTransmit_BTF
  0x80009c9: I2C_SlaveReceive_BTF
  0x80009e9: HAL_I2C_Slave_Sequential_Transmit_IT
  0x8000a75: HAL_I2C_Slave_Sequential_Receive_IT
  0x8000b01: HAL_I2C_EnableListen_IT
  0x8000b3f: HAL_I2C_MasterTxCpltCallback
  0x8000b41: HAL_I2C_MasterRxCpltCallback
  0x8000b43: HAL_I2C_SlaveTxCpltCallback
  0x8000b45: I2C_SlaveTransmit_TXE
  0x8000b95: HAL_I2C_SlaveRxCpltCallback
  0x8000b97: I2C_SlaveReceive_RXNE
  0x8000be3: I2C_Slave_ADDR
  0x8000c0d: I2C_Slave_AF
  0x8000ca1: HAL_I2C_MemTxCpltCallback
  0x8000ca3: I2C_MasterTransmit_TXE
  0x8000ded: I2C_MasterTransmit_BTF
  0x8000e8b: HAL_I2C_MemRxCpltCallback
  0x8000e8d: I2C_MasterReceive_RXNE
  0x8000f5d: I2C_MasterReceive_BTF
  0x800105b: HAL_I2C_AbortCpltCallback
  0x800105d: I2C_ITError
  0x80011a5: I2C_Slave_STOPF
  0x80012a9: HAL_I2C_EV_IRQHandler
  0x8001411: HAL_I2C_ER_IRQHandler
  0x80014ed: I2C_DMAAbort
  0x800154d: RCC_Delay
  0x8001579: HAL_RCC_OscConfig
  0x8001959: HAL_RCC_GetSysClockFreq
  0x80019c5: HAL_RCC_ClockConfig
  0x8001b35: HAL_RCC_GetHCLKFreq
  0x8001b41: HAL_RCCEx_PeriphCLKConfig
  0x8001c55: HAL_RTC_AlarmIRQHandler
  0x8001c8d: HAL_TIM_PWM_DeInit
  0x8001cc7: HAL_TIM_IC_CaptureCallback
  0x8001cc9: HAL_TIM_PWM_PulseFinishedCallback
  0x8001ccb: HAL_TIM_TriggerCallback
  0x8001ccd: HAL_TIM_IRQHandler
  0x8001e47: TIM_CCxChannelCmd
  0x8001e65: HAL_TIM_PWM_Stop
  0x8001ec5: TIM_CCxNChannelCmd
  0x8001ee1: HAL_TIMEx_PWMN_Stop
  0x8001f2d: HAL_TIMEx_CommutationCallback
  0x8001f2f: HAL_TIMEx_BreakCallback
  0x8001f31: UART_EndRxTransfer
  0x8001f4d: UART_Transmit_IT
  0x8001fb7: HAL_UART_Transmit_IT
  0x8001fff: UART_EndTransmit_IT
  0x8002019: UART_Receive_IT
  0x80020b9: HAL_UART_IRQHandler
  0x80021d9: UART_DMAAbortOnError
  0x80021e9: HAL_UART_GetState
  0x80021f5: is_pin_configured
  0x800220b: set_pin_configured
  0x8002229: reset_pin_configured
  0x8002249: get_GPIO_Port
  0x8002285: set_GPIO_Port_Clock
  0x800232d: get_pwm_channel
  0x8002359: HAL_TIM_PWM_MspDeInit
  0x8002361: pwm_stop
  0x80023b9: noOsSystickHandler
  0x80023bb: SysTick_Handler
  0x80023cd: digital_io_init
  0x800244d: digital_io_write
  0x8002465: hw_config_init
  0x8002471: pinmap_find_peripheral
  0x800248b: pinmap_peripheral
  0x800249d: pinmap_find_pin
  0x80024b5: pinmap_pin
  0x80024c5: pinmap_find_function
  0x80024e1: pinmap_function
  0x80024f5: pin_in_pinmap
  0x8002519: HAL_RTC_AlarmAEventCallback
  0x8002531: RTC_Alarm_IRQHandler
  0x8002541: _Error_Handler
  0x8002545: SystemInit
  0x8002591: timer_disable_clock
  0x80025f5: get_timer_obj
  0x80025f9: HAL_TIM_OC_DelayElapsedCallback
  0x8002613: HAL_TIM_PeriodElapsedCallback
  0x8002621: TIM1_UP_IRQHandler
  0x8002635: TIM2_IRQHandler
  0x8002649: TIM3_IRQHandler
  0x800265d: TIM4_IRQHandler
  0x8002671: get_i2c_obj
  0x8002675: HAL_I2C_AddrCallback
  0x80026c5: HAL_I2C_ListenCpltCallback
  0x80026f5: HAL_I2C_ErrorCallback
  0x800270d: I2C1_EV_IRQHandler
  0x800271d: I2C1_ER_IRQHandler
  0x800272d: I2C2_EV_IRQHandler
  0x800273d: I2C2_ER_IRQHandler
  0x800274d: serial_tx_active
  0x8002771: uart_attach_tx_callback
  0x80027c5: uart_index
  0x80027e9: HAL_UART_RxCpltCallback
  0x800280d: HAL_UART_TxCpltCallback
  0x8002859: HAL_UART_ErrorCallback
  0x8002899: USART1_IRQHandler
  0x80028b1: USART2_IRQHandler
  0x80028c9: USART3_IRQHandler
  0x80028e1: _exit
  0x80028e5: _kill
  0x80028f5: _getpid
  0x80028f9: pinMode
  0x800298d: digitalWrite
  0x80029d5: _ZN14HardwareSerial16_tx_complete_irqEP8serial_s
  0x8002a09: _ZN14HardwareSerial9availableEv
  0x8002a1d: _ZN14HardwareSerial4peekEv
  0x8002a39: _ZN14HardwareSerial4readEv
  0x8002a61: _ZN14HardwareSerial5flushEv
  0x8002a75: _ZN14HardwareSerial5writeEh
  0x8002ac5: _Z14serialEventRunv
  0x8002af1: _ZN14HardwareSerial4initEv
  0x8002b15: _ZN14HardwareSerial5setRxEm
  0x8002b2d: _ZN14HardwareSerial5setTxEm
  0x8002b45: _ZN14HardwareSerialC1EPv
  0x8002ba1: _Z41__static_initialization_and_destruction_0ii
  0x8002bc5: _GLOBAL__sub_I_Serial2
  0x8002bd3: _ZNK9IPAddress7printToER5Print
  0x8002c0d: _ZN9IPAddressC1Ehhhh
  0x8002c29: _Z41__static_initialization_and_destruction_0ii
  0x8002c55: _GLOBAL__sub_I__ZN9IPAddressC2Ev
  0x8002c63: _ZN5Print5writeEPKhj
  0x8002c87: _ZN5Print5printEc
  0x8002c91: _ZN5Print11printNumberEmh
  0x8002ceb: _ZN5Print5printEmi
  0x8002d01: _ZN5Print5printEhi
  0x8002d09: _ZNSt17_Function_handlerIFvvEPS0_E9_M_invokeERKSt9_Any_data
  0x8002d11: _ZNSt14_Function_base13_Base_managerIPFvvEE10_M_managerERSt9_Any_dataRKS4_St18_Manager_operation
  0x8002d2b: _ZNSt8functionIFvvEEC2ERKS1_
  0x8002d49: _Z15attachInterruptmSt8functionIFvvEEm
  0x8002e19: _ZNSt8functionIFvvEEC2IPS0_vvEET_
  0x8002e35: _Z15attachInterruptmPFvvEm
  0x8002e71: _Z11initVariantv
  0x8002e73: _Z7premainv
  0x8002e81: main
  0x8002ea1: _ZL10get_pin_idt
  0x8002eb5: __tcf_0
  0x8002edd: _Z41__static_initialization_and_destruction_0ii
  0x8002f89: EXTI0_IRQHandler
  0x8002f93: EXTI1_IRQHandler
  0x8002f9d: EXTI2_IRQHandler
  0x8002fa7: EXTI3_IRQHandler
  0x8002fb1: EXTI4_IRQHandler
  0x8002fbb: EXTI9_5_IRQHandler
  0x8002fd1: EXTI15_10_IRQHandler
  0x8002fe9: _Z22stm32_interrupt_enableP12GPIO_TypeDeftSt8functionIFvvEEm
  0x80030ed: _ZNKSt8functionIFvvEEclEv
  0x80030fd: HAL_GPIO_EXTI_Callback
  0x800311d: _GLOBAL__sub_I__Z22stm32_interrupt_enableP12GPIO_TypeDeftSt8functionIFvvEEm
  0x800312b: __aeabi_atexit
  0x8003135: __cxa_atexit
  0x8003151: __libc_init_array
  0x8003199: abort
  0x80031a7: _raise_r
  0x80031f9: raise
  0x8003209: _kill_r
  0x800322d: _getpid_r
  0x8003231: _ZSt25__throw_bad_function_callv
  0x8003239: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKSsj
  0x80032fd: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKSsj
  0x80033c1: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x8003445: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x80034c8: __EH_FRAME_BEGIN__
  0x80034c9: _init
  0x80034d5: _fini
  0x80034e0: _etext
  0x80034f4: PinMap_PWM
  0x8003644: PinMap_UART_RX
  0x800368c: PinMap_UART_TX
  0x8003730: digitalPin
  0x800376c: AHBPrescTable
  0x800377c: _ZTV14HardwareSerial
  0x800379c: _ZTV9IPAddress
  0x80037a8: __sf_fake_stderr
  0x80037c8: __sf_fake_stdin
  0x80037e8: __sf_fake_stdout
  0x8003808: __exidx_end
  0x800380c: __frame_dummy_init_array_entry
  0x800382c: __init_array_end
  0x8003830: _sidata
  0x20000000: __dso_handle
  0x20000004: uwTickFreq
  0x20000008: uwTickPrio
  0x2000000c: SystemCoreClock
  0x20000010: _impure_ptr
  0x20000014: impure_data
  0x20000074: _edata
  0x20000078: object.8672
  0x20000090: state
  0x20000094: RTCUserCallback
  0x20000098: RtcHandle
  0x200000ac: callbackUserData
  0x200000b0: timer_handles
  0x20000108: i2c_handles
  0x20000110: rx_callback
  0x20000124: rx_callback_obj
  0x20000138: tx_callback
  0x2000014c: tx_callback_obj
  0x20000160: uart_handlers
  0x20000174: g_anOutputPinConfigured
  0x20000188: g_digPinConfigured
  0x2000019c: Serial2
  0x200002e0: _ZL11INADDR_NONE
  0x200002e8: _ZL13gpio_irq_conf
  0x20000428: _ZGVNSt7collateIcE2idE
  0x2000042c: _ZGVNSt8messagesIcE2idE
  0x20000430: _ZGVNSt8time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000434: _ZGVNSt8time_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000438: _ZGVNSt11__timepunctIcE2idE
  0x2000043c: _ZGVNSt7num_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000440: _ZGVNSt7num_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000444: _ZGVNSt8numpunctIcE2idE
  0x20000448: _ZGVNSt9money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x2000044c: _ZGVNSt9money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000450: _ZGVNSt10moneypunctIcLb1EE2idE
  0x20000454: _ZGVNSt10moneypunctIcLb0EE2idE
  0x20000458: _ZGVNSt7collateIwE2idE
  0x2000045c: _ZGVNSt8messagesIwE2idE
  0x20000460: _ZGVNSt8time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000464: _ZGVNSt8time_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000468: _ZGVNSt11__timepunctIwE2idE
  0x2000046c: _ZGVNSt7num_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000470: _ZGVNSt7num_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000474: _ZGVNSt8numpunctIwE2idE
  0x20000478: _ZGVNSt9money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x2000047c: _ZGVNSt9money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000480: _ZGVNSt10moneypunctIwLb1EE2idE
  0x20000484: _ZGVNSt10moneypunctIwLb0EE2idE
  0x20000488: _ZGVNSt7__cxx117collateIwE2idE
  0x2000048c: _ZGVNSt7__cxx118messagesIwE2idE
  0x20000490: _ZGVNSt7__cxx118time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000494: _ZGVNSt7__cxx118numpunctIwE2idE
  0x20000498: _ZGVNSt7__cxx119money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x2000049c: _ZGVNSt7__cxx119money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004a0: _ZGVNSt7__cxx1110moneypunctIwLb1EE2idE
  0x200004a4: _ZGVNSt7__cxx1110moneypunctIwLb0EE2idE
  0x200004a8: _ZGVNSt7__cxx117collateIcE2idE
  0x200004ac: _ZGVNSt7__cxx118messagesIcE2idE
  0x200004b0: _ZGVNSt7__cxx118time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200004b4: _ZGVNSt7__cxx118numpunctIcE2idE
  0x200004b8: _ZGVNSt7__cxx119money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200004bc: _ZGVNSt7__cxx119money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200004c0: _ZGVNSt7__cxx1110moneypunctIcLb1EE2idE
  0x200004c4: _ZGVNSt7__cxx1110moneypunctIcLb0EE2idE
  0x200004c8: uwTick
  0x200004cc: errno
  0x200004d0: _end
  0x20005000: _estack
  0xf108f85f: BootRAM
