interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: ARDUINO-SAM3-I2C.bin
    permissions: rwx
    size: 0x15b00
symbols:
  0x0: __register_frame_info
  0x80000: exception_table
  0x800f5: __do_global_dtors_aux
  0x80119: frame_dummy
  0x80149: setup
  0x80155: loop
  0x801c1: _ZN7TwoWire5writeEPKhj
  0x80211: _ZN7TwoWire9availableEv
  0x8021d: _ZN7TwoWire4readEv
  0x8023b: _ZN7TwoWire4peekEv
  0x80251: _ZN7TwoWire5flushEv
  0x80253: _ZN7TwoWire5writeEh
  0x8028d: _ZL16TWI_WaitByteSentP3Twim.constprop.3
  0x802b9: _ZL24TWI_WaitTransferCompleteP3Twim.constprop.4
  0x802e5: _ZL9Wire_Initv
  0x80339: _ZL12Wire1_Deinitv
  0x80351: _ZL11Wire_Deinitv
  0x80369: _ZL10Wire1_Initv
  0x803bd: _ZN7TwoWireC2EP3TwiPFvvES3_
  0x80405: _ZN7TwoWire5beginEv
  0x80435: _ZN7TwoWire11requestFromEhhmhh
  0x804ad: _ZN7TwoWire11requestFromEhhh
  0x804bf: _ZN7TwoWire11requestFromEii
  0x804c9: _ZN7TwoWire17beginTransmissionEi
  0x804db: _ZN7TwoWire15endTransmissionEh
  0x8055d: _ZN7TwoWire15endTransmissionEv
  0x80563: _ZN7TwoWire9onServiceEv
  0x8067d: TWI1_Handler
  0x80689: TWI0_Handler
  0x80695: _GLOBAL__sub_I__ZN7TwoWireC2EP3TwiPFvvES3_
  0x806d5: _Z11serialEventv
  0x806d9: UART_Handler
  0x806e5: _Z12serialEvent1v
  0x806e7: _Z12serialEvent2v
  0x806e9: _Z12serialEvent3v
  0x806ed: USART0_Handler
  0x806f9: USART1_Handler
  0x80705: USART3_Handler
  0x80711: init
  0x80839: _GLOBAL__sub_I_g_APinDescription
  0x8090d: _Z14serialEventRunv
  0x80951: PIO_PullUp
  0x8095b: PIO_SetPeripheral
  0x80981: PIO_SetInput
  0x809a7: PIO_SetOutput
  0x809cd: PIO_Configure
  0x80a31: PIO_GetOutputDataStatus
  0x80a45: pmc_enable_periph_clk
  0x80a89: pmc_disable_periph_clk
  0x80ac9: TWI_SetClock
  0x80b21: TWI_Disable
  0x80b4d: TWI_ConfigureMaster
  0x80b95: TWI_Stop
  0x80bbd: TWI_StartRead
  0x80c2d: TWI_ReadByte
  0x80c55: TWI_WriteByte
  0x80c79: TWI_StartWrite
  0x80cf5: TWI_EnableIt
  0x80d35: TWI_DisableIt
  0x80d75: TWI_GetStatus
  0x80d9d: TWI_SendSTOPCondition
  0x80dc9: SystemInit
  0x80e51: Reset_Handler
  0x80ec9: adc_init
  0x80f61: adc_configure_trigger
  0x80f6f: adc_configure_timing
  0x80f89: adc_disable_channel
  0x80f93: adc_disable_all_channel
  0x80f9b: adc_disable_interrupt
  0x80fa1: UOTGHS_Handler
  0x80fb1: PIOA_Handler
  0x80fe9: PIOB_Handler
  0x81021: PIOC_Handler
  0x81059: PIOD_Handler
  0x81091: SPI0_Handler
  0x81093: SVC_Handler
  0x81097: PendSV_Handler
  0x8109b: SysTick_Handler
  0x810b1: sysTickHook
  0x810b5: svcHook
  0x810b9: _sbrk
  0x810d5: link
  0x810db: _close
  0x810e1: _fstat
  0x810eb: _isatty
  0x810ef: _lseek
  0x810f3: _read
  0x810f9: _write
  0x8111d: _exit
  0x8112d: _kill
  0x8112f: _getpid
  0x81135: analogOutputInit
  0x81139: pinMode
  0x81241: digitalWrite
  0x812b1: _ZN5Print5writeEPKhj
  0x812d5: tickReset
  0x812f5: _ZN10RingBufferC2Ev
  0x8130f: _ZN10RingBuffer10store_charEh
  0x8132d: _ZN9UARTClasscvbEv
  0x81331: _ZN9UARTClass9availableEv
  0x81343: _ZN9UARTClass4peekEv
  0x8135f: _ZN9UARTClass4readEv
  0x81389: _ZN9UARTClass5flushEv
  0x813a1: _ZN9UARTClass5writeEh
  0x813f5: _ZN9UARTClass3endEv
  0x81431: _ZN9UARTClassC2EP4Uart4IRQnmP10RingBufferS4_
  0x81455: _ZN9UARTClass4initEmm
  0x814c5: _ZN9UARTClass5beginEm
  0x814cd: _ZN9UARTClass10IrqHandlerEv
  0x81517: _ZN10USARTClass5beginEm
  0x81521: _ZN10USARTClassC2EP5Usart4IRQnmP10RingBufferS4_
  0x81545: initVariant
  0x81549: main
  0x81575: _watchdogDefaultSetup
  0x81581: delay
  0x81585: TimeTick_Increment
  0x81595: WDT_Disable
  0x8159d: __assert_func
  0x815d9: fiprintf
  0x81601: __libc_init_array
  0x81651: iprintf
  0x81679: memset
  0x8170d: strlen
  0x8176d: kill
  0x8177d: __sprint_r.part.0
  0x817f5: _vfiprintf_r
  0x82449: __sbprintf
  0x824c5: __swsetup_r
  0x82589: register_fini
  0x8259d: abort
  0x825ad: atexit
  0x825b9: __sflush_r
  0x82701: _fflush_r
  0x8272d: _cleanup_r
  0x82739: __sinit
  0x8282d: __sfp_lock_acquire
  0x82831: __sfp_lock_release
  0x82835: __libc_fini_array
  0x82865: _fputwc_r
  0x82925: _malloc_trim_r
  0x829c1: _free_r
  0x82b59: __sfvwrite_r
  0x82e6d: _fwalk
  0x82eb5: __locale_charset
  0x82ebd: __locale_mb_cur_max
  0x82ec9: __smakebuf_r
  0x82fa9: _malloc_r
  0x834e1: memchr
  0x83575: memcpy
  0x83661: memmove
  0x8372d: __malloc_lock
  0x83731: __malloc_unlock
  0x83735: _realloc_r
  0x83af5: _sbrk_r
  0x83b19: _raise_r
  0x83b71: raise
  0x83b81: _kill_r
  0x83ba9: _getpid_r
  0x83bad: __sread
  0x83bd1: __swrite
  0x83c09: __sseek
  0x83c29: __sclose
  0x83c31: __swbuf_r
  0x83cd9: _wcrtomb_r
  0x83d29: __ascii_wctomb
  0x83d45: _write_r
  0x83d6d: __register_exitproc
  0x83e15: _close_r
  0x83e39: _fclose_r
  0x83eb9: fclose
  0x83ec9: _fstat_r
  0x83ef1: _isatty_r
  0x83f15: _lseek_r
  0x83f3d: _read_r
  0x83f65: __aeabi_uldivmod
  0x83f91: __gnu_ldivmod_helper
  0x83fc1: __gnu_uldivmod_helper
  0x83ff1: __aeabi_idiv0
  0x83ff5: __divdi3
  0x84295: __udivdi3
  0x84528: _ZTV7TwoWire
  0x84548: g_APinDescription
  0x84f74: __func__.7227
  0x84f82: __func__.7157
  0x84f8f: __func__.7208
  0x84f9e: __func__.7176
  0x8505e: __func__.7184
  0x85067: __func__.7240
  0x8507d: __func__.7191
  0x8508b: __func__.7231
  0x85099: __func__.7195
  0x850a6: __func__.7222
  0x850b3: __func__.7200
  0x850c1: __func__.7151
  0x85138: _ZTV9UARTClass
  0x85168: _ZTV10USARTClass
  0x851dc: _global_impure_ptr
  0x851e0: blanks.6717
  0x85220: zeroes.6718
  0x85231: _init
  0x8523c: __preinit_array_start
  0x85240: __frame_dummy_init_array_entry
  0x8524c: __init_array_end
  0x8524d: _fini
  0x85258: __fini_array_start
  0x8525c: _efixed
  0x85264: _etext
  0x20070000: _srelocate
  0x20070001: banzai
  0x2007002c: SystemCoreClock
  0x20070030: _ZL5ticks
  0x20070038: impure_data
  0x20070460: _impure_ptr
  0x20070464: lc_ctype_charset
  0x20070484: __mb_cur_max
  0x20070488: __malloc_av_
  0x20070890: __malloc_trim_threshold
  0x20070894: __malloc_sbrk_base
  0x20070898: __wctomb
  0x2007089c: _erelocate
  0x200708a0: object.7862
  0x200708b8: reading
  0x200708bc: Wire1
  0x20070950: Wire
  0x200709e4: tx_buffer2
  0x20070a6c: tx_buffer1
  0x20070af4: Serial
  0x20070b18: rx_buffer1
  0x20070ba0: Serial1
  0x20070bc8: Serial2
  0x20070bf0: Serial3
  0x20070c18: tx_buffer3
  0x20070ca0: tx_buffer4
  0x20070d28: g_pinStatus
  0x20070d78: rx_buffer2
  0x20070e00: rx_buffer3
  0x20070e88: rx_buffer4
  0x20070f10: gpf_isr
  0x20070f14: callbacksPioA
  0x20070f94: callbacksPioB
  0x20071014: callbacksPioC
  0x20071094: callbacksPioD
  0x20071114: heap.6420
  0x20071118: _dwTickCount
  0x2007111c: __malloc_max_total_mem
  0x20071120: __malloc_max_sbrked_mem
  0x20071124: __malloc_top_pad
  0x20071128: __malloc_current_mallinfo
  0x20071150: errno
  0x20071154: _end
  0x20088000: _estack
