interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: ARDUINO-F103-ADC.bin
    permissions: rwx
    size: 0x16430
symbols:
  0x0: reent.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x800010d: __do_global_dtors_aux
  0x8000131: frame_dummy
  0x8000179: strlen
  0x8000189: __aeabi_drsub
  0x8000191: __subdf3
  0x8000195: __aeabi_dadd
  0x800040d: __floatunsidf
  0x800042d: __floatsidf
  0x8000451: __aeabi_f2d
  0x800048d: __floatundidf
  0x800049d: __aeabi_l2d
  0x80004f9: __muldf3
  0x800074d: __divdf3
  0x800091d: __gedf2
  0x8000925: __ledf2
  0x800092d: __eqdf2
  0x80009a9: __aeabi_cdrcmple
  0x80009b9: __aeabi_cdcmpeq
  0x80009c9: __aeabi_dcmpeq
  0x80009dd: __aeabi_dcmplt
  0x80009f1: __aeabi_dcmple
  0x8000a05: __aeabi_dcmpge
  0x8000a19: __aeabi_dcmpgt
  0x8000a2d: __unorddf2
  0x8000a59: __fixdfsi
  0x8000aa9: __fixunsdfsi
  0x8000ae9: __truncdfsf2
  0x8000b89: setup
  0x8000ba1: loop
  0x8000be5: SystemClock_Config
  0x8000c85: Reset_Handler
  0x8000c88: CopyDataInit
  0x8000c90: LoopCopyDataInit
  0x8000c9e: FillZerobss
  0x8000ca4: LoopFillZerobss
  0x8000ccc: Default_Handler
  0x8000ccd: USB_HP_CAN1_TX_IRQHandler
  0x8000ccf: init
  0x8000cd7: HAL_MspInit
  0x8000cd9: HAL_InitTick
  0x8000d25: HAL_Init
  0x8000d49: HAL_IncTick
  0x8000d61: HAL_GetTick
  0x8000d6d: HAL_ADC_PollForConversion
  0x8000edd: HAL_ADC_GetValue
  0x8000ee5: HAL_ADC_ConfigChannel
  0x800101d: HAL_ADC_GetState
  0x8001021: ADC_Enable
  0x80010a1: HAL_ADC_Start
  0x800118d: ADC_ConversionStop_Disable
  0x80011d9: HAL_ADC_Init
  0x80012e9: HAL_ADC_DeInit
  0x80013e5: HAL_ADC_Stop
  0x8001421: HAL_ADCEx_Calibration_Start
  0x800150d: HAL_NVIC_SetPriorityGrouping
  0x8001531: HAL_NVIC_SetPriority
  0x8001595: HAL_NVIC_EnableIRQ
  0x80015b1: HAL_SYSTICK_Config
  0x80015dd: HAL_NVIC_ClearPendingIRQ
  0x80015fd: HAL_SYSTICK_CLKSourceConfig
  0x800161d: HAL_SYSTICK_Callback
  0x800161f: HAL_SYSTICK_IRQHandler
  0x8001629: HAL_DMA_Abort_IT
  0x80016c1: HAL_GPIO_Init
  0x80018ad: HAL_GPIO_EXTI_IRQHandler
  0x80018c9: I2C_Master_SB
  0x8001953: I2C_Master_ADD10
  0x800195f: I2C_Master_ADDR
  0x8001b39: I2C_SlaveTransmit_BTF
  0x8001b59: I2C_SlaveReceive_BTF
  0x8001b79: HAL_I2C_Slave_Sequential_Transmit_IT
  0x8001c05: HAL_I2C_Slave_Sequential_Receive_IT
  0x8001c91: HAL_I2C_EnableListen_IT
  0x8001ccf: HAL_I2C_MasterTxCpltCallback
  0x8001cd1: HAL_I2C_MasterRxCpltCallback
  0x8001cd3: HAL_I2C_SlaveTxCpltCallback
  0x8001cd5: I2C_SlaveTransmit_TXE
  0x8001d25: HAL_I2C_SlaveRxCpltCallback
  0x8001d27: I2C_SlaveReceive_RXNE
  0x8001d73: I2C_Slave_ADDR
  0x8001d9d: I2C_Slave_AF
  0x8001e31: HAL_I2C_MemTxCpltCallback
  0x8001e33: I2C_MasterTransmit_TXE
  0x8001f7d: I2C_MasterTransmit_BTF
  0x800201b: HAL_I2C_MemRxCpltCallback
  0x800201d: I2C_MasterReceive_RXNE
  0x80020ed: I2C_MasterReceive_BTF
  0x80021eb: HAL_I2C_AbortCpltCallback
  0x80021ed: I2C_ITError
  0x8002335: I2C_Slave_STOPF
  0x8002439: HAL_I2C_EV_IRQHandler
  0x80025a1: HAL_I2C_ER_IRQHandler
  0x800267d: I2C_DMAAbort
  0x80026dd: RCC_Delay
  0x8002709: HAL_RCC_OscConfig
  0x8002ae9: HAL_RCC_GetSysClockFreq
  0x8002b55: HAL_RCC_ClockConfig
  0x8002cc5: HAL_RCC_GetHCLKFreq
  0x8002cd1: HAL_RCC_GetPCLK1Freq
  0x8002cf1: HAL_RCC_GetPCLK2Freq
  0x8002d11: HAL_RCCEx_PeriphCLKConfig
  0x8002e25: HAL_RCCEx_GetPeriphCLKFreq
  0x8002f21: HAL_RTC_AlarmIRQHandler
  0x8002f59: HAL_TIM_IC_CaptureCallback
  0x8002f5b: HAL_TIM_PWM_PulseFinishedCallback
  0x8002f5d: HAL_TIM_TriggerCallback
  0x8002f5f: HAL_TIM_IRQHandler
  0x80030d9: HAL_TIMEx_CommutationCallback
  0x80030db: HAL_TIMEx_BreakCallback
  0x80030dd: UART_EndRxTransfer
  0x80030f9: UART_Transmit_IT
  0x8003165: UART_SetConfig
  0x8003315: UART_WaitOnFlagUntilTimeout
  0x8003379: HAL_UART_MspInit
  0x800337b: HAL_UART_Init
  0x80033d9: HAL_UART_Transmit
  0x80034bb: HAL_UART_Transmit_IT
  0x8003503: HAL_UART_Receive_IT
  0x800355f: UART_EndTransmit_IT
  0x8003579: UART_Receive_IT
  0x8003619: HAL_UART_IRQHandler
  0x8003739: UART_DMAAbortOnError
  0x8003749: HAL_UART_GetState
  0x8003755: set_GPIO_Port_Clock
  0x80037fd: get_adc_channel
  0x8003819: HAL_ADC_MspInit
  0x8003895: HAL_ADC_MspDeInit
  0x80038f1: adc_read_value
  0x80039d9: noOsSystickHandler
  0x80039db: SysTick_Handler
  0x80039eb: hw_config_init
  0x80039f7: pinmap_find_peripheral
  0x8003a11: pinmap_peripheral
  0x8003a23: pinmap_find_pin
  0x8003a3b: pinmap_pin
  0x8003a4b: pinmap_find_function
  0x8003a67: pinmap_function
  0x8003a7b: pinmap_merge_peripheral
  0x8003a8d: HAL_RTC_AlarmAEventCallback
  0x8003aa5: RTC_Alarm_IRQHandler
  0x8003ab5: _Error_Handler
  0x8003ab9: SystemInit
  0x8003b05: get_timer_obj
  0x8003b09: HAL_TIM_OC_DelayElapsedCallback
  0x8003b23: HAL_TIM_PeriodElapsedCallback
  0x8003b31: TIM1_UP_IRQHandler
  0x8003b45: TIM2_IRQHandler
  0x8003b59: TIM3_IRQHandler
  0x8003b6d: TIM4_IRQHandler
  0x8003b81: get_i2c_obj
  0x8003b85: HAL_I2C_AddrCallback
  0x8003bd5: HAL_I2C_ListenCpltCallback
  0x8003c05: HAL_I2C_ErrorCallback
  0x8003c1d: I2C1_EV_IRQHandler
  0x8003c2d: I2C1_ER_IRQHandler
  0x8003c3d: I2C2_EV_IRQHandler
  0x8003c4d: I2C2_ER_IRQHandler
  0x8003c5d: uart_init
  0x8004095: uart_debug_init
  0x80040e5: uart_debug_write
  0x800419d: serial_rx_active
  0x80041c1: serial_tx_active
  0x80041e5: uart_getc
  0x8004221: uart_attach_rx_callback
  0x8004279: uart_attach_tx_callback
  0x80042cd: uart_index
  0x80042f1: HAL_UART_RxCpltCallback
  0x8004315: HAL_UART_TxCpltCallback
  0x8004361: HAL_UART_ErrorCallback
  0x80043a1: USART1_IRQHandler
  0x80043b9: USART2_IRQHandler
  0x80043d1: USART3_IRQHandler
  0x80043e9: _sbrk
  0x8004425: _close
  0x800442b: _fstat
  0x8004435: _isatty
  0x8004439: _lseek
  0x800443d: _read
  0x8004441: _write
  0x800444d: _exit
  0x8004451: _kill
  0x8004461: _getpid
  0x8004465: analogRead
  0x80044c5: _ZN14HardwareSerial16_tx_complete_irqEP8serial_s
  0x80044f9: _ZN14HardwareSerial9availableEv
  0x800450d: _ZN14HardwareSerial4peekEv
  0x8004529: _ZN14HardwareSerial4readEv
  0x8004551: _ZN14HardwareSerial5flushEv
  0x8004565: _ZN14HardwareSerial16_rx_complete_irqEP8serial_s
  0x80045a1: _ZN14HardwareSerial5writeEh
  0x80045f1: _Z14serialEventRunv
  0x800461d: _ZN14HardwareSerial4initEv
  0x8004641: _ZN14HardwareSerial5beginEmh
  0x80046fd: _ZN14HardwareSerial5setRxEm
  0x8004715: _ZN14HardwareSerial5setTxEm
  0x800472d: _ZN14HardwareSerialC1EPv
  0x8004789: _Z41__static_initialization_and_destruction_0ii
  0x80047ad: _GLOBAL__sub_I_Serial2
  0x80047bb: _ZNK9IPAddress7printToER5Print
  0x80047f5: _ZN9IPAddressC1Ehhhh
  0x8004811: _Z41__static_initialization_and_destruction_0ii
  0x800483d: _GLOBAL__sub_I__ZN9IPAddressC2Ev
  0x800484b: _ZN5Print5writeEPKhj
  0x800486f: _ZN5Print5printEPKc
  0x800488f: _ZN5Print5printEc
  0x8004899: _ZN5Print7printlnEv
  0x80048ad: _ZN5Print11printNumberEmh
  0x8004907: _ZN5Print5printEli
  0x8004947: _ZN5Print5printEii
  0x800494f: _ZN5Print5printEmi
  0x8004965: _ZN5Print5printEhi
  0x800496d: _ZN5Print10printFloatEdh
  0x8004af1: _ZN5Print5printEdi
  0x8004b05: _ZN5Print7printlnEdi
  0x8004b21: _Z11initVariantv
  0x8004b23: _Z7premainv
  0x8004b31: main
  0x8004b51: _ZL10get_pin_idt
  0x8004b65: __tcf_0
  0x8004b8d: _Z41__static_initialization_and_destruction_0ii
  0x8004c39: EXTI0_IRQHandler
  0x8004c43: EXTI1_IRQHandler
  0x8004c4d: EXTI2_IRQHandler
  0x8004c57: EXTI3_IRQHandler
  0x8004c61: EXTI4_IRQHandler
  0x8004c6b: EXTI9_5_IRQHandler
  0x8004c81: EXTI15_10_IRQHandler
  0x8004c99: _ZNKSt8functionIFvvEEclEv
  0x8004ca9: HAL_GPIO_EXTI_Callback
  0x8004cc9: _GLOBAL__sub_I__Z22stm32_interrupt_enableP12GPIO_TypeDeftSt8functionIFvvEEm
  0x8004cd7: __aeabi_atexit
  0x8004ce1: __assert_func
  0x8004d1d: __cxa_atexit
  0x8004d39: fiprintf
  0x8004d5d: __libc_init_array
  0x8004da5: memset
  0x8004db5: _free_r
  0x8004e4d: _malloc_r
  0x8004f09: __sfputc_r
  0x8004f35: __sfputs_r
  0x8004f59: _vfiprintf_r
  0x8005185: _printf_common
  0x8005275: _printf_i
  0x80054b5: iprintf
  0x80054e5: _sbrk_r
  0x8005505: __swbuf_r
  0x80055a9: __swsetup_r
  0x8005685: abort
  0x8005695: __sflush_r
  0x80057a5: _fflush_r
  0x80057f9: _cleanup_r
  0x8005805: std.isra.0
  0x800584d: __sfmoreglue
  0x8005879: __sinit
  0x80058d9: __sfp
  0x8005951: _fwalk_reent
  0x800598d: __swhatbuf_r
  0x80059d5: __smakebuf_r
  0x8005a55: memchr
  0x8005a71: __malloc_lock
  0x8005a73: __malloc_unlock
  0x8005a75: _raise_r
  0x8005ac5: raise
  0x8005ad5: _kill_r
  0x8005af9: _getpid_r
  0x8005afd: __sread
  0x8005b1f: __swrite
  0x8005b57: __sseek
  0x8005b7b: __sclose
  0x8005b85: _write_r
  0x8005ba9: _close_r
  0x8005bc9: _fstat_r
  0x8005bed: _isatty_r
  0x8005c0d: _lseek_r
  0x8005c31: _read_r
  0x8005c55: _ZSt25__throw_bad_function_callv
  0x8005c5d: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKSsj
  0x8005d21: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKSsj
  0x8005de5: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x8005e69: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x8005eec: __EH_FRAME_BEGIN__
  0x8005eed: _init
  0x8005ef9: _fini
  0x8005f04: _etext
  0x8005f2c: PinMap_ADC
  0x8005fe0: PinMap_UART_RX
  0x8006028: PinMap_UART_TX
  0x80060cc: digitalPin
  0x8006108: AHBPrescTable
  0x8006118: APBPrescTable
  0x80061d8: _ZTV14HardwareSerial
  0x80061f8: _ZZN14HardwareSerial5beginEmhE19__PRETTY_FUNCTION__
  0x800622c: _ZTV9IPAddress
  0x8006288: _global_impure_ptr
  0x80062c0: __sf_fake_stderr
  0x80062e0: __sf_fake_stdin
  0x8006300: __sf_fake_stdout
  0x8006320: __exidx_end
  0x8006324: __frame_dummy_init_array_entry
  0x8006344: __init_array_end
  0x8006348: _sidata
  0x20000000: __dso_handle
  0x20000004: uwTickFreq
  0x20000008: uwTickPrio
  0x2000000c: g_current_pin
  0x20000010: SystemCoreClock
  0x20000014: serial_debug
  0x20000080: _readResolution
  0x20000084: _impure_ptr
  0x20000088: impure_data
  0x200000e8: _edata
  0x200000ec: object.8672
  0x20000104: RTCUserCallback
  0x20000108: RtcHandle
  0x2000011c: callbackUserData
  0x20000120: timer_handles
  0x20000178: i2c_handles
  0x20000180: rx_callback
  0x20000194: rx_callback_obj
  0x200001a8: tx_callback
  0x200001bc: tx_callback_obj
  0x200001d0: uart_handlers
  0x200001e4: heap_end.4572
  0x200001e8: Serial2
  0x2000032c: _ZL11INADDR_NONE
  0x20000334: _ZL13gpio_irq_conf
  0x20000474: __malloc_free_list
  0x20000478: __malloc_sbrk_start
  0x2000047c: _ZGVNSt7collateIcE2idE
  0x20000480: _ZGVNSt8messagesIcE2idE
  0x20000484: _ZGVNSt8time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000488: _ZGVNSt8time_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x2000048c: _ZGVNSt11__timepunctIcE2idE
  0x20000490: _ZGVNSt7num_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000494: _ZGVNSt7num_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000498: _ZGVNSt8numpunctIcE2idE
  0x2000049c: _ZGVNSt9money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200004a0: _ZGVNSt9money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200004a4: _ZGVNSt10moneypunctIcLb1EE2idE
  0x200004a8: _ZGVNSt10moneypunctIcLb0EE2idE
  0x200004ac: _ZGVNSt7collateIwE2idE
  0x200004b0: _ZGVNSt8messagesIwE2idE
  0x200004b4: _ZGVNSt8time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004b8: _ZGVNSt8time_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004bc: _ZGVNSt11__timepunctIwE2idE
  0x200004c0: _ZGVNSt7num_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004c4: _ZGVNSt7num_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004c8: _ZGVNSt8numpunctIwE2idE
  0x200004cc: _ZGVNSt9money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004d0: _ZGVNSt9money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004d4: _ZGVNSt10moneypunctIwLb1EE2idE
  0x200004d8: _ZGVNSt10moneypunctIwLb0EE2idE
  0x200004dc: _ZGVNSt7__cxx117collateIwE2idE
  0x200004e0: _ZGVNSt7__cxx118messagesIwE2idE
  0x200004e4: _ZGVNSt7__cxx118time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004e8: _ZGVNSt7__cxx118numpunctIwE2idE
  0x200004ec: _ZGVNSt7__cxx119money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004f0: _ZGVNSt7__cxx119money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004f4: _ZGVNSt7__cxx1110moneypunctIwLb1EE2idE
  0x200004f8: _ZGVNSt7__cxx1110moneypunctIwLb0EE2idE
  0x200004fc: _ZGVNSt7__cxx117collateIcE2idE
  0x20000500: _ZGVNSt7__cxx118messagesIcE2idE
  0x20000504: _ZGVNSt7__cxx118time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000508: _ZGVNSt7__cxx118numpunctIcE2idE
  0x2000050c: _ZGVNSt7__cxx119money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000510: _ZGVNSt7__cxx119money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000514: _ZGVNSt7__cxx1110moneypunctIcLb1EE2idE
  0x20000518: _ZGVNSt7__cxx1110moneypunctIcLb0EE2idE
  0x2000051c: uwTick
  0x20000520: errno
  0x20000524: _end
  0x20005000: _estack
  0xf108f85f: BootRAM
