#include:
#  - ./syms.yml

interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin

memory_map:
  mmio: {base_addr:  0x40000000, size: 0x20000000, permissions: rw-}
  nvic: {base_addr:  0xe0000000, size: 0x10000000, permissions: rw-}
  irq_ret: {base_addr: 0xfffff000, size: 0x1000, permissions: --x}

  ram:
    base_addr: 0x20070000
    permissions: rw-
    size: 0x40000
  text:
    base_addr: 0x00080000
    file: Heat_Press.bin
    permissions: r-x
    size: 0x7000
