interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: ARDUINO-SAM3-ADC.bin
    permissions: rwx
    size: 0x15cb4
symbols:
  0x0: __register_frame_info
  0x80000: exception_table
  0x800f5: __do_global_dtors_aux
  0x80119: frame_dummy
  0x80149: loop
  0x80191: setup
  0x801a1: _Z11serialEventv
  0x801a5: UART_Handler
  0x801b1: _Z12serialEvent1v
  0x801b3: _Z12serialEvent2v
  0x801b5: _Z12serialEvent3v
  0x801b9: USART0_Handler
  0x801c5: USART1_Handler
  0x801d1: USART3_Handler
  0x801dd: init
  0x80305: _GLOBAL__sub_I_g_APinDescription
  0x803d9: _Z14serialEventRunv
  0x8041d: PIO_PullUp
  0x80427: PIO_SetPeripheral
  0x8044d: PIO_SetInput
  0x80473: PIO_SetOutput
  0x80499: PIO_Configure
  0x804fd: PIO_GetOutputDataStatus
  0x80511: pmc_enable_periph_clk
  0x80555: pmc_disable_periph_clk
  0x80595: SystemInit
  0x8061d: Reset_Handler
  0x80695: adc_init
  0x8072d: adc_configure_trigger
  0x8073b: adc_configure_timing
  0x80755: adc_start
  0x8075b: adc_enable_channel
  0x80765: adc_disable_channel
  0x8076f: adc_disable_all_channel
  0x80777: adc_get_channel_status
  0x80781: adc_get_latest_value
  0x80785: adc_disable_interrupt
  0x80789: adc_get_status
  0x8078d: UOTGHS_Handler
  0x8079d: PIOA_Handler
  0x807d5: PIOB_Handler
  0x8080d: PIOC_Handler
  0x80845: PIOD_Handler
  0x8087d: SPI0_Handler
  0x8087f: SVC_Handler
  0x80883: PendSV_Handler
  0x80887: SysTick_Handler
  0x8089d: sysTickHook
  0x808a1: svcHook
  0x808a5: _sbrk
  0x808c1: link
  0x808c7: _close
  0x808cd: _fstat
  0x808d7: _isatty
  0x808db: _lseek
  0x808df: _read
  0x808e5: _write
  0x80909: _exit
  0x80919: _kill
  0x8091b: _getpid
  0x80921: mapResolution
  0x80935: analogRead
  0x809d1: analogOutputInit
  0x809d5: pinMode
  0x80add: digitalWrite
  0x80b4d: _ZN5Print5writeEPKhj
  0x80b6f: _ZN5Print5writeEPKc
  0x80b8d: _ZN5Print5printEc
  0x80b99: _ZN5Print7printlnEv
  0x80ba9: _ZN5Print11printNumberEmh
  0x80be9: _ZN5Print10printFloatEdh
  0x80d31: _ZN5Print7printlnEdi
  0x80d4d: tickReset
  0x80d6d: _ZN10RingBufferC2Ev
  0x80d87: _ZN10RingBuffer10store_charEh
  0x80da5: _ZN9UARTClasscvbEv
  0x80da9: _ZN9UARTClass9availableEv
  0x80dbb: _ZN9UARTClass4peekEv
  0x80dd7: _ZN9UARTClass4readEv
  0x80e01: _ZN9UARTClass5flushEv
  0x80e19: _ZN9UARTClass5writeEh
  0x80e6d: _ZN9UARTClass3endEv
  0x80ea9: _ZN9UARTClassC2EP4Uart4IRQnmP10RingBufferS4_
  0x80ecd: _ZN9UARTClass4initEmm
  0x80f3d: _ZN9UARTClass5beginEm
  0x80f45: _ZN9UARTClass10IrqHandlerEv
  0x80f8f: _ZN10USARTClass5beginEm
  0x80f99: _ZN10USARTClassC2EP5Usart4IRQnmP10RingBufferS4_
  0x80fbd: initVariant
  0x80fc1: main
  0x80fed: _watchdogDefaultSetup
  0x80ff9: delay
  0x80ffd: TimeTick_Increment
  0x8100d: WDT_Disable
  0x81015: __fpclassifyd
  0x81065: __aeabi_drsub
  0x8106d: __subdf3
  0x81071: __aeabi_dadd
  0x812e9: __floatunsidf
  0x81309: __aeabi_i2d
  0x8132d: __aeabi_f2d
  0x81369: __floatundidf
  0x81379: __aeabi_l2d
  0x813d5: __muldf3
  0x81629: __divdf3
  0x817f9: __gedf2
  0x81801: __ledf2
  0x81809: __nedf2
  0x81885: __aeabi_cdrcmple
  0x81895: __aeabi_cdcmpeq
  0x818a5: __aeabi_dcmpeq
  0x818b9: __aeabi_dcmplt
  0x818cd: __aeabi_dcmple
  0x818e1: __aeabi_dcmpge
  0x818f5: __aeabi_dcmpgt
  0x81909: __aeabi_d2uiz
  0x81949: __truncdfsf2
  0x819e9: __libc_init_array
  0x81a39: iprintf
  0x81a61: memset
  0x81af5: strlen
  0x81b55: kill
  0x81b65: __sprint_r.part.0
  0x81bdd: _vfiprintf_r
  0x82831: __sbprintf
  0x828ad: __swsetup_r
  0x82971: register_fini
  0x82985: atexit
  0x82991: __sflush_r
  0x82ad9: _fflush_r
  0x82b05: _cleanup_r
  0x82b11: __sinit
  0x82c05: __sfp_lock_acquire
  0x82c09: __sfp_lock_release
  0x82c0d: __libc_fini_array
  0x82c3d: _fputwc_r
  0x82cfd: _malloc_trim_r
  0x82d99: _free_r
  0x82f31: __sfvwrite_r
  0x83245: _fwalk
  0x8328d: __locale_charset
  0x83295: __locale_mb_cur_max
  0x832a1: __smakebuf_r
  0x83381: _malloc_r
  0x838b9: memchr
  0x8394d: memcpy
  0x83a39: memmove
  0x83b05: __malloc_lock
  0x83b09: __malloc_unlock
  0x83b0d: _realloc_r
  0x83ecd: _sbrk_r
  0x83ef1: _kill_r
  0x83f19: __sread
  0x83f3d: __swrite
  0x83f75: __sseek
  0x83f95: __sclose
  0x83f9d: __swbuf_r
  0x84045: _wcrtomb_r
  0x84095: __ascii_wctomb
  0x840b1: _write_r
  0x840d9: __register_exitproc
  0x84181: _close_r
  0x841a5: _fclose_r
  0x84225: fclose
  0x84235: _fstat_r
  0x8425d: _isatty_r
  0x84281: _lseek_r
  0x842a9: _read_r
  0x842d1: __aeabi_uldivmod
  0x842fd: __gnu_ldivmod_helper
  0x8432d: __gnu_uldivmod_helper
  0x8435d: __aeabi_idiv0
  0x84361: __divdi3
  0x84601: __udivdi3
  0x84890: g_APinDescription
  0x85328: _ZTV9UARTClass
  0x85358: _ZTV10USARTClass
  0x8538c: _global_impure_ptr
  0x85390: blanks.6717
  0x853d0: zeroes.6718
  0x853e1: _init
  0x853ec: __preinit_array_start
  0x853f0: __frame_dummy_init_array_entry
  0x853f8: __init_array_end
  0x853f9: _fini
  0x85404: __fini_array_start
  0x85408: _efixed
  0x85410: _etext
  0x20070000: _srelocate
  0x20070001: banzai
  0x2007002c: SystemCoreClock
  0x20070030: latestSelectedChannel.9384
  0x20070034: _readResolution
  0x20070038: _ZL5ticks
  0x20070040: impure_data
  0x20070468: _impure_ptr
  0x2007046c: lc_ctype_charset
  0x2007048c: __mb_cur_max
  0x20070490: __malloc_av_
  0x20070898: __malloc_trim_threshold
  0x2007089c: __malloc_sbrk_base
  0x200708a0: __wctomb
  0x200708a4: _erelocate
  0x200708a8: object.7862
  0x200708c0: tx_buffer2
  0x20070948: tx_buffer1
  0x200709d0: Serial
  0x200709f4: rx_buffer1
  0x20070a7c: Serial1
  0x20070aa4: Serial2
  0x20070acc: Serial3
  0x20070af4: tx_buffer3
  0x20070b7c: tx_buffer4
  0x20070c04: g_pinStatus
  0x20070c54: rx_buffer2
  0x20070cdc: rx_buffer3
  0x20070d64: rx_buffer4
  0x20070dec: gpf_isr
  0x20070df0: callbacksPioA
  0x20070e70: callbacksPioB
  0x20070ef0: callbacksPioC
  0x20070f70: callbacksPioD
  0x20070ff0: heap.6420
  0x20070ff4: _dwTickCount
  0x20070ff8: __malloc_max_total_mem
  0x20070ffc: __malloc_max_sbrked_mem
  0x20071000: __malloc_top_pad
  0x20071004: __malloc_current_mallinfo
  0x2007102c: errno
  0x20071030: _end
  0x20088000: _estack
