interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: SAM3-RIOT-ADC.bin
    permissions: rwx
    size: 0x12070
symbols:
  0x0: _sbackup_data
  0x80000: cortex_vector_base
  0x80040: vector_cpu
  0x800f5: isr_trng
  0x800f9: _init
  0x800fb: _fini
  0x800fd: _sbrk_r
  0x80139: _read_r
  0x80141: _write_r
  0x80149: _close_r
  0x80153: _lseek_r
  0x8015d: _fstat_r
  0x80167: _isatty_r
  0x80175: sched_run
  0x801d9: sched_set_status
  0x80259: sched_switch
  0x80289: sched_task_exit
  0x802c5: thread_stack_init
  0x8032d: cpu_switch_context_exit
  0x80332: unreachable329
  0x80335: thread_yield_higher
  0x80345: isr_pendsv
  0x80361: isr_svc
  0x80365: context_restore
  0x8037d: hard_fault_default
  0x80390: fix_msp
  0x80396: test_sp
  0x803a4: use_psp
  0x803a8: out
  0x803c1: nmi_default
  0x803d1: mem_manage_default
  0x803e1: bus_fault_default
  0x803f1: usage_fault_default
  0x80401: debug_mon_default
  0x80411: dummy_handler_default
  0x80421: pre_startup
  0x80423: post_startup
  0x80425: reset_handler_default
  0x80491: hard_fault_handler
  0x80619: irq_disable
  0x80621: irq_enable
  0x80629: irq_restore
  0x8062f: irq_is_in
  0x80637: stdio_init
  0x80645: stdio_read
  0x8064b: stdio_write
  0x8065d: pm_off
  0x80665: board_init
  0x8067d: panic_arch
  0x80681: core_panic
  0x806c5: main_trampoline
  0x806dd: idle_thread
  0x806e5: kernel_init
  0x8073d: thread_add_to_list
  0x8076d: thread_create
  0x80865: pm_set_lowest
  0x80869: cpu_init
  0x808e9: isr_handler
  0x80925: uart_write
  0x80945: uart_poweron
  0x80965: uart_init
  0x80a11: isr_uart
  0x80a17: isr_usart0
  0x80a1d: isr_usart1
  0x80a23: isr_usart3
  0x80a29: gpio_init
  0x80a99: gpio_init_mux
  0x80acd: periph_init
  0x80ad3: main
  0x80aeb: auto_init
  0x80aed: cortexm_init
  0x80b2d: spi_init_pins
  0x80b79: spi_init
  0x80b99: adc_init
  0x80bfd: adc_sample
  0x80c6d: _mutex_lock
  0x80ccd: mutex_unlock
  0x80d19: __libc_init_array
  0x80d61: _malloc_r
  0x80e15: iprintf
  0x80e45: _puts_r
  0x80f21: puts
  0x80f31: __swbuf_r
  0x80fd5: __swsetup_r
  0x810b1: __sflush_r
  0x811bd: _fflush_r
  0x81235: std
  0x8127d: _cleanup_r
  0x81289: __sfmoreglue
  0x812b5: __sfp_lock_acquire
  0x812c1: __sfp_lock_release
  0x812cd: __sinit_lock_acquire
  0x812d9: __sinit_lock_release
  0x812e5: __sinit
  0x81355: __sfp
  0x813e1: _fwalk_reent
  0x8141f: __retarget_lock_init_recursive
  0x81421: __retarget_lock_acquire_recursive
  0x81423: __retarget_lock_release_recursive
  0x81425: __swhatbuf_r
  0x8146d: __smakebuf_r
  0x814ed: memset
  0x814fd: __malloc_lock
  0x81509: __malloc_unlock
  0x81515: _free_r
  0x815ad: __sfputc_r
  0x815d7: __sfputs_r
  0x815fd: _vfprintf_r
  0x8185d: _printf_common
  0x8193d: _printf_i
  0x81b89: __sread
  0x81bab: __swrite
  0x81be3: __sseek
  0x81c07: __sclose
  0x81c0f: memchr
  0x81eb1: assert_crash_message
  0x81f0c: uart_config
  0x81f4c: spi_config
  0x81f64: _global_impure_ptr
  0x81f68: __sf_fake_stderr
  0x81f88: __sf_fake_stdin
  0x81fa8: __sf_fake_stdout
  0x81ffc: __preinit_array_start
  0x82070: _sbackup_data_load
  0x20070000: isr_stack
  0x20070200: _estack
  0x20070204: idle_name
  0x20070208: main_name
  0x2007020c: _impure_ptr
  0x20070210: impure_data
  0x20070270: _tcb_name_offset
  0x20070271: max_threads
  0x20070274: _erelocate
  0x20070278: sched_active_pid
  0x2007027c: sched_active_thread
  0x20070280: sched_context_switch_request
  0x20070284: sched_num_threads
  0x20070288: sched_runqueues
  0x200702c8: sched_threads
  0x2007034c: crashed
  0x20070350: idle_stack
  0x20070450: main_stack
  0x20070a50: ctx
  0x20070a70: locks
  0x20070a74: lock
  0x20070a78: __malloc_free_list
  0x20070a7c: __malloc_sbrk_start
  0x20070a80: __lock___atexit_recursive_mutex
  0x20070a81: __lock___arc4random_mutex
  0x20070a82: __lock___env_recursive_mutex
  0x20070a83: __lock___sinit_recursive_mutex
  0x20070a84: __lock___malloc_recursive_mutex
  0x20070a85: __lock___at_quick_exit_mutex
  0x20070a86: __lock___dd_hash_mutex
  0x20070a87: __lock___tz_mutex
  0x20070a88: __lock___sfp_recursive_mutex
  0x20070a8c: __noinit_end
  0x20088000: _eheap
