interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: ARDUINO-SAM3-GPIO.bin
    permissions: rwx
    size: 0x15054
symbols:
  0x0: __register_frame_info
  0x80000: exception_table
  0x800f5: __do_global_dtors_aux
  0x80119: frame_dummy
  0x80149: setup
  0x80161: loop
  0x80185: _Z11serialEventv
  0x80189: UART_Handler
  0x80195: _Z12serialEvent1v
  0x80197: _Z12serialEvent2v
  0x80199: _Z12serialEvent3v
  0x8019d: USART0_Handler
  0x801a9: USART1_Handler
  0x801b5: USART3_Handler
  0x801c1: init
  0x802e9: _GLOBAL__sub_I_g_APinDescription
  0x803bd: _Z14serialEventRunv
  0x80401: PIO_PullUp
  0x8040b: PIO_Get
  0x8041f: PIO_SetPeripheral
  0x80445: PIO_SetInput
  0x8046b: PIO_SetOutput
  0x80491: PIO_Configure
  0x804f5: PIO_GetOutputDataStatus
  0x80509: pmc_enable_periph_clk
  0x8054d: pmc_disable_periph_clk
  0x8058d: SystemInit
  0x80615: Reset_Handler
  0x8068d: adc_init
  0x80725: adc_configure_trigger
  0x80733: adc_configure_timing
  0x8074d: adc_disable_channel
  0x80757: adc_disable_all_channel
  0x8075f: adc_disable_interrupt
  0x80765: UOTGHS_Handler
  0x80775: PIOA_Handler
  0x807ad: PIOB_Handler
  0x807e5: PIOC_Handler
  0x8081d: PIOD_Handler
  0x80855: SPI0_Handler
  0x80857: SVC_Handler
  0x8085b: PendSV_Handler
  0x8085f: SysTick_Handler
  0x80875: sysTickHook
  0x80879: svcHook
  0x8087d: _sbrk
  0x80899: link
  0x8089f: _close
  0x808a5: _fstat
  0x808af: _isatty
  0x808b3: _lseek
  0x808b7: _read
  0x808bd: _write
  0x808e1: _exit
  0x808f1: _kill
  0x808f3: _getpid
  0x808f9: analogOutputInit
  0x808fd: pinMode
  0x80a05: digitalWrite
  0x80a75: digitalRead
  0x80ab9: tickReset
  0x80ad9: _ZN10RingBufferC2Ev
  0x80af3: _ZN10RingBuffer10store_charEh
  0x80b11: _ZN9UARTClasscvbEv
  0x80b15: _ZN9UARTClass9availableEv
  0x80b27: _ZN9UARTClass4peekEv
  0x80b43: _ZN9UARTClass4readEv
  0x80b6d: _ZN9UARTClass5flushEv
  0x80b85: _ZN9UARTClass5writeEh
  0x80bd9: _ZN9UARTClass3endEv
  0x80c15: _ZN9UARTClassC2EP4Uart4IRQnmP10RingBufferS4_
  0x80c39: _ZN9UARTClass4initEmm
  0x80ca9: _ZN9UARTClass5beginEm
  0x80cb1: _ZN9UARTClass10IrqHandlerEv
  0x80cfb: _ZN10USARTClass5beginEm
  0x80d05: _ZN10USARTClassC2EP5Usart4IRQnmP10RingBufferS4_
  0x80d29: initVariant
  0x80d2d: main
  0x80d59: _watchdogDefaultSetup
  0x80d65: delay
  0x80d67: _ZN5Print5writeEPKhj
  0x80d89: TimeTick_Increment
  0x80d99: WDT_Disable
  0x80da1: __libc_init_array
  0x80df1: iprintf
  0x80e19: memset
  0x80ead: strlen
  0x80f0d: kill
  0x80f1d: __sprint_r.part.0
  0x80f95: _vfiprintf_r
  0x81be9: __sbprintf
  0x81c65: __swsetup_r
  0x81d29: register_fini
  0x81d3d: atexit
  0x81d49: __sflush_r
  0x81e91: _fflush_r
  0x81ebd: _cleanup_r
  0x81ec9: __sinit
  0x81fbd: __sfp_lock_acquire
  0x81fc1: __sfp_lock_release
  0x81fc5: __libc_fini_array
  0x81ff5: _fputwc_r
  0x820b5: _malloc_trim_r
  0x82151: _free_r
  0x822e9: __sfvwrite_r
  0x825fd: _fwalk
  0x82645: __locale_charset
  0x8264d: __locale_mb_cur_max
  0x82659: __smakebuf_r
  0x82739: _malloc_r
  0x82c71: memchr
  0x82d05: memcpy
  0x82df1: memmove
  0x82ebd: __malloc_lock
  0x82ec1: __malloc_unlock
  0x82ec5: _realloc_r
  0x83285: _sbrk_r
  0x832a9: _kill_r
  0x832d1: __sread
  0x832f5: __swrite
  0x8332d: __sseek
  0x8334d: __sclose
  0x83355: __swbuf_r
  0x833fd: _wcrtomb_r
  0x8344d: __ascii_wctomb
  0x83469: _write_r
  0x83491: __register_exitproc
  0x83539: _close_r
  0x8355d: _fclose_r
  0x835dd: fclose
  0x835ed: _fstat_r
  0x83615: _isatty_r
  0x83639: _lseek_r
  0x83661: _read_r
  0x83689: __aeabi_uldivmod
  0x836b5: __gnu_ldivmod_helper
  0x836e5: __gnu_uldivmod_helper
  0x83715: __aeabi_idiv0
  0x83719: __divdi3
  0x839b9: __udivdi3
  0x83c48: g_APinDescription
  0x846d0: _ZTV9UARTClass
  0x84700: _ZTV10USARTClass
  0x84734: _global_impure_ptr
  0x84738: blanks.6717
  0x84778: zeroes.6718
  0x84789: _init
  0x84794: __preinit_array_start
  0x84798: __frame_dummy_init_array_entry
  0x847a0: __init_array_end
  0x847a1: _fini
  0x847ac: __fini_array_start
  0x847b0: _efixed
  0x847b8: _etext
  0x20070000: _srelocate
  0x20070001: banzai
  0x2007002c: SystemCoreClock
  0x20070030: _ZL5ticks
  0x20070038: impure_data
  0x20070460: _impure_ptr
  0x20070464: lc_ctype_charset
  0x20070484: __mb_cur_max
  0x20070488: __malloc_av_
  0x20070890: __malloc_trim_threshold
  0x20070894: __malloc_sbrk_base
  0x20070898: __wctomb
  0x2007089c: _erelocate
  0x200708a0: object.7862
  0x200708b8: buttonState
  0x200708bc: tx_buffer2
  0x20070944: tx_buffer1
  0x200709cc: Serial
  0x200709f0: rx_buffer1
  0x20070a78: Serial1
  0x20070aa0: Serial2
  0x20070ac8: Serial3
  0x20070af0: tx_buffer3
  0x20070b78: tx_buffer4
  0x20070c00: g_pinStatus
  0x20070c50: rx_buffer2
  0x20070cd8: rx_buffer3
  0x20070d60: rx_buffer4
  0x20070de8: gpf_isr
  0x20070dec: callbacksPioA
  0x20070e6c: callbacksPioB
  0x20070eec: callbacksPioC
  0x20070f6c: callbacksPioD
  0x20070fec: heap.6420
  0x20070ff0: _dwTickCount
  0x20070ff4: __malloc_max_total_mem
  0x20070ff8: __malloc_max_sbrked_mem
  0x20070ffc: __malloc_top_pad
  0x20071000: __malloc_current_mallinfo
  0x20071028: errno
  0x2007102c: _end
  0x20088000: _estack
