interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: SAM3-RIOT-GPIO_INT.bin
    permissions: rwx
    size: 0x12100
symbols:
  0x0: _sbackup_data
  0x80000: cortex_vector_base
  0x80040: vector_cpu
  0x800f5: isr_trng
  0x800f9: _init
  0x800fb: _fini
  0x800fd: _sbrk_r
  0x80139: _read_r
  0x80141: _write_r
  0x80149: _close_r
  0x80153: _lseek_r
  0x8015d: _fstat_r
  0x80167: _isatty_r
  0x80175: sched_run
  0x801d9: sched_set_status
  0x80259: sched_switch
  0x80289: sched_task_exit
  0x802c5: thread_stack_init
  0x8032d: cpu_switch_context_exit
  0x80332: unreachable329
  0x80335: thread_yield_higher
  0x80345: isr_pendsv
  0x80361: isr_svc
  0x80365: context_restore
  0x8037d: hard_fault_default
  0x80390: fix_msp
  0x80396: test_sp
  0x803a4: use_psp
  0x803a8: out
  0x803c1: nmi_default
  0x803d1: mem_manage_default
  0x803e1: bus_fault_default
  0x803f1: usage_fault_default
  0x80401: debug_mon_default
  0x80411: dummy_handler_default
  0x80421: pre_startup
  0x80423: post_startup
  0x80425: reset_handler_default
  0x80491: hard_fault_handler
  0x80619: irq_disable
  0x80621: irq_enable
  0x80629: irq_restore
  0x8062f: irq_is_in
  0x80637: stdio_init
  0x80645: stdio_read
  0x8064b: stdio_write
  0x8065d: pm_off
  0x80665: board_init
  0x8067d: panic_arch
  0x80681: core_panic
  0x806c5: main_trampoline
  0x806dd: idle_thread
  0x806e5: kernel_init
  0x8073d: thread_create
  0x80835: pm_set_lowest
  0x80839: cpu_init
  0x808b9: isr_handler
  0x808f5: uart_write
  0x80915: uart_poweron
  0x80935: uart_init
  0x809e1: isr_uart
  0x809e7: isr_usart0
  0x809ed: isr_usart1
  0x809f3: isr_usart3
  0x809f9: _write_map
  0x80a29: isr_handler
  0x80a89: gpio_init
  0x80b39: gpio_init_mux
  0x80b6d: gpio_irq_enable
  0x80b95: gpio_init_int
  0x80c55: isr_pioa
  0x80c61: isr_piob
  0x80c6d: isr_pioc
  0x80c79: isr_piod
  0x80c85: periph_init
  0x80c8b: gpioCB
  0x80c8d: main
  0x80cb9: auto_init
  0x80cbd: cortexm_init
  0x80cfd: spi_init_pins
  0x80d49: spi_init
  0x80d69: __libc_init_array
  0x80db1: _malloc_r
  0x80e65: iprintf
  0x80e95: _puts_r
  0x80f71: puts
  0x80f81: __swbuf_r
  0x81025: __swsetup_r
  0x81101: __sflush_r
  0x8120d: _fflush_r
  0x81285: std
  0x812cd: _cleanup_r
  0x812d9: __sfmoreglue
  0x81305: __sfp_lock_acquire
  0x81311: __sfp_lock_release
  0x8131d: __sinit_lock_acquire
  0x81329: __sinit_lock_release
  0x81335: __sinit
  0x813a5: __sfp
  0x81431: _fwalk_reent
  0x8146f: __retarget_lock_init_recursive
  0x81471: __retarget_lock_acquire_recursive
  0x81473: __retarget_lock_release_recursive
  0x81475: __swhatbuf_r
  0x814bd: __smakebuf_r
  0x8153d: memset
  0x8154d: __malloc_lock
  0x81559: __malloc_unlock
  0x81565: _free_r
  0x815fd: __sfputc_r
  0x81627: __sfputs_r
  0x8164d: _vfprintf_r
  0x818ad: _printf_common
  0x8198d: _printf_i
  0x81bd9: __sread
  0x81bfb: __swrite
  0x81c33: __sseek
  0x81c57: __sclose
  0x81c5f: memchr
  0x81f01: assert_crash_message
  0x81f5c: uart_config
  0x81f9c: spi_config
  0x81fb4: _global_impure_ptr
  0x81fb8: __sf_fake_stderr
  0x81fd8: __sf_fake_stdin
  0x81ff8: __sf_fake_stdout
  0x8204c: __preinit_array_start
  0x82100: _sbackup_data_load
  0x20070000: isr_stack
  0x20070200: _estack
  0x20070204: idle_name
  0x20070208: main_name
  0x2007020c: exti_map
  0x2007024c: _impure_ptr
  0x20070250: impure_data
  0x200702b0: _tcb_name_offset
  0x200702b1: max_threads
  0x200702b4: _erelocate
  0x200702b8: sched_active_pid
  0x200702bc: sched_active_thread
  0x200702c0: sched_context_switch_request
  0x200702c4: sched_num_threads
  0x200702c8: sched_runqueues
  0x20070308: sched_threads
  0x2007038c: crashed
  0x20070390: idle_stack
  0x20070490: main_stack
  0x20070a90: ctx
  0x20070ab0: exti_ctx
  0x20070ae8: callGPIO
  0x20070aec: locks
  0x20070af0: __malloc_free_list
  0x20070af4: __malloc_sbrk_start
  0x20070af8: __lock___atexit_recursive_mutex
  0x20070af9: __lock___arc4random_mutex
  0x20070afa: __lock___env_recursive_mutex
  0x20070afb: __lock___sinit_recursive_mutex
  0x20070afc: __lock___malloc_recursive_mutex
  0x20070afd: __lock___at_quick_exit_mutex
  0x20070afe: __lock___dd_hash_mutex
  0x20070aff: __lock___tz_mutex
  0x20070b00: __lock___sfp_recursive_mutex
  0x20070b04: __noinit_end
  0x20088000: _eheap
