interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: SAM3-RIOT-USART.bin
    permissions: rwx
    size: 0x1205c
symbols:
  0x0: _sbackup_data
  0x80000: cortex_vector_base
  0x80040: vector_cpu
  0x800f5: isr_trng
  0x800f9: _init
  0x800fb: _fini
  0x800fd: _sbrk_r
  0x80139: _read_r
  0x80141: _write_r
  0x80149: _close_r
  0x80153: _lseek_r
  0x8015d: _fstat_r
  0x80167: _isatty_r
  0x80175: sched_run
  0x801d9: sched_set_status
  0x80259: sched_switch
  0x80289: sched_task_exit
  0x802c5: thread_stack_init
  0x8032d: cpu_switch_context_exit
  0x80332: unreachable329
  0x80335: thread_yield_higher
  0x80345: isr_pendsv
  0x80361: isr_svc
  0x80365: context_restore
  0x8037d: hard_fault_default
  0x80390: fix_msp
  0x80396: test_sp
  0x803a4: use_psp
  0x803a8: out
  0x803c1: nmi_default
  0x803d1: mem_manage_default
  0x803e1: bus_fault_default
  0x803f1: usage_fault_default
  0x80401: debug_mon_default
  0x80411: dummy_handler_default
  0x80421: pre_startup
  0x80423: post_startup
  0x80425: reset_handler_default
  0x80491: hard_fault_handler
  0x80619: irq_disable
  0x80621: irq_enable
  0x80629: irq_restore
  0x8062f: irq_is_in
  0x80639: stdio_init
  0x80651: stdio_read
  0x80661: stdio_write
  0x80673: pm_off
  0x8067d: board_init
  0x80695: panic_arch
  0x80699: core_panic
  0x806dd: main_trampoline
  0x806f5: idle_thread
  0x806fd: kernel_init
  0x80755: thread_add_to_list
  0x80785: thread_create
  0x8087d: pm_set_lowest
  0x80881: cpu_init
  0x80901: isrpipe_write_one
  0x80917: isrpipe_read
  0x8093d: isr_handler
  0x80979: uart_write
  0x80999: uart_poweron
  0x809b9: uart_init
  0x80a65: isr_uart
  0x80a6b: isr_usart0
  0x80a71: isr_usart1
  0x80a77: isr_usart3
  0x80a7d: gpio_init
  0x80aed: gpio_init_mux
  0x80b21: _pop
  0x80b33: tsrb_get
  0x80b59: tsrb_add_one
  0x80b7f: periph_init
  0x80b81: main
  0x80bb1: auto_init
  0x80bb5: _mutex_lock
  0x80c15: mutex_unlock
  0x80c61: cortexm_init
  0x80ca1: __libc_init_array
  0x80ce9: _malloc_r
  0x80d9d: iprintf
  0x80dcd: _puts_r
  0x80ea9: puts
  0x80eb9: __swbuf_r
  0x80f5d: __swsetup_r
  0x81039: __sflush_r
  0x81145: _fflush_r
  0x811bd: std
  0x81205: _cleanup_r
  0x81211: __sfmoreglue
  0x8123d: __sfp_lock_acquire
  0x81249: __sfp_lock_release
  0x81255: __sinit_lock_acquire
  0x81261: __sinit_lock_release
  0x8126d: __sinit
  0x812dd: __sfp
  0x81369: _fwalk_reent
  0x813a7: __retarget_lock_init_recursive
  0x813a9: __retarget_lock_acquire_recursive
  0x813ab: __retarget_lock_release_recursive
  0x813ad: __swhatbuf_r
  0x813f5: __smakebuf_r
  0x81475: memset
  0x81485: __malloc_lock
  0x81491: __malloc_unlock
  0x8149d: _free_r
  0x81535: __sfputc_r
  0x8155f: __sfputs_r
  0x81585: _vfprintf_r
  0x817e5: _printf_common
  0x818c5: _printf_i
  0x81b11: __sread
  0x81b33: __swrite
  0x81b6b: __sseek
  0x81b8f: __sclose
  0x81b97: memchr
  0x81e39: assert_crash_message
  0x81e94: uart_config
  0x81f3c: _global_impure_ptr
  0x81f40: __sf_fake_stderr
  0x81f60: __sf_fake_stdin
  0x81f80: __sf_fake_stdout
  0x81fd4: __preinit_array_start
  0x8205c: _sbackup_data_load
  0x20070000: isr_stack
  0x20070200: _estack
  0x20070204: stdio_uart_isrpipe
  0x20070218: idle_name
  0x2007021c: main_name
  0x20070220: _impure_ptr
  0x20070224: impure_data
  0x20070284: _tcb_name_offset
  0x20070285: max_threads
  0x20070288: _erelocate
  0x2007028c: sched_active_pid
  0x20070290: sched_active_thread
  0x20070294: sched_context_switch_request
  0x20070298: sched_num_threads
  0x2007029c: sched_runqueues
  0x200702dc: sched_threads
  0x20070360: _rx_buf_mem
  0x200703a0: crashed
  0x200703a4: idle_stack
  0x200704a4: main_stack
  0x20070aa4: ctx
  0x20070ac4: __malloc_free_list
  0x20070ac8: __malloc_sbrk_start
  0x20070acc: __lock___atexit_recursive_mutex
  0x20070acd: __lock___arc4random_mutex
  0x20070ace: __lock___env_recursive_mutex
  0x20070acf: __lock___sinit_recursive_mutex
  0x20070ad0: __lock___malloc_recursive_mutex
  0x20070ad1: __lock___at_quick_exit_mutex
  0x20070ad2: __lock___dd_hash_mutex
  0x20070ad3: __lock___tz_mutex
  0x20070ad4: __lock___sfp_recursive_mutex
  0x20070ad8: __noinit_end
  0x20088000: _eheap
