interrupt_triggers:
  time_based_fuzzed:
    every_nth_tick: 0x3e8
    fuzz_mode: fuzzed
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: ARDUINO-F103-Serial.bin
    permissions: rwx
    size: 0x14dd4
symbols:
  0x0: reent.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x800010d: __do_global_dtors_aux
  0x8000131: frame_dummy
  0x8000179: strlen
  0x8000189: setup
  0x800019d: loop
  0x80001e5: SystemClock_Config
  0x8000285: Reset_Handler
  0x8000288: CopyDataInit
  0x8000290: LoopCopyDataInit
  0x800029e: FillZerobss
  0x80002a4: LoopFillZerobss
  0x80002cc: Default_Handler
  0x80002cd: USB_HP_CAN1_TX_IRQHandler
  0x80002cf: init
  0x80002d7: HAL_MspInit
  0x80002d9: HAL_InitTick
  0x8000325: HAL_Init
  0x8000349: HAL_IncTick
  0x8000361: HAL_GetTick
  0x800036d: HAL_NVIC_SetPriorityGrouping
  0x8000391: HAL_NVIC_SetPriority
  0x80003f5: HAL_NVIC_EnableIRQ
  0x8000411: HAL_SYSTICK_Config
  0x800043d: HAL_NVIC_ClearPendingIRQ
  0x800045d: HAL_SYSTICK_CLKSourceConfig
  0x800047d: HAL_SYSTICK_Callback
  0x800047f: HAL_SYSTICK_IRQHandler
  0x8000489: HAL_DMA_Abort_IT
  0x8000521: HAL_GPIO_Init
  0x800070d: HAL_GPIO_EXTI_IRQHandler
  0x8000729: I2C_Master_SB
  0x80007b3: I2C_Master_ADD10
  0x80007bf: I2C_Master_ADDR
  0x8000999: I2C_SlaveTransmit_BTF
  0x80009b9: I2C_SlaveReceive_BTF
  0x80009d9: HAL_I2C_Slave_Sequential_Transmit_IT
  0x8000a65: HAL_I2C_Slave_Sequential_Receive_IT
  0x8000af1: HAL_I2C_EnableListen_IT
  0x8000b2f: HAL_I2C_MasterTxCpltCallback
  0x8000b31: HAL_I2C_MasterRxCpltCallback
  0x8000b33: HAL_I2C_SlaveTxCpltCallback
  0x8000b35: I2C_SlaveTransmit_TXE
  0x8000b85: HAL_I2C_SlaveRxCpltCallback
  0x8000b87: I2C_SlaveReceive_RXNE
  0x8000bd3: I2C_Slave_ADDR
  0x8000bfd: I2C_Slave_AF
  0x8000c91: HAL_I2C_MemTxCpltCallback
  0x8000c93: I2C_MasterTransmit_TXE
  0x8000ddd: I2C_MasterTransmit_BTF
  0x8000e7b: HAL_I2C_MemRxCpltCallback
  0x8000e7d: I2C_MasterReceive_RXNE
  0x8000f4d: I2C_MasterReceive_BTF
  0x800104b: HAL_I2C_AbortCpltCallback
  0x800104d: I2C_ITError
  0x8001195: I2C_Slave_STOPF
  0x8001299: HAL_I2C_EV_IRQHandler
  0x8001401: HAL_I2C_ER_IRQHandler
  0x80014dd: I2C_DMAAbort
  0x800153d: RCC_Delay
  0x8001569: HAL_RCC_OscConfig
  0x8001949: HAL_RCC_GetSysClockFreq
  0x80019b5: HAL_RCC_ClockConfig
  0x8001b25: HAL_RCC_GetHCLKFreq
  0x8001b31: HAL_RCC_GetPCLK1Freq
  0x8001b51: HAL_RCC_GetPCLK2Freq
  0x8001b71: HAL_RCCEx_PeriphCLKConfig
  0x8001c85: HAL_RTC_AlarmIRQHandler
  0x8001cbd: HAL_TIM_IC_CaptureCallback
  0x8001cbf: HAL_TIM_PWM_PulseFinishedCallback
  0x8001cc1: HAL_TIM_TriggerCallback
  0x8001cc3: HAL_TIM_IRQHandler
  0x8001e3d: HAL_TIMEx_CommutationCallback
  0x8001e3f: HAL_TIMEx_BreakCallback
  0x8001e41: UART_EndRxTransfer
  0x8001e5d: UART_Transmit_IT
  0x8001ec9: UART_SetConfig
  0x8002079: UART_WaitOnFlagUntilTimeout
  0x80020dd: HAL_UART_MspInit
  0x80020df: HAL_UART_Init
  0x800213d: HAL_UART_Transmit
  0x800221f: HAL_UART_Transmit_IT
  0x8002267: HAL_UART_Receive_IT
  0x80022c3: UART_EndTransmit_IT
  0x80022dd: UART_Receive_IT
  0x800237d: HAL_UART_IRQHandler
  0x800249d: UART_DMAAbortOnError
  0x80024ad: HAL_UART_GetState
  0x80024b9: set_GPIO_Port_Clock
  0x8002561: GetCurrentMilli
  0x8002569: noOsSystickHandler
  0x800256b: SysTick_Handler
  0x800257b: hw_config_init
  0x8002587: pinmap_find_peripheral
  0x80025a1: pinmap_peripheral
  0x80025b3: pinmap_find_pin
  0x80025cb: pinmap_pin
  0x80025db: pinmap_find_function
  0x80025f7: pinmap_function
  0x800260b: pinmap_merge_peripheral
  0x800261d: HAL_RTC_AlarmAEventCallback
  0x8002635: RTC_Alarm_IRQHandler
  0x8002645: _Error_Handler
  0x8002649: SystemInit
  0x8002695: get_timer_obj
  0x8002699: HAL_TIM_OC_DelayElapsedCallback
  0x80026b3: HAL_TIM_PeriodElapsedCallback
  0x80026c1: TIM1_UP_IRQHandler
  0x80026d5: TIM2_IRQHandler
  0x80026e9: TIM3_IRQHandler
  0x80026fd: TIM4_IRQHandler
  0x8002711: get_i2c_obj
  0x8002715: HAL_I2C_AddrCallback
  0x8002765: HAL_I2C_ListenCpltCallback
  0x8002795: HAL_I2C_ErrorCallback
  0x80027ad: I2C1_EV_IRQHandler
  0x80027bd: I2C1_ER_IRQHandler
  0x80027cd: I2C2_EV_IRQHandler
  0x80027dd: I2C2_ER_IRQHandler
  0x80027ed: uart_init
  0x8002c25: uart_debug_init
  0x8002c75: uart_debug_write
  0x8002d2d: serial_rx_active
  0x8002d51: serial_tx_active
  0x8002d75: uart_getc
  0x8002db1: uart_attach_rx_callback
  0x8002e09: uart_attach_tx_callback
  0x8002e5d: uart_index
  0x8002e81: HAL_UART_RxCpltCallback
  0x8002ea5: HAL_UART_TxCpltCallback
  0x8002ef1: HAL_UART_ErrorCallback
  0x8002f31: USART1_IRQHandler
  0x8002f49: USART2_IRQHandler
  0x8002f61: USART3_IRQHandler
  0x8002f79: _sbrk
  0x8002fb5: _close
  0x8002fbb: _fstat
  0x8002fc5: _isatty
  0x8002fc9: _lseek
  0x8002fcd: _read
  0x8002fd1: _write
  0x8002fdd: _exit
  0x8002fe1: _kill
  0x8002ff1: _getpid
  0x8002ff5: millis
  0x8002ffd: _ZN14HardwareSerial16_tx_complete_irqEP8serial_s
  0x8003031: _ZN14HardwareSerial9availableEv
  0x8003045: _ZN14HardwareSerial4peekEv
  0x8003061: _ZN14HardwareSerial4readEv
  0x8003089: _ZN14HardwareSerial5flushEv
  0x800309d: _ZN14HardwareSerial16_rx_complete_irqEP8serial_s
  0x80030d9: _ZN14HardwareSerial5writeEh
  0x8003129: _Z14serialEventRunv
  0x8003155: _ZN14HardwareSerial4initEv
  0x8003179: _ZN14HardwareSerial5beginEmh
  0x8003235: _ZN14HardwareSerial5setRxEm
  0x800324d: _ZN14HardwareSerial5setTxEm
  0x8003265: _ZN14HardwareSerialC1EPv
  0x80032c1: _Z41__static_initialization_and_destruction_0ii
  0x80032e5: _GLOBAL__sub_I_Serial2
  0x80032f3: _ZNK9IPAddress7printToER5Print
  0x800332d: _ZN9IPAddressC1Ehhhh
  0x8003349: _Z41__static_initialization_and_destruction_0ii
  0x8003375: _GLOBAL__sub_I__ZN9IPAddressC2Ev
  0x8003383: _ZN5Print5writeEPKhj
  0x80033a7: _ZN5Print5printEc
  0x80033b1: _ZN5Print11printNumberEmh
  0x800340b: _ZN5Print5printEli
  0x800344b: _ZN5Print5printEii
  0x8003453: _ZN5Print5printEmi
  0x8003469: _ZN5Print5printEhi
  0x8003471: _ZN6Stream9timedPeekEv
  0x800349d: _ZN6Stream13peekNextDigitE13LookaheadModeb
  0x800354d: _ZN6Stream8parseIntE13LookaheadModec
  0x80035a9: _Z11initVariantv
  0x80035ab: _Z7premainv
  0x80035b9: main
  0x80035d9: _ZL10get_pin_idt
  0x80035ed: __tcf_0
  0x8003615: _Z41__static_initialization_and_destruction_0ii
  0x80036c1: EXTI0_IRQHandler
  0x80036cb: EXTI1_IRQHandler
  0x80036d5: EXTI2_IRQHandler
  0x80036df: EXTI3_IRQHandler
  0x80036e9: EXTI4_IRQHandler
  0x80036f3: EXTI9_5_IRQHandler
  0x8003709: EXTI15_10_IRQHandler
  0x8003721: _ZNKSt8functionIFvvEEclEv
  0x8003731: HAL_GPIO_EXTI_Callback
  0x8003751: _GLOBAL__sub_I__Z22stm32_interrupt_enableP12GPIO_TypeDeftSt8functionIFvvEEm
  0x800375f: __aeabi_atexit
  0x8003769: __assert_func
  0x80037a5: __cxa_atexit
  0x80037c1: fiprintf
  0x80037e5: __libc_init_array
  0x800382d: memset
  0x800383d: _free_r
  0x80038d5: _malloc_r
  0x8003991: __sfputc_r
  0x80039bd: __sfputs_r
  0x80039e1: _vfiprintf_r
  0x8003c0d: _printf_common
  0x8003cfd: _printf_i
  0x8003f3d: iprintf
  0x8003f6d: _sbrk_r
  0x8003f8d: __swbuf_r
  0x8004031: __swsetup_r
  0x800410d: abort
  0x800411d: __sflush_r
  0x800422d: _fflush_r
  0x8004281: _cleanup_r
  0x800428d: std.isra.0
  0x80042d5: __sfmoreglue
  0x8004301: __sinit
  0x8004361: __sfp
  0x80043d9: _fwalk_reent
  0x8004415: __swhatbuf_r
  0x800445d: __smakebuf_r
  0x80044dd: memchr
  0x80044f9: __malloc_lock
  0x80044fb: __malloc_unlock
  0x80044fd: _raise_r
  0x800454d: raise
  0x800455d: _kill_r
  0x8004581: _getpid_r
  0x8004585: __sread
  0x80045a7: __swrite
  0x80045df: __sseek
  0x8004603: __sclose
  0x800460d: _write_r
  0x8004631: _close_r
  0x8004651: _fstat_r
  0x8004675: _isatty_r
  0x8004695: _lseek_r
  0x80046b9: _read_r
  0x80046dd: _ZSt25__throw_bad_function_callv
  0x80046e5: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKSsj
  0x80047a9: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKSsj
  0x800486d: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x80048f1: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x8004974: __EH_FRAME_BEGIN__
  0x8004975: _init
  0x8004981: _fini
  0x800498c: _etext
  0x80049a0: PinMap_UART_RX
  0x80049e8: PinMap_UART_TX
  0x8004a8c: digitalPin
  0x8004ac8: AHBPrescTable
  0x8004ad8: APBPrescTable
  0x8004b98: _ZTV14HardwareSerial
  0x8004bb8: _ZZN14HardwareSerial5beginEmhE19__PRETTY_FUNCTION__
  0x8004bec: _ZTV9IPAddress
  0x8004c34: _global_impure_ptr
  0x8004c6c: __sf_fake_stderr
  0x8004c8c: __sf_fake_stdin
  0x8004cac: __sf_fake_stdout
  0x8004ccc: __exidx_end
  0x8004cd0: __frame_dummy_init_array_entry
  0x8004cf0: __init_array_end
  0x8004cf4: _sidata
  0x20000000: __dso_handle
  0x20000004: uwTickFreq
  0x20000008: uwTickPrio
  0x2000000c: SystemCoreClock
  0x20000010: serial_debug
  0x2000007c: _impure_ptr
  0x20000080: impure_data
  0x200000e0: _edata
  0x200000e4: object.8672
  0x200000fc: RTCUserCallback
  0x20000100: RtcHandle
  0x20000114: callbackUserData
  0x20000118: timer_handles
  0x20000170: i2c_handles
  0x20000178: rx_callback
  0x2000018c: rx_callback_obj
  0x200001a0: tx_callback
  0x200001b4: tx_callback_obj
  0x200001c8: uart_handlers
  0x200001dc: heap_end.4572
  0x200001e0: Serial2
  0x20000324: _ZL11INADDR_NONE
  0x2000032c: _ZL13gpio_irq_conf
  0x2000046c: __malloc_free_list
  0x20000470: __malloc_sbrk_start
  0x20000474: _ZGVNSt7collateIcE2idE
  0x20000478: _ZGVNSt8messagesIcE2idE
  0x2000047c: _ZGVNSt8time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000480: _ZGVNSt8time_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000484: _ZGVNSt11__timepunctIcE2idE
  0x20000488: _ZGVNSt7num_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x2000048c: _ZGVNSt7num_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000490: _ZGVNSt8numpunctIcE2idE
  0x20000494: _ZGVNSt9money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000498: _ZGVNSt9money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x2000049c: _ZGVNSt10moneypunctIcLb1EE2idE
  0x200004a0: _ZGVNSt10moneypunctIcLb0EE2idE
  0x200004a4: _ZGVNSt7collateIwE2idE
  0x200004a8: _ZGVNSt8messagesIwE2idE
  0x200004ac: _ZGVNSt8time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004b0: _ZGVNSt8time_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004b4: _ZGVNSt11__timepunctIwE2idE
  0x200004b8: _ZGVNSt7num_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004bc: _ZGVNSt7num_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004c0: _ZGVNSt8numpunctIwE2idE
  0x200004c4: _ZGVNSt9money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004c8: _ZGVNSt9money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004cc: _ZGVNSt10moneypunctIwLb1EE2idE
  0x200004d0: _ZGVNSt10moneypunctIwLb0EE2idE
  0x200004d4: _ZGVNSt7__cxx117collateIwE2idE
  0x200004d8: _ZGVNSt7__cxx118messagesIwE2idE
  0x200004dc: _ZGVNSt7__cxx118time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004e0: _ZGVNSt7__cxx118numpunctIwE2idE
  0x200004e4: _ZGVNSt7__cxx119money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004e8: _ZGVNSt7__cxx119money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200004ec: _ZGVNSt7__cxx1110moneypunctIwLb1EE2idE
  0x200004f0: _ZGVNSt7__cxx1110moneypunctIwLb0EE2idE
  0x200004f4: _ZGVNSt7__cxx117collateIcE2idE
  0x200004f8: _ZGVNSt7__cxx118messagesIcE2idE
  0x200004fc: _ZGVNSt7__cxx118time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000500: _ZGVNSt7__cxx118numpunctIcE2idE
  0x20000504: _ZGVNSt7__cxx119money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000508: _ZGVNSt7__cxx119money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x2000050c: _ZGVNSt7__cxx1110moneypunctIcLb1EE2idE
  0x20000510: _ZGVNSt7__cxx1110moneypunctIcLb0EE2idE
  0x20000514: uwTick
  0x20000518: errno
  0x2000051c: _end
  0x20005000: _estack
  0xf108f85f: BootRAM
